import Link from 'next/link';
/* API-selected media can come from approved external asset hosts; use a plain image to avoid an unbounded Next image allowlist. */
/* eslint-disable @next/next/no-img-element */
import type { CountryPage, ProfileSummary, Section } from '@/lib/countries';
import { SiteFooter, SiteHeader } from './SiteChrome';

const sectionTitles: Record<string, string> = {
  'why-study': 'Why study here?', universities: 'Universities', subjects: 'Subjects and programmes', intakes: 'Intakes', documents: 'Documents', 'cost-of-study': 'Cost of study', scholarships: 'Scholarships', 'visa-process': 'Visa process', 'work-opportunities': 'Work opportunities', 'language-requirements': 'Language requirements', events: 'Events', cities: 'Cities', 'life-and-culture': 'Life and culture', 'living-costs': 'Living costs', careers: 'Careers', 'application-steps': 'Application steps', guides: 'Guides', faqs: 'Frequently asked questions', 'consultant-cta': 'Plan with guidance', 'trust-disclaimer': 'Source and trust note', hero: 'Overview',
};
const href = (value: string | null | undefined, fallback = '#consultation') => value && (/^\//.test(value) || /^#[a-zA-Z0-9_-]+$/.test(value) || /^https:\/\//.test(value)) ? value : fallback;

export function CountryPageView({ page }: { page: CountryPage }) {
  const { country, profiles, sections, faqs, consultantCards } = page;
  const navItems = [...sections].sort((a, b) => a.displayOrder - b.displayOrder).map((section) => ({ id: section.sectionKey, label: section.heading ?? sectionTitles[section.sectionKey] ?? section.sectionKey }));
  const facts = factsFor(profiles);
  return <main><SiteHeader detail /><section className="detail-hero"><div className="shell detail-hero-grid"><div><Link className="back-link" href="/countries">← All destinations</Link><p className="eyebrow">Study destination · {country.continent.name}</p><h1>{country.pageHeading || `Study in ${country.name}`}</h1><p className="hero-copy">{country.shortDescription}</p><Link className="button" href="#consultation">Talk to a counsellor</Link></div><div className="hero-card">{country.flag ? <img src={country.flag.url} alt={country.flag.alt || `${country.name} flag`} /> : <div className="hero-placeholder" aria-hidden="true">{country.name.slice(0, 1)}</div>}<span>{country.name}</span><small>{country.continent.name}</small></div></div></section>
    {navItems.length ? <nav className="detail-tabs" aria-label="On this page"><div className="shell">{navItems.map((item) => <a key={item.id} href={`#country-section-${item.id}`}>{item.label}</a>)}{facts.length ? <a href="#facts">At a glance</a> : null}{faqs.length ? <a href="#faqs">FAQs</a> : null}<a href="#consultation">Consultation</a></div></nav> : null}
    <div className="shell detail-layout"><div className="detail-main"><p className="eyebrow">Your destination guide</p>{sections.length ? sections.map((section) => <EditorialSection key={section.id} section={section} />) : <div className="empty-state"><h2>More guidance is being prepared</h2><p>Only published country information is shown here. Check back for additional sections.</p></div>}{faqs.length ? <section id="faqs" className="editorial-section"><p className="eyebrow">Questions answered</p><h2>Frequently asked questions</h2><div className="faq-list">{faqs.map((faq) => <details key={faq.id}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section> : null}</div>{facts.length ? <aside id="facts" className="facts-panel"><p className="eyebrow">At a glance</p><h2>{country.name}</h2>{facts.map((fact) => <Fact key={fact.label} label={fact.label} value={fact.value} />)}</aside> : null}</div>
    <section id="consultation" className="consultation-band"><div className="shell consultation-inner"><div><p className="eyebrow">Plan with confidence</p><h2>Get a personalised study plan</h2><p>Use the published country guidance to frame your next conversation.</p></div><Link className="button light" href="#consultants">Explore guidance</Link></div></section>
    {consultantCards.length ? <section id="consultants" className="shell consultants"><p className="eyebrow">Guidance for your journey</p><h2>Explore consultation options</h2><div className="consultant-grid">{consultantCards.map((card) => <article key={card.id} className="consultant-card">{card.featuredMediaId ? null : null}<h3>{card.title}</h3><p>{card.shortDescription}</p><Link href={href(card.ctaUrl)}>{card.ctaLabel} →</Link></article>)}</div></section> : null}<SiteFooter /></main>;
}

function factsFor(profiles: ProfileSummary) {
  const values: Array<{ label: string; value: string | number | null }> = [];
  if (profiles.statistics?.universitiesCount != null) values.push({ label: 'Universities', value: profiles.statistics.universitiesCount });
  if (profiles.statistics?.coursesCount != null) values.push({ label: 'Courses', value: profiles.statistics.coursesCount });
  if (profiles.cost?.tuitionMin) values.push({ label: 'Tuition', value: `${profiles.cost.currencySymbol ?? profiles.cost.currencyCode} ${profiles.cost.tuitionMin}${profiles.cost.tuitionMax ? `–${profiles.cost.tuitionMax}` : '+'}` });
  if (profiles.intakes.length) values.push({ label: 'Major intakes', value: profiles.intakes.map((item) => item.shortLabel ?? item.name).join(', ') });
  return values;
}
function Fact({ label, value }: { label: string; value: string | number | null | undefined }) { return <div className="fact"><span>{label}</span><strong>{value ?? 'Not published'}</strong></div>; }

function EditorialSection({ section }: { section: Section }) {
  const body = section.bodyJson ?? {};
  const title = section.heading ?? sectionTitles[section.sectionKey] ?? section.sectionKey;
  return <article id={`country-section-${section.sectionKey}`} className={`editorial-section section-${section.sectionType.toLowerCase()}`}><div className="section-heading">{section.eyebrow ? <p className="eyebrow">{section.eyebrow}</p> : null}<h2>{title}</h2>{section.subheading ? <p className="section-lede">{section.subheading}</p> : null}</div>{section.sectionType === 'RICH_TEXT' ? <Paragraphs value={body.paragraphs} /> : null}{section.sectionType === 'FACT_GRID' ? <ItemGrid items={body.items} fact /> : null}{section.sectionType === 'CARD_GRID' ? <ItemGrid items={body.items} /> : null}{section.sectionType === 'STEPS' ? <Steps items={body.items} /> : null}{section.sectionType === 'CTA' ? <p className="section-lede">{text(body.supportingText)}</p> : null}{section.sectionType === 'MEDIA' ? <MediaSection section={section} caption={text(body.caption)} /> : null}{section.sectionType !== 'MEDIA' && section.primaryMedia ? <img className="section-media" src={section.primaryMedia.url} alt={section.primaryMedia.alt || title} /> : null}{section.ctaLabel ? <Link className="text-link" href={href(section.ctaUrl)}>{section.ctaLabel} →</Link> : null}</article>;
}
function text(value: unknown): string { return typeof value === 'string' ? value : ''; }
function Paragraphs({ value }: { value: unknown }) { const paragraphs = Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; return paragraphs.length ? <div className="editorial-copy">{paragraphs.map((paragraph, index) => <p key={`${paragraph.slice(0, 20)}-${index}`}>{paragraph}</p>)}</div> : null; }
function ItemGrid({ items, fact = false }: { items: unknown; fact?: boolean }) { const records = Array.isArray(items) ? items.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : []; return records.length ? <div className={`editorial-items ${fact ? 'fact-grid' : 'card-grid'}`}>{records.map((item, index) => <div key={`${text(item.title || item.label)}-${index}`}><strong>{text(item.title || item.label)}</strong><span>{text(item.description || item.value)}</span></div>)}</div> : null; }
function Steps({ items }: { items: unknown }) { const records = Array.isArray(items) ? items.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : []; return records.length ? <ol className="editorial-steps">{records.map((item, index) => <li key={`${text(item.title)}-${index}`}><span>{text(item.step) || String(index + 1).padStart(2, '0')}</span><div><strong>{text(item.title)}</strong><p>{text(item.description)}</p></div></li>)}</ol> : null; }
function MediaSection({ section, caption }: { section: Section; caption: string }) { return section.primaryMedia ? <figure><img className="section-media" src={section.primaryMedia.url} alt={section.primaryMedia.alt || section.heading || ''} />{caption ? <figcaption>{caption}</figcaption> : null}</figure> : null; }
