import { formatDate } from '@/lib/format';
import type { ProfileSummary } from '@/lib/countries';
import { isPublishedValue } from '@/lib/country-experience';

export type StructuredNavItem = { id: string; label: string };
const present = isPublishedValue;
const money = (profile: ProfileSummary['cost'], min: string | null | undefined, max?: string | null) => { if (!profile || !present(min)) return null; return `${profile.currencySymbol ?? profile.currencyCode} ${min}${present(max) ? `–${max}` : '+'}`; };
const range = (min: string | null | undefined, max?: string | null) => present(min) ? `${min}${present(max) ? `–${max}` : '+'}` : null;
const label = (value: unknown) => typeof value === 'string' && value.trim() ? value : null;
function nav(id: string, labelText: string): StructuredNavItem { return { id, label: labelText }; }

export function structuredNavItems(profiles: ProfileSummary): StructuredNavItem[] {
  const items: StructuredNavItem[] = [];
  if (profiles.cost) items.push(nav('structured-cost', 'Cost')); if (profiles.intakes.length) items.push(nav('structured-intakes', 'Intakes')); if (profiles.language) items.push(nav('structured-language', 'Language')); if (profiles.work) items.push(nav('structured-work-visa', 'Work & visa')); if (profiles.statistics) items.push(nav('structured-statistics', 'Statistics')); if (profiles.cost?.sourceReference || profiles.work?.sourceReference || profiles.language?.sourceReference || profiles.statistics?.sourceReference) items.push(nav('structured-trust', 'Sources')); return items;
}

export function CountryStructuredSections({ profiles }: { profiles: ProfileSummary }) {
  const items = structuredNavItems(profiles);
  return <>{items.some((item) => item.id === 'structured-cost') ? <section id="structured-cost" className="structured-section editorial-section"><SectionHeading eyebrow="Verified profile" title="Cost of study" /><div className="structured-grid">{profileCostRows(profiles.cost).map(([name, value]) => <Fact key={name} label={name} value={value} />)}</div></section> : null}{items.some((item) => item.id === 'structured-intakes') ? <section id="structured-intakes" className="structured-section editorial-section"><SectionHeading eyebrow="Verified profile" title="Major intakes" /><div className="structured-grid">{profiles.intakes.map((intake) => <Fact key={intake.id} label={intake.name} value={[intake.shortLabel, intake.availabilityStatus.toLowerCase(), intake.applicationOpeningNote, intake.applicationDeadlineNote].filter(Boolean).join(' · ')} />)}</div></section> : null}{items.some((item) => item.id === 'structured-language') ? <section id="structured-language" className="structured-section editorial-section"><SectionHeading eyebrow="Verified profile" title="Language requirements" /><div className="structured-grid">{profileLanguageRows(profiles.language).map(([name, value]) => <Fact key={name} label={name} value={value} />)}</div></section> : null}{items.some((item) => item.id === 'structured-work-visa') ? <section id="structured-work-visa" className="structured-section editorial-section"><SectionHeading eyebrow="Verified profile" title="Work and visa pathways" /><div className="structured-grid">{profileWorkRows(profiles.work).map(([name, value]) => <Fact key={name} label={name} value={value} />)}</div></section> : null}{items.some((item) => item.id === 'structured-statistics') ? <section id="structured-statistics" className="structured-section editorial-section"><SectionHeading eyebrow="Verified profile" title="Destination statistics" /><div className="structured-grid">{profileStatisticsRows(profiles.statistics).map(([name, value]) => <Fact key={name} label={name} value={value} />)}</div></section> : null}{items.some((item) => item.id === 'structured-trust') ? <section id="structured-trust" className="structured-section editorial-section"><SectionHeading eyebrow="Source trust" title="What these figures mean" /><p className="section-lede">Structured profile fields are shown only when the source and verification timestamp are present.</p><div className="trust-notes">{[profiles.cost, profiles.work, profiles.language, profiles.statistics].filter((profile) => profile?.sourceReference).map((profile, index) => <p key={`${profile?.sourceReference}-${index}`}><strong>Source:</strong> {profile?.sourceReference}{profile?.verifiedAt ? ` · verified ${formatDate(profile.verifiedAt)}` : ''}</p>)}</div></section> : null}</>;
}

function profileCostRows(profile: ProfileSummary['cost']) { if (!profile) return []; return [['Tuition', money(profile, profile.tuitionMin, profile.tuitionMax)], ['Living costs', money(profile, profile.livingCostMin, profile.livingCostMax)], ['Accommodation', money(profile, profile.accommodationMin, profile.accommodationMax)], ['Food', money(profile, profile.foodCostMin, profile.foodCostMax)], ['Transport', money(profile, profile.transportCostMin, profile.transportCostMax)], ['Health insurance', money(profile, profile.healthInsuranceCost)], ['Application fee', money(profile, profile.applicationFeeMin, profile.applicationFeeMax)], ['Notes', label(profile.livingCostNotes) ?? label(profile.disclaimer)]].filter((row): row is [string, string] => Boolean(row[1])); }
function profileLanguageRows(profile: ProfileSummary['language']) { if (!profile) return []; return [['IELTS', [profile.ieltsRequirement, range(profile.ieltsMinScore), profile.ieltsNotes].filter(Boolean).join(' · ')], ['PTE', [profile.pteRequirement, range(profile.pteMinScore), profile.pteNotes].filter(Boolean).join(' · ')], ['TOEFL', [profile.toeflRequirement, range(profile.toeflMinScore), profile.toeflNotes].filter(Boolean).join(' · ')], ['Duolingo', [profile.duolingoRequirement, range(profile.duolingoMinScore), profile.duolingoNotes].filter(Boolean).join(' · ')], ['Waiver', profile.languageWaiverAvailable ? `Available${profile.waiverNotes ? ` · ${profile.waiverNotes}` : ''}` : null], ['Notes', label(profile.generalNotes)]].filter((row): row is [string, string] => Boolean(row[1])); }
function profileWorkRows(profile: ProfileSummary['work']) { if (!profile) return []; return [['Part-time work', profile.partTimeAllowed === true ? `Allowed${profile.partTimeHoursPerWeek ? ` · ${profile.partTimeHoursPerWeek} hours/week` : ''}` : profile.partTimeAllowed === false ? 'Not published as allowed' : null], ['Post-study work', profile.postStudyWorkAvailable ? [profile.postStudyWorkSummary, range(profile.postStudyWorkMinMonths?.toString(), profile.postStudyWorkMaxMonths?.toString()) ? `${range(profile.postStudyWorkMinMonths?.toString(), profile.postStudyWorkMaxMonths?.toString())} months` : null].filter(Boolean).join(' · ') : 'Not available'], ['Immigration pathway', [profile.immigrationPathwayStrength, profile.immigrationPathwaySummary].filter(Boolean).join(' · ')], ['Visa success', [profile.visaSuccessBand, profile.visaSuccessPercentage ? `${profile.visaSuccessPercentage}%` : null].filter(Boolean).join(' · ')], ['Visa information', [profile.visaInformation, profile.visaProcessingTime, profile.proofOfFundsSummary].filter(Boolean).join(' · ')].filter(Boolean).join(' · ')].filter((row): row is [string, string] => Boolean(row[1])); }
function profileStatisticsRows(profile: ProfileSummary['statistics']) { if (!profile) return []; return [['Universities', profile.universitiesCount], ['Courses', profile.coursesCount], ['Top-ranked universities', profile.topRankedUniversitiesCount], ['Cities', profile.citiesCount], ['Scholarships', profile.scholarshipsCount], ['International students', profile.internationalStudentsCount], ['Student satisfaction', present(profile.studentSatisfactionPercentage) ? `${profile.studentSatisfactionPercentage}%` : null]].filter((row): row is [string, string | number] => present(row[1])); }
function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>; }
function Fact({ label: factLabel, value }: { label: string; value: string | number }) { return <div className="structured-fact"><span>{factLabel}</span><strong>{value}</strong></div>; }
