'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Country } from '@/lib/countries';

type Continent = { id: string; name: string; slug: string; status: string };
export function CountriesExplorer({ countries, continents }: { countries: Country[]; continents: Continent[] }) {
  const [query, setQuery] = useState('');
  const [submitted, setSubmitted] = useState('');
  const [region, setRegion] = useState('all');
  const [suggestions, setSuggestions] = useState<Country[]>([]);
  const [open, setOpen] = useState(false);
  const searchRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!query.trim()) return; const controller = new AbortController(); const timer = window.setTimeout(() => { void fetch(`/api/countries/suggestions?q=${encodeURIComponent(query.trim())}`, { signal: controller.signal }).then((response) => response.json() as Promise<{ data?: Country[] }>).then((body) => { setSuggestions(body.data ?? []); setOpen(true); }).catch(() => undefined); }, 180); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query]);
  useEffect(() => { const onClick = (event: MouseEvent) => { if (!searchRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('mousedown', onClick); return () => document.removeEventListener('mousedown', onClick); }, []);
  const visible = useMemo(() => countries.filter((country) => (!submitted || `${country.name} ${country.slug}`.toLowerCase().includes(submitted.toLowerCase())) && (region === 'all' || country.continent.slug === region)), [countries, region, submitted]);
  function submit(event: React.FormEvent) { event.preventDefault(); setSubmitted(query.trim()); setOpen(false); document.getElementById('country-results')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  return <>
    <section className="country-search-band" aria-labelledby="country-search-heading"><div className="shell"><p className="eyebrow">Find your destination</p><h2 id="country-search-heading">Explore study destinations</h2><div className="search-row" ref={searchRef}><form onSubmit={submit} className="search-form"><label htmlFor="country-search">Search by country</label><div className="search-control"><input id="country-search" role="combobox" aria-expanded={open} aria-controls="country-suggestions" aria-autocomplete="list" value={query} onChange={(event) => { setQuery(event.target.value); if (!event.target.value.trim()) { setOpen(false); setSuggestions([]); } }} onKeyDown={(event) => { if (event.key === 'Escape') setOpen(false); }} placeholder="Try Canada, France, or Australia" /><button type="submit">Search</button></div>{open && suggestions.length ? <ul id="country-suggestions" role="listbox" className="suggestions">{suggestions.map((item) => <li key={item.id} role="option" aria-selected="false"><button type="button" onClick={() => { setQuery(item.name); setSubmitted(item.name); setOpen(false); }}>{item.name}<span>{item.continent.name}</span></button></li>)}</ul> : null}</form><div className="quick-filters" aria-label="Quick filters"><button type="button" className={region === 'all' ? 'chip active' : 'chip'} onClick={() => setRegion('all')}>All destinations</button>{continents.map((continent) => <button type="button" className={region === continent.slug ? 'chip active' : 'chip'} key={continent.id} onClick={() => setRegion(continent.slug)}>{continent.name}</button>)}</div></div></div></section>
    <section id="country-results" className="shell results-section" aria-labelledby="country-results-heading"><div className="results-heading"><div><p className="eyebrow">Browse by region</p><h2 id="country-results-heading">{region === 'all' ? 'All destinations' : continents.find((item) => item.slug === region)?.name}</h2></div><p role="status" aria-live="polite">{visible.length} {visible.length === 1 ? 'destination' : 'destinations'}</p></div>{visible.length ? <div className="country-grid">{visible.map((country) => <CountryCard key={country.id} country={country} />)}</div> : <div className="empty-state"><h3>No destinations found</h3><p>Try another country or clear the active filters.</p><button type="button" className="button secondary" onClick={() => { setSubmitted(''); setQuery(''); setRegion('all'); }}>Clear all</button></div>}</section>
  </>;
}
function CountryCard({ country }: { country: Country }) { const profile = country.profiles; return <article className="country-card"><div className="card-top"><span className="country-flag">{country.flag ? <img src={country.flag.url} alt={country.flag.alt || `${country.name} flag`} /> : <span aria-hidden="true">◎</span>}</span><span className="country-region">{country.continent.name}</span></div><h3>{country.name}</h3><p>{country.shortDescription}</p><div className="card-facts">{profile?.cost?.tuitionMin ? <span>{profile.cost.currencySymbol ?? profile.cost.currencyCode} {profile.cost.tuitionMin}+ tuition</span> : null}{profile?.intakes?.length ? <span>{profile.intakes.map((item) => item.shortLabel ?? item.name).join(' · ')}</span> : null}</div><Link className="card-link" href={`/countries/${country.slug}`}>View country <span aria-hidden="true">→</span></Link></article>; }
