import Link from 'next/link';
import type { CountryPage, Section } from '@/lib/countries';

export function CountryPageView({ page }: { page: CountryPage }) {
  const { country, profiles, sections, faqs, consultantCards } = page;
  return <main>
    <header className="site-header"><div className="shell header-inner"><Link href="/countries" className="brand">universta<span>.</span></Link><nav aria-label="Primary navigation"><Link href="/countries">Countries</Link><a href="#consultation">Get counselling</a></nav></div></header>
    <section className="detail-hero"><div className="shell detail-hero-grid"><div><Link className="back-link" href="/countries">← All destinations</Link><p className="eyebrow">Study destination · {country.continent.name}</p><h1>{country.pageHeading || `Study in ${country.name}`}</h1><p className="hero-copy">{country.shortDescription}</p><a className="button" href="#consultation">Talk to a counsellor</a></div><div className="hero-card">{country.flag ? <img src={country.flag.url} alt={country.flag.alt || `${country.name} flag`} /> : null}<span>{country.name}</span><small>{country.continent.name}</small></div></div></section>
    <div className="detail-tabs"><div className="shell"><a href="#overview">Overview</a><a href="#facts">At a glance</a><a href="#faqs">FAQs</a><a href="#consultation">Consultation</a></div></div>
    <section id="overview" className="shell detail-content"><div className="detail-main"><p className="eyebrow">Your destination guide</p><h2>Why study in {country.name}?</h2><p>{country.shortDescription}</p>{sections.map((section) => <EditorialSection key={section.id} section={section} />)}</div><aside id="facts" className="facts-panel"><p className="eyebrow">At a glance</p><h2>{country.name}</h2><Fact label="Universities" value={profiles.statistics?.universitiesCount} /><Fact label="Courses" value={profiles.statistics?.coursesCount} /><Fact label="Tuition" value={profiles.cost?.tuitionMin ? `${profiles.cost.currencySymbol ?? profiles.cost.currencyCode} ${profiles.cost.tuitionMin}${profiles.cost.tuitionMax ? `–${profiles.cost.tuitionMax}` : '+'}` : null} /><Fact label="Major intakes" value={profiles.intakes.length ? profiles.intakes.map((item) => item.shortLabel ?? item.name).join(', ') : null} /></aside></section>
    {faqs.length ? <section id="faqs" className="soft-band"><div className="shell"><p className="eyebrow">Questions answered</p><h2>Frequently asked questions</h2><div className="faq-list">{faqs.map((faq) => <details key={faq.id}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></div></section> : null}
    <section id="consultation" className="consultation-band"><div className="shell consultation-inner"><div><p className="eyebrow">Plan with confidence</p><h2>Get a personalised study plan</h2><p>Speak with a Universta counsellor about your next step.</p></div><a className="button light" href="mailto:hello@universta.com?subject=Country%20consultation">Request counselling</a></div></section>
    {consultantCards.length ? <section className="shell consultants"><p className="eyebrow">Guidance for your journey</p><h2>Explore consultation options</h2><div className="consultant-grid">{consultantCards.map((card) => <article key={card.id} className="consultant-card"><h3>{card.title}</h3><p>{card.shortDescription}</p>{card.ctaUrl ? <a href={card.ctaUrl}>{card.ctaLabel} →</a> : <a href="#consultation">{card.ctaLabel} →</a>}</article>)}</div></section> : null}
    <footer className="site-footer"><div className="shell"><span className="brand">universta<span>.</span></span><p>Information is editorial and source-aware. Admission, visa, cost, and work outcomes vary by institution and applicant.</p></div></footer>
  </main>;
}

function Fact({ label, value }: { label: string; value: string | number | null | undefined }) { return <div className="fact"><span>{label}</span><strong>{value ?? 'Not published'}</strong></div>; }
function EditorialSection({ section }: { section: Section }) { const body = section.bodyJson; const paragraphs = Array.isArray(body?.paragraphs) ? body.paragraphs.filter((item): item is string => typeof item === 'string') : []; const items = Array.isArray(body?.items) ? body.items.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object')) : []; return <article className="editorial-section">{section.eyebrow ? <p className="eyebrow">{section.eyebrow}</p> : null}{section.heading ? <h3>{section.heading}</h3> : null}{section.subheading ? <p className="section-lede">{section.subheading}</p> : null}{section.primaryMedia ? <img className="section-media" src={section.primaryMedia.url} alt={section.primaryMedia.alt || section.heading || ''} /> : null}{paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{items.length ? <div className="editorial-items">{items.map((item, index) => <div key={`${String(item.title ?? item.label)}-${index}`}><strong>{String(item.title ?? item.label ?? '')}</strong><span>{String(item.description ?? item.value ?? '')}</span></div>)}</div> : null}{section.ctaUrl && section.ctaLabel ? <a className="text-link" href={section.ctaUrl}>{section.ctaLabel} →</a> : null}</article>; }
