import Link from 'next/link';
import type { Section } from '@/lib/countries';
/* API-selected media can come from approved external asset hosts. */
/* eslint-disable @next/next/no-img-element */

const titles: Record<string, string> = { 'why-study': 'Why study here?', universities: 'Universities', subjects: 'Subjects and programmes', documents: 'Documents', scholarships: 'Scholarships', 'visa-process': 'Visa process', events: 'Events', cities: 'Cities', 'life-and-culture': 'Life and culture', careers: 'Careers', 'application-steps': 'Application steps', guides: 'Guides', 'trust-disclaimer': 'Source and trust note', 'consultant-cta': 'Plan with guidance', intakes: 'Intakes', 'cost-of-study': 'Cost of study', 'work-opportunities': 'Work opportunities', 'language-requirements': 'Language requirements' };
const safeHref = (value: string | null | undefined) => value && (/^\//.test(value) || /^#[a-zA-Z0-9_-]+$/.test(value) || /^https:\/\//.test(value)) ? value : '#consultation';
export function CountryEditorialSections({ sections }: { sections: Section[] }) { return <>{[...sections].sort((a, b) => a.displayOrder - b.displayOrder).map((section) => <EditorialSection key={section.id} section={section} />)}</>; }
export function editorialNavItems(sections: Section[]) { return [...sections].sort((a, b) => a.displayOrder - b.displayOrder).map((section) => ({ id: `country-section-${section.sectionKey}`, label: section.heading ?? titles[section.sectionKey] ?? section.sectionKey })); }
function EditorialSection({ section }: { section: Section }) { const title = section.heading ?? titles[section.sectionKey] ?? 'Country guidance'; const content = keyRenderer(section.sectionKey, section); return <article id={`country-section-${section.sectionKey}`} className={`editorial-section section-${section.sectionKey}`}><div className="section-heading">{section.eyebrow ? <p className="eyebrow">{section.eyebrow}</p> : null}<h2>{title}</h2>{section.subheading ? <p className="section-lede">{section.subheading}</p> : null}</div>{content}{section.primaryMedia ? <img className="section-media" src={section.primaryMedia.url} alt={section.primaryMedia.alt || title} /> : null}{section.ctaLabel ? <Link className="text-link" href={safeHref(section.ctaUrl)}>{section.ctaLabel} →</Link> : null}</article>; }
function keyRenderer(key: string, section: Section) { const body = section.bodyJson ?? {}; if (key === 'application-steps' || key === 'visa-process') return <Steps items={body.items} />; if (key === 'documents') return <Checklist items={body.items} />; if (key === 'universities' || key === 'subjects' || key === 'scholarships' || key === 'events' || key === 'cities' || key === 'careers') return <Cards items={body.items} />; if (key === 'trust-disclaimer') return <Trust body={body} />; if (key === 'why-study' || key === 'life-and-culture' || key === 'guides' || key === 'work-opportunities' || key === 'language-requirements' || key === 'intakes' || key === 'cost-of-study' || key === 'consultant-cta') return <Copy body={body} />; return section.sectionType === 'STEPS' ? <Steps items={body.items} /> : section.sectionType === 'FACT_GRID' ? <Cards items={body.items} /> : section.sectionType === 'CARD_GRID' ? <Cards items={body.items} /> : section.sectionType === 'CTA' ? <Copy body={body} /> : section.sectionType === 'MEDIA' ? <p className="section-lede">{string(body.caption)}</p> : <Copy body={body} />; }
function string(value: unknown) { return typeof value === 'string' ? value : ''; }
function records(value: unknown) { return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : []; }
function Copy({ body }: { body: Record<string, unknown> }) { const paragraphs = Array.isArray(body.paragraphs) ? body.paragraphs.filter((item): item is string => typeof item === 'string') : [string(body.supportingText)]; return paragraphs.filter(Boolean).length ? <div className="editorial-copy">{paragraphs.filter(Boolean).map((paragraph, index) => <p key={`${paragraph.slice(0, 20)}-${index}`}>{paragraph}</p>)}</div> : null; }
function Cards({ items }: { items: unknown }) { const values = records(items); return values.length ? <div className="editorial-items card-grid">{values.map((item, index) => <div key={`${string(item.title || item.label)}-${index}`}><strong>{string(item.title || item.label)}</strong><span>{string(item.description || item.value)}</span></div>)}</div> : null; }
function Checklist({ items }: { items: unknown }) { const values = records(items); return values.length ? <ul className="editorial-checklist">{values.map((item, index) => <li key={`${string(item.title || item.label)}-${index}`}><strong>{string(item.title || item.label)}</strong><span>{string(item.description || item.value)}</span></li>)}</ul> : null; }
function Steps({ items }: { items: unknown }) { const values = records(items); return values.length ? <ol className="editorial-steps">{values.map((item, index) => <li key={`${string(item.title)}-${index}`}><span>{string(item.step) || String(index + 1).padStart(2, '0')}</span><div><strong>{string(item.title)}</strong><p>{string(item.description)}</p></div></li>)}</ol> : null; }
function Trust({ body }: { body: Record<string, unknown> }) { return <div className="trust-notes"><p>{string(body.paragraph) || string(body.supportingText) || 'This editorial note is published separately from structured country profile verification.'}</p></div>; }
