import type { Metadata } from 'next';
import Link from 'next/link';
import { getSubjects } from '@/lib/catalog';
import { SubjectsExplorer } from '@/components/catalog/SubjectsExplorer';
export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Subjects | Universta', description: 'Explore published study subjects and course pathways.' };
type SearchParams = Record<string, string | string[] | undefined>;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
export default async function SubjectsPage({ searchParams }: { searchParams: Promise<SearchParams> }) { const params = await searchParams; let data: Awaited<ReturnType<typeof getSubjects>> | null = null; try { data = await getSubjects({ q: one(params.q) ?? '', page: one(params.page) ?? '1', limit: '12' }); } catch { return <main className="error-page shell"><p className="eyebrow">Subjects</p><h1>Subjects are temporarily unavailable</h1><p>Please try again shortly.</p><Link className="button" href="/subjects">Retry</Link></main>; } return <main><header className="site-header"><div className="shell header-inner"><Link className="brand" href="/subjects">universta<span>.</span></Link><nav aria-label="Primary navigation"><Link href="/subjects">Subjects</Link><Link href="/courses">Courses</Link><Link href="/countries">Countries</Link></nav></div></header><section className="listing-hero"><div className="shell"><p className="eyebrow">Choose your direction</p><h1>Find the subject that moves you forward.</h1><p>Explore published subjects, specialisations, and course pathways through structured, source-aware information.</p></div></section><SubjectsExplorer subjects={data.data} meta={data.meta} /><section className="consultation-band"><div className="shell consultation-inner"><div><p className="eyebrow">Need a starting point?</p><h2>Turn a subject into a plan.</h2><p>Use published course information as a starting point and verify important decisions with official sources.</p></div><Link className="button light" href="/courses">Explore courses</Link></div></section><footer className="site-footer"><div className="shell footer-grid"><div><Link className="brand" href="/subjects">universta<span>.</span></Link><p>Structured, source-aware study guidance.</p></div><p className="footer-note">Information may vary by institution, programme, applicant, and policy.</p></div></footer></main>; }
