'use client';
import { useCallback, useEffect, useState } from 'react';
import { authFetch } from '@/features/auth/auth-client';

const titles: Record<string, string> = { universities: 'Universities', scholarships: 'Scholarships', consultants: 'Consultants', jobs: 'Jobs', events: 'Events', 'success-stories': 'Success stories', testimonials: 'Testimonials', pages: 'Editorial pages', 'navigation-menus': 'Navigation menus', 'contact-inquiries': 'Contact enquiries' };
const examples: Record<string, string> = { universities: '{\n  "name": "Demo University",\n  "slug": "demo-university",\n  "countryId": "<country-id>",\n  "shortDescription": "Clearly fictional local demo record"\n}', scholarships: '{\n  "title": "Demo scholarship",\n  "slug": "demo-scholarship",\n  "summary": "Clearly fictional local demo record"\n}', consultants: '{\n  "name": "Demo consultant",\n  "slug": "demo-consultant"\n}', jobs: '{\n  "title": "Demo role",\n  "slug": "demo-role"\n}', events: '{\n  "title": "Demo event",\n  "slug": "demo-event",\n  "startsAt": "2026-12-01T10:00:00.000Z"\n}', 'success-stories': '{\n  "title": "Demo story",\n  "slug": "demo-story",\n  "journey": "Clearly fictional local demo content"\n}', testimonials: '{\n  "quote": "Clearly fictional local demo content"\n}', pages: '{\n  "pageType": "EDITORIAL",\n  "title": "About",\n  "slug": "about"\n}', 'navigation-menus': '{\n  "name": "Primary",\n  "menuKey": "primary",\n  "location": "HEADER"\n}' };

type Envelope = { data: any; meta: any; error: { message: string } | null };
async function request(path: string, init?: RequestInit) { const response = await authFetch(`/api/v1/admin/phase1/${path}`, { ...init, headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) } }); const body = await response.json() as Envelope; if (!response.ok || body.error) throw new Error(body.error?.message ?? 'Admin request failed'); return body; }

export function Phase1Manager({ resource }: { resource: string }) {
  const [rows, setRows] = useState<any[]>([]); const [message, setMessage] = useState(''); const [draft, setDraft] = useState(examples[resource] ?? '{}'); const title = titles[resource] ?? resource;
  const load = useCallback(async () => { try { const body = await request(resource); setRows(body.data ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load records'); } }, [resource]);
  useEffect(() => { void load(); }, [load]);
  async function create() { try { const body = JSON.parse(draft); await request(resource, { method: 'POST', body: JSON.stringify(body) }); setMessage('Draft created. Publish it when ready.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Invalid JSON'); } }
  async function action(path: string, method = 'POST') { try { await request(path, { method }); setMessage('Saved.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save'); } }
  return <section className="mx-auto max-w-[1240px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#828B9B]">Expanded Phase 1</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">{title}</h2></div><p className="text-sm text-[#667085]">{rows.length} records</p></div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="overflow-x-auto rounded-2xl border border-[#E8ECF3] bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#E8ECF3] text-[#667085]"><tr><th className="p-4">Record</th><th className="p-4">Slug / status</th><th className="p-4">Actions</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b border-[#F0F2F5]" key={row.id}><td className="p-4 font-semibold">{row.name ?? row.title ?? row.fullName ?? row.inquiryNumber ?? row.quote?.slice(0, 48)}</td><td className="p-4 text-[#667085]">{row.slug ?? row.status}</td><td className="flex flex-wrap gap-2 p-4">{resource !== 'contact-inquiries' ? <><button type="button" className="rounded-lg bg-[#1657CF] px-3 py-2 text-xs font-semibold text-white" onClick={() => void action(`${resource}/${row.id}/publish`)}>Publish</button><button type="button" className="rounded-lg border border-[#E8ECF3] px-3 py-2 text-xs font-semibold" onClick={() => void action(`${resource}/${row.id}/unpublish`)}>Unpublish</button></> : <button type="button" className="rounded-lg bg-[#1657CF] px-3 py-2 text-xs font-semibold text-white" disabled={Boolean(row.convertedLeadId)} onClick={() => void action(`${resource}/${row.id}/convert`)}>Convert to lead</button>}<button type="button" className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700" onClick={() => void action(`${resource}/${row.id}`, 'DELETE')}>Archive</button></td></tr>)}</tbody></table>{rows.length ? null : <p className="p-6 text-sm text-[#667085]">No records yet.</p>}</div>{resource === 'contact-inquiries' ? <aside className="rounded-2xl border border-[#E8ECF3] bg-white p-5 text-sm text-[#667085]">Contact enquiries are separate from counselling leads. Conversion is idempotent, requires a phone number, and is recorded in the API audit log.</aside> : <aside className="rounded-2xl border border-[#E8ECF3] bg-white p-5"><h3 className="font-semibold">Create draft</h3><p className="mt-2 text-sm text-[#667085]">Use the supported schema fields. Complex relationships can be managed through the API while richer form editors are added.</p><textarea className="mt-4 h-72 w-full rounded-xl border border-[#DCE2EA] p-3 font-mono text-xs" value={draft} onChange={(event) => setDraft(event.target.value)} /><button className="mt-3 rounded-xl bg-[#1657CF] px-4 py-2 text-sm font-semibold text-white" type="button" onClick={() => void create()}>Create draft</button></aside>}</div>{message ? <p className="mt-5 text-sm text-[#48505F]" role="status">{message}</p> : null}</section>;
}
