import type { Metadata } from 'next';
import Link from 'next/link';
import { getCountries } from '@/lib/countries';
import { getCourseLevels, getCourses, getStudyModes, getSubjects } from '@/lib/catalog';
import { CoursesExplorer } from '@/components/catalog/CoursesExplorer';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Courses | Universta', description: 'Search published courses by subject, level, study mode, and country.' };
type SearchParams = Record<string, string | string[] | undefined>;
const keys = ['q', 'subject', 'subSubject', 'level', 'country', 'studyMode', 'intake', 'scholarshipAvailable', 'featured', 'minTuition', 'maxTuition', 'sort', 'page'] as const;
function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function unavailable() { return <main className="error-page shell"><p className="eyebrow">Courses</p><h1>Courses are temporarily unavailable</h1><p>Please try again shortly.</p><Link className="button" href="/courses">Retry</Link></main>; }
type Data = Awaited<ReturnType<typeof getCourses>> & { subjects: Awaited<ReturnType<typeof getSubjects>>['data']; levels: Awaited<ReturnType<typeof getCourseLevels>>; modes: Awaited<ReturnType<typeof getStudyModes>>; countries: Array<{ id: string; name: string; slug: string }> };
function content(data: Data, filters: Record<string, string>) { return <main><header className="site-header"><div className="shell header-inner"><Link className="brand" href="/courses">universta<span>.</span></Link><nav aria-label="Primary navigation"><Link href="/subjects">Subjects</Link><Link href="/courses">Courses</Link><Link href="/countries">Countries</Link></nav></div></header><section className="listing-hero"><div className="shell"><p className="eyebrow">Course discovery</p><h1>Find a course that fits your next step.</h1><p>Search published course data by subject, level, study mode, country, intake, and verified availability.</p></div></section><CoursesExplorer courses={data.data} meta={data.meta} subjects={data.subjects} levels={data.levels} modes={data.modes} countries={data.countries} filters={filters} /><section className="consultation-band"><div className="shell consultation-inner"><div><p className="eyebrow">Need a starting point?</p><h2>Make your shortlist clearer.</h2><p>Course-country facts are indicative. Verify important decisions with official sources.</p></div><Link className="button light" href="/subjects">Browse subjects</Link></div></section><footer className="site-footer"><div className="shell footer-grid"><div><Link className="brand" href="/courses">universta<span>.</span></Link><p>Structured, source-aware study guidance.</p></div><p className="footer-note">No ranking, salary, university, or admissions guarantee claims are shown.</p></div></footer></main>; }
export default async function CoursesPage({ searchParams }: { searchParams: Promise<SearchParams> }) { const raw = await searchParams; const filters = Object.fromEntries(keys.flatMap((key) => { const value = one(raw[key]); return value ? [[key, value]] : []; })) as Record<string, string>; let data: Data; try { const [courses, subjects, levels, modes, countries] = await Promise.all([getCourses({ ...filters, limit: '12' }), getSubjects({ limit: '100' }).then((result) => result.data), getCourseLevels(), getStudyModes(), getCountries({ limit: '100' }).then((result) => result.data.map((item) => ({ id: item.id, name: item.name, slug: item.slug })))]); data = { ...courses, subjects, levels, modes, countries }; } catch { return unavailable(); } return content(data, filters); }
