'use client';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useState } from 'react';
import type { PageMeta, Subject } from '@/lib/catalog';

export function SubjectsExplorer({ subjects, meta }: { subjects: Subject[]; meta: PageMeta }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [query, setQuery] = useState(params.get('q') ?? '');
  function submit(event: React.FormEvent) { event.preventDefault(); const next = new URLSearchParams(params.toString()); if (query.trim()) next.set('q', query.trim()); else next.delete('q'); next.delete('page'); router.push(`${pathname}${next.toString() ? `?${next}` : ''}`); }
  function page(value: number) { const next = new URLSearchParams(params.toString()); next.set('page', String(value)); router.push(`${pathname}?${next}`); }
  return <section className="catalog-explorer shell" aria-labelledby="subjects-results-heading"><div className="catalog-toolbar"><form onSubmit={submit}><label htmlFor="subject-search">Search subjects</label><div className="catalog-search"><input id="subject-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by subject" /><button className="button" type="submit">Search</button></div></form><span className="result-count" role="status">{meta.total} {meta.total === 1 ? 'subject' : 'subjects'}</span></div>{subjects.length ? <div className="catalog-card-grid">{subjects.map((subject) => <article className="catalog-card" key={subject.id}>{subject.listingMedia ? <img src={subject.listingMedia.url} alt={subject.listingMedia.alt ?? subject.name} /> : <div className="catalog-card-placeholder" aria-hidden="true">{subject.name.slice(0, 1)}</div>}<div className="catalog-card-body"><div className="card-badges">{subject.featured ? <span>Featured</span> : null}<span>{subject.publishedCourseCount} courses</span></div><h2 id={`subject-${subject.id}`}>{subject.name}</h2><p>{subject.shortDescription ?? 'Explore published courses and study pathways.'}</p><div className="catalog-card-facts"><span>{subject.publishedSubSubjectCount} specialisations</span><span>{subject.availableCountryCount} countries</span></div><Link className="card-link" href={`/subjects/${subject.slug}`}>View subject <span aria-hidden="true">→</span></Link></div></article>)}</div> : <div className="empty-state"><h2 id="subjects-results-heading">No subjects found</h2><p>Try a different subject or clear the search.</p><Link className="button secondary" href="/subjects">Clear search</Link></div>}{meta.totalPages > 1 ? <nav className="pagination" aria-label="Subject pages"><button type="button" disabled={meta.page <= 1} onClick={() => page(meta.page - 1)}>Previous</button><span>Page {meta.page} of {meta.totalPages}</span><button type="button" disabled={meta.page >= meta.totalPages} onClick={() => page(meta.page + 1)}>Next</button></nav> : null}</section>;
}
