import type { FieldHelpContent } from './types';

/** Definitions for fields whose meaning is identical everywhere they appear.
 * Module-specific registries spread these in and override only what
 * genuinely differs (see registry.ts). Content here is cross-checked
 * against the shared Phase1StructuredEditor form components, the standard
 * SEO field set, and the DTOs/validation actually enforced — not assumed
 * from field names. */
export const commonFieldHelp = {
  name: {
    purpose: 'The record’s display name.',
    input: 'A clear, specific name.',
    dataType: 'Text',
    required: 'Required.',
    example: 'Business & Management',
    frontendEffect: 'Shown as the page heading and on listing cards.',
  },
  title: {
    purpose: 'The record’s display title.',
    input: 'A clear, specific title.',
    dataType: 'Text',
    required: 'Required.',
    example: 'International Excellence Scholarship',
    frontendEffect: 'Shown as the page heading and on listing cards.',
  },
  slug: {
    purpose: 'Controls the URL-friendly identifier of the record.',
    input: 'Lowercase words separated by hyphens. Leave blank to generate it automatically from the name/title.',
    dataType: 'Text',
    required: 'Optional when auto-generated; required where the form marks it required.',
    format: 'Lowercase letters, numbers and hyphens only (a-z, 0-9, -).',
    example: 'business-management',
    frontendEffect: 'Used to build the public URL for this record.',
    caution: 'Changing a slug on a record that is already published changes its public address and can break existing links and search rankings. Avoid renaming a live slug.',
  },
  shortDescription: {
    purpose: 'A one- or two-sentence summary used in listing cards and as a search-result fallback.',
    input: 'A concise, accurate summary.',
    dataType: 'Text',
    required: 'Usually optional.',
    format: 'Keep to roughly 160 characters or fewer — it can double as the meta description when no dedicated one is set.',
    frontendEffect: 'Shown on listing cards and used as a fallback meta description.',
  },
  description: {
    purpose: 'The main body content shown on this record’s own page.',
    input: 'Full, accurate descriptive text.',
    dataType: 'Long text',
    required: 'Optional.',
    frontendEffect: 'Rendered as the main content area of the detail page.',
  },
  overview: {
    purpose: 'The main body content shown on this record’s own page.',
    input: 'Full, accurate descriptive text.',
    dataType: 'Long text',
    required: 'Optional.',
    frontendEffect: 'Rendered as the main content area of the detail page.',
  },
  status: {
    purpose: 'Controls whether this record is visible to the public.',
    input: 'Choose Draft while preparing content, Published once it is ready to go live.',
    dataType: 'Choice',
    required: 'Required.',
    example: 'Published',
    frontendEffect: 'Draft records are never visible publicly. Published records go live immediately upon saving.',
  },
  displayOrder: {
    purpose: 'Controls where this record appears relative to others of the same type.',
    input: 'A whole number. Lower numbers usually appear first.',
    dataType: 'Number',
    required: 'Optional — leave at 0 if the order does not matter yet.',
    example: '0',
    frontendEffect: 'Affects sort order on listing pages that use manual ordering.',
  },
  featured: {
    purpose: 'Highlights this record in "Featured" sections on the public site.',
    input: 'Tick to feature this record.',
    dataType: 'Checkbox',
    required: 'Optional.',
    frontendEffect: 'Included in the relevant "Featured" listing section when checked.',
  },
  featuredFrom: {
    purpose: 'The date and time featuring begins, if you want it scheduled rather than immediate.',
    input: 'Pick a date and time, or leave blank to feature immediately once the Featured checkbox is on.',
    dataType: 'Date and time',
    required: 'Optional.',
    dependency: 'Only takes effect together with the Featured checkbox.',
    frontendEffect: 'Before this time, the record is not shown as featured even if Featured is checked.',
    caution: 'If both Featured from and Featured until are set, Featured until must be later than Featured from.',
  },
  featuredUntil: {
    purpose: 'The date and time featuring ends automatically.',
    input: 'Pick a date and time, or leave blank for no end date.',
    dataType: 'Date and time',
    required: 'Optional.',
    dependency: 'Only takes effect together with the Featured checkbox.',
    frontendEffect: 'After this time, the record stops being shown as featured automatically.',
    caution: 'Must be later than Featured from if both are set.',
  },
  publishStartsAt: {
    purpose: 'Schedules this record to go live automatically at a future date and time, instead of immediately.',
    input: 'Pick a future date and time, or leave blank to publish immediately when Status is set to Published.',
    dataType: 'Date and time',
    required: 'Optional.',
    frontendEffect: 'The record becomes publicly visible automatically at this moment.',
  },
  publishEndsAt: {
    purpose: 'Automatically takes this record down at a future date and time, without deleting it.',
    input: 'Pick a future date and time, or leave blank for no automatic end.',
    dataType: 'Date and time',
    required: 'Optional.',
    frontendEffect: 'The record stops being publicly visible at this moment, but is not deleted.',
    caution: 'Must be later than Publish starts at if both are set.',
  },
  sourceUrl: {
    purpose: 'The official page used to verify this information.',
    input: 'The exact page where you confirmed the details are accurate.',
    dataType: 'URL',
    required: 'Required before publishing a record whose information claims to be verified.',
    format: 'A valid https:// URL.',
    example: 'https://official-domain.example/course-page',
    frontendEffect: 'Supports verification/trust information where the public page shows it.',
    caution: 'Do not enter an unrelated source or a fabricated link — this field exists to keep published information trustworthy.',
  },
  verifiedDate: {
    purpose: 'The date the information was last confirmed against its official source.',
    input: 'The date you checked the Source URL and confirmed the details.',
    dataType: 'Date',
    required: 'Required together with Source URL before publishing as verified/available.',
    format: 'Cannot be a future date.',
    example: '2026-08-05',
    frontendEffect: 'Supports verification/trust information where the public page shows it.',
  },
  media: {
    purpose: 'The image shown for this record.',
    input: 'Choose an existing image from the Media Library, or upload a new one without leaving this form.',
    dataType: 'Image',
    required: 'Optional.',
    format: 'JPEG, PNG, WEBP or GIF, up to 5MB.',
    frontendEffect: 'Shown as the card thumbnail and/or page hero image, depending on where this field is used.',
  },
  seoTitle: {
    purpose: 'What shows as this page’s title in a browser tab and in search results.',
    input: 'A clear, keyword-aware title.',
    dataType: 'Text',
    required: 'Optional, but recommended for any page that matters for search visibility.',
    format: 'Roughly 50–60 characters is recommended — not enforced by the system.',
    frontendEffect: 'Browser tab title and search-result title.',
  },
  metaDescription: {
    purpose: 'The short summary search engines typically display under this page’s title.',
    input: 'A compelling, accurate one- or two-sentence summary.',
    dataType: 'Text',
    required: 'Optional, but recommended.',
    format: 'Roughly 150–160 characters is recommended — not enforced by the system.',
    frontendEffect: 'Search-result snippet text.',
  },
  canonicalUrl: {
    purpose: 'Tells search engines which web address is the "real" one for this content.',
    input: 'Leave blank unless the same content is genuinely reachable at more than one address.',
    dataType: 'URL',
    required: 'Optional.',
    format: 'A valid URL.',
    frontendEffect: 'Sets the canonical link tag on the page.',
  },
  focusKeyword: {
    purpose: 'An internal note on the main search term this page targets.',
    input: 'The phrase you are optimising this page for.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified — it is not shown to visitors or sent to search engines.',
  },
  robotsIndex: {
    purpose: 'Controls whether search engines are allowed to list this page in results.',
    input: 'Leave checked for normal published content.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'When unchecked, asks search engines not to index this page. Unpublished drafts are never indexable regardless of this setting.',
  },
  robotsFollow: {
    purpose: 'Controls whether search engines are allowed to follow links found on this page.',
    input: 'Leave checked for normal published content.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'When unchecked, asks search engines not to follow this page’s links.',
  },
  ogTitle: {
    purpose: 'The title shown when this page is shared on Facebook, LinkedIn and similar platforms.',
    input: 'A short, share-friendly title — often the same as the SEO title.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Social share card title.',
  },
  ogDescription: {
    purpose: 'The description shown when this page is shared on social platforms.',
    input: 'A short, share-friendly summary.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Social share card description.',
  },
  ogMedia: {
    purpose: 'The image shown when this page is shared on social platforms.',
    input: 'Choose an on-brand, wide image.',
    dataType: 'Image',
    required: 'Optional.',
    frontendEffect: 'Social share card image.',
  },
  twitterTitle: {
    purpose: 'The title shown when this page is shared on X/Twitter.',
    input: 'A short, share-friendly title.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'X/Twitter share card title.',
  },
  twitterDescription: {
    purpose: 'The description shown when this page is shared on X/Twitter.',
    input: 'A short, share-friendly summary.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'X/Twitter share card description.',
  },
  country: {
    purpose: 'Links this record to a specific country.',
    input: 'Search for and select an existing, published Country.',
    dataType: 'Relationship',
    required: 'Depends on the form — check whether the field is marked required.',
    dependency: 'The Country record must already exist.',
    frontendEffect: 'Used for country-based grouping, filtering and cross-links on the public site.',
  },
  state: {
    purpose: 'Links this record to a specific state or province.',
    input: 'Select an existing State/Province belonging to the chosen Country.',
    dataType: 'Relationship',
    required: 'Usually optional.',
    dependency: 'A Country should be selected first — the list is filtered to that country’s states.',
    frontendEffect: 'Used for location grouping and filtering where shown.',
  },
  city: {
    purpose: 'Links this record to a specific city.',
    input: 'Select an existing City belonging to the chosen Country.',
    dataType: 'Relationship',
    required: 'Usually optional.',
    dependency: 'A Country should be selected first — the list is filtered to that country’s cities.',
    frontendEffect: 'Used for location grouping and filtering where shown.',
  },
  university: {
    purpose: 'Links this record to a specific university.',
    input: 'Search for and select an existing, published University.',
    dataType: 'Relationship',
    required: 'Depends on the form — check whether the field is marked required.',
    dependency: 'The University record must already exist.',
    frontendEffect: 'Used for cross-links and grouping on the public site.',
  },
  subject: {
    purpose: 'Classifies this record under a top-level field of study.',
    input: 'Search for an existing Subject, or create a new one without leaving this form.',
    dataType: 'Relationship',
    required: 'Required where the form marks it required.',
    dependency: 'The Subject record must already exist, or be created inline.',
    frontendEffect: 'Groups this record under the chosen Subject on the public Subjects directory.',
  },
  course: {
    purpose: 'Links this record to a specific generic course.',
    input: 'Search for and select an existing Generic Course.',
    dataType: 'Relationship',
    required: 'Depends on the form — check whether the field is marked required.',
    dependency: 'The Generic Course record must already exist.',
    frontendEffect: 'Used for cross-links and grouping on the public site.',
  },
  provider: {
    purpose: 'The organisation funding or offering this scholarship.',
    input: 'Search for an existing provider, or create a new one without leaving this form.',
    dataType: 'Relationship',
    required: 'Optional, but recommended for a named scholarship.',
    frontendEffect: 'Shown wherever this scholarship displays its provider.',
  },
  amount: {
    purpose: 'The monetary value of this scholarship or benefit.',
    input: 'A number only — select the currency separately.',
    dataType: 'Number',
    required: 'Optional.',
    example: '5000',
    dependency: 'If Amount is entered, Currency must also be entered.',
    frontendEffect: 'Shown alongside the currency wherever the amount is displayed.',
    caution: 'Entering an amount without a currency will be flagged — always set both together.',
  },
  currency: {
    purpose: 'The currency the Amount is stated in.',
    input: 'The official three-letter currency code.',
    dataType: 'Text',
    required: 'Required if an Amount is entered.',
    format: 'ISO 4217 three-letter code.',
    example: 'GBP',
    frontendEffect: 'Shown alongside the amount.',
  },
  deadline: {
    purpose: 'The application or availability deadline.',
    input: 'The real deadline date, if one exists.',
    dataType: 'Date',
    required: 'Optional.',
    frontendEffect: 'Shown on the public listing/detail card.',
    caution: 'Leave blank only when there genuinely is no fixed deadline — do not guess a date.',
  },
  applicationUrl: {
    purpose: 'The page where a visitor actually applies.',
    input: 'The official application page.',
    dataType: 'URL',
    required: 'Optional.',
    format: 'A valid URL.',
    frontendEffect: 'Used as the destination of the "Apply" action where shown.',
  },
  email: {
    purpose: 'A contact email address for this record.',
    input: 'A real, monitored email address.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown wherever this record’s contact details are displayed.',
  },
  phone: {
    purpose: 'A contact phone number for this record.',
    input: 'A real, monitored phone number.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown wherever this record’s contact details are displayed.',
  },
  websiteUrl: {
    purpose: 'The record’s own website.',
    input: 'The official website address.',
    dataType: 'URL',
    required: 'Optional.',
    format: 'A valid URL.',
    frontendEffect: 'Used as an outbound link where shown.',
  },
} satisfies Record<string, FieldHelpContent>;
