import { commonFieldHelp } from './common';
import type { FieldHelpContent } from './types';

/** Central lookup for every field's help content, keyed "<module>.<field>".
 * Common, identically-meaning fields (title, slug, status, SEO fields, …)
 * are pulled from `commonFieldHelp`; only fields whose meaning, format or
 * validation genuinely differs get a dedicated entry here. Every entry is
 * cross-checked against the actual rendered admin form and its backend
 * validation — see docs/phase1-admin-guide/ for the verification pass this
 * was built from. */
export const fieldHelpRegistry: Record<string, FieldHelpContent> = {
  // ---- Continents ----
  'continents.name': commonFieldHelp.name,
  'continents.slug': commonFieldHelp.slug,
  'continents.code': {
    purpose: 'A short, stable identifier for this continent.',
    input: 'A short code, if your team uses one.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'EU',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified.',
  },
  'continents.displayOrder': commonFieldHelp.displayOrder,
  'continents.description': commonFieldHelp.description,

  // ---- Countries ----
  'countries.continentId': {
    purpose: 'Which continent this country belongs to.',
    input: 'Select an existing, active Continent.',
    dataType: 'Relationship',
    required: 'Required.',
    dependency: 'The Continent record must already exist and be Active.',
    frontendEffect: 'Used to group and filter this country under its continent.',
  },
  'countries.name': commonFieldHelp.name,
  'countries.slug': commonFieldHelp.slug,
  'countries.iso2Code': {
    purpose: 'The official two-letter ISO 3166-1 country code.',
    input: 'The real ISO alpha-2 code for this country.',
    dataType: 'Text',
    required: 'Required.',
    format: 'Exactly two uppercase letters (A-Z).',
    example: 'GB',
    frontendEffect: 'Used for country identification and, where implemented, flag/format lookups.',
  },
  'countries.iso3Code': {
    purpose: 'The official three-letter ISO 3166-1 country code.',
    input: 'The real ISO alpha-3 code for this country.',
    dataType: 'Text',
    required: 'Required.',
    format: 'Exactly three uppercase letters (A-Z).',
    example: 'GBR',
    frontendEffect: 'Used for country identification and, where implemented, format lookups.',
  },
  'countries.pageHeading': {
    purpose: 'The heading shown at the top of this country’s public page.',
    input: 'A clear, specific heading.',
    dataType: 'Text',
    required: 'Required before publishing.',
    example: 'Study in the United Kingdom',
    frontendEffect: 'Shown as the page heading on the country detail page.',
  },
  'countries.shortDescription': commonFieldHelp.shortDescription,
  'countries.displayOrder': commonFieldHelp.displayOrder,
  'countries.isFeatured': commonFieldHelp.featured,

  // ---- Course levels / Study modes (Catalog masters) ----
  'course-levels.code': {
    purpose: 'A stable, machine-readable identifier for this course level.',
    input: 'A short, unique code.',
    dataType: 'Text',
    required: 'Required.',
    format: 'Uppercase letters, numbers, underscores and hyphens only.',
    example: 'POSTGRADUATE',
    frontendEffect: 'Referenced internally by course offerings and integrations.',
    caution: 'Courses and offerings reference this code — changing it after go-live can break existing links between records.',
  },
  'course-levels.name': commonFieldHelp.name,
  'course-levels.description': commonFieldHelp.description,
  'course-levels.educationOrder': {
    purpose: 'Where this level sits in the academic progression (used for level-aware sorting/filtering).',
    input: 'A whole number — lower numbers are earlier in the academic progression.',
    dataType: 'Number',
    required: 'Optional — leave at 0 if it does not matter.',
    example: '3',
    frontendEffect: 'Used to order levels academically, separate from the generic Display order.',
  },
  'study-modes.code': {
    purpose: 'A stable, machine-readable identifier for this study mode.',
    input: 'A short, unique code.',
    dataType: 'Text',
    required: 'Required.',
    format: 'Uppercase letters, numbers, underscores and hyphens only.',
    example: 'ON_CAMPUS',
    frontendEffect: 'Referenced internally by course offerings and integrations.',
    caution: 'Course offerings reference this code — changing it after go-live can break existing links between records.',
  },
  'study-modes.name': commonFieldHelp.name,
  'study-modes.description': commonFieldHelp.description,
  'intakes.name': commonFieldHelp.name,
  'intakes.monthNumber': {
    purpose: 'Which calendar month this intake falls in, for month-aware sorting and filters.',
    input: 'A number from 1 (January) to 12 (December), if this intake maps to a specific month.',
    dataType: 'Number',
    required: 'Optional.',
    format: '1–12.',
    example: '9',
    frontendEffect: 'Used for chronological ordering of intake options where shown.',
  },
  'scholarship-providers.name': commonFieldHelp.name,
  'scholarship-providers.websiteUrl': commonFieldHelp.websiteUrl,

  // ---- Generic Courses ----
  'courses.name': commonFieldHelp.name,
  'courses.slug': commonFieldHelp.slug,
  'courses.courseLevelId': {
    purpose: 'The qualification level this generic course represents.',
    input: 'Select an existing, active Course Level.',
    dataType: 'Relationship',
    required: 'Required.',
    frontendEffect: 'Shown as the level tag and used for level-based filtering.',
  },
  'courses.subSubjectId': {
    purpose: 'An optional link to a more specific specialisation within the chosen Subject.',
    input: 'Paste the ID of an existing Sub-subject, or leave blank.',
    dataType: 'Text (UUID)',
    required: 'Optional.',
    dependency: 'The Sub-subject must already exist under the chosen Subject.',
    frontendEffect: 'Used for finer-grained subject grouping where implemented.',
    caution: 'This is a raw ID field, not a searchable picker — an incorrect or unrelated ID will silently fail to match.',
  },
  'courses.shortName': {
    purpose: 'A short label used where space is limited, such as compact listing cards.',
    input: 'A brief version of the course name.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown in place of the full name where the template needs a shorter label.',
  },
  'courses.qualificationName': {
    purpose: 'The formal qualification name this course leads to.',
    input: 'The real qualification title, e.g. "Master of Science".',
    dataType: 'Text',
    required: 'Optional.',
    example: 'Master of Science',
    frontendEffect: 'Shown alongside the course name where the template includes it.',
  },
  'courses.courseCode': {
    purpose: 'An internal or external reference code for this course.',
    input: 'A short code, if one is used for this course.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified.',
  },
  'courses.studyModes': {
    purpose: 'Which delivery modes this generic course is available in.',
    input: 'Tick every relevant, active Study Mode.',
    dataType: 'Relationship (multi-select)',
    required: 'Optional.',
    frontendEffect: 'Used for study-mode filtering on the public courses directory.',
  },
  'courses.durationMin': {
    purpose: 'The shortest typical duration for this course.',
    input: 'A number, paired with the Duration unit.',
    dataType: 'Number',
    required: 'Optional.',
    dependency: 'Interpreted together with Duration unit.',
    frontendEffect: 'Shown as the course’s duration range.',
  },
  'courses.durationMax': {
    purpose: 'The longest typical duration for this course.',
    input: 'A number, paired with the Duration unit.',
    dataType: 'Number',
    required: 'Optional.',
    dependency: 'Interpreted together with Duration unit; should not be less than Duration min.',
    frontendEffect: 'Shown as the course’s duration range.',
  },
  'courses.durationUnit': {
    purpose: 'The unit the Duration min/max figures are measured in.',
    input: 'Select Years, Months or Semesters.',
    dataType: 'Choice',
    required: 'Optional, defaults to Years.',
    frontendEffect: 'Shown next to the duration figures.',
  },
  'courses.credits': {
    purpose: 'The academic credit value of this course, where applicable.',
    input: 'The real credit value.',
    dataType: 'Number',
    required: 'Optional.',
    frontendEffect: 'Shown where the template includes credit information.',
  },
  'courses.careerSummary': {
    purpose: 'A summary of typical career outcomes for graduates of this course.',
    input: 'Real, accurate career-outcome information.',
    dataType: 'Long text',
    required: 'Optional.',
    frontendEffect: 'Shown in the career outcomes section of the course page.',
  },
  'courses.popularityScore': {
    purpose: 'An internal score used to bias sorting toward more popular courses.',
    input: 'A number — higher generally means more popular. Leave blank if unknown.',
    dataType: 'Number',
    required: 'Optional.',
    frontendEffect: 'Can be used as a sort signal on course listings, alongside Display order and Featured.',
    caution: 'Do not fabricate a popularity figure — leave blank rather than guessing.',
  },

  // ---- Consultant Locations ----
  'consultant-locations.city': {
    purpose: 'The city this consultant office/branch is physically located in.',
    input: 'The real city name.',
    dataType: 'Text',
    required: 'Required.',
    frontendEffect: 'Shown as the location’s city, and used in the location’s own public page.',
  },

  // ---- Universities ----
  'universities.name': commonFieldHelp.name,
  'universities.slug': commonFieldHelp.slug,
  'universities.shortDescription': commonFieldHelp.shortDescription,
  'universities.countryId': commonFieldHelp.country,
  'universities.institutionType': {
    purpose: 'A free-text label describing the kind of institution.',
    input: 'A short label, e.g. "University" or "College".',
    dataType: 'Text',
    required: 'Optional.',
    example: 'University',
    frontendEffect: 'Shown as a label/badge on the university card and page.',
    caution: 'This is a plain text box, not a fixed list — keep wording consistent across records (always "University", not sometimes "Uni").',
  },
  'universities.sourceReference': commonFieldHelp.sourceUrl,
  'universities.featuredMediaId': commonFieldHelp.media,
  'universities.overview': commonFieldHelp.overview,
  'universities.displayOrder': commonFieldHelp.displayOrder,

  // ---- Campuses (repeatable rows on a University) ----
  'campuses.name': {
    purpose: 'The campus’s display name.',
    input: 'A clear, specific campus name.',
    dataType: 'Text',
    required: 'Required to save this row.',
    example: 'Main Campus',
    frontendEffect: 'Shown wherever this campus is listed, and as an option on Course Offerings.',
  },
  'campuses.city': {
    purpose: 'The city the campus is physically located in.',
    input: 'The real city name.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown as part of the campus location.',
  },
  'campuses.state': {
    purpose: 'The state or province the campus is physically located in.',
    input: 'The real state/province name.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown as part of the campus location.',
  },
  'campuses.address': {
    purpose: 'The campus’s full street address.',
    input: 'The real, complete address.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown on the campus/university detail page where available.',
  },

  // ---- Accreditations (repeatable rows on a University) ----
  'accreditations.name': {
    purpose: 'The name of the accreditation or recognition held.',
    input: 'The real accreditation name.',
    dataType: 'Text',
    required: 'Required to save this row.',
    example: 'AACSB Accreditation',
    frontendEffect: 'Shown in the university’s accreditations list.',
  },
  'accreditations.accreditor': {
    purpose: 'The body that granted this accreditation.',
    input: 'The real accrediting organisation’s name.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown alongside the accreditation name.',
  },
  'accreditations.referenceUrl': {
    purpose: 'A link to verify this accreditation.',
    input: 'The accrediting body’s official page confirming this accreditation.',
    dataType: 'URL',
    required: 'Optional.',
    format: 'A valid URL.',
    frontendEffect: 'Used as the verification link where the accreditation is shown, if supported by the current page template.',
  },

  // ---- Course requirements (repeatable rows on a University Course Offering) ----
  'requirements.category': {
    purpose: 'What kind of requirement this row describes.',
    input: 'A short label, e.g. "ACADEMIC" or "ENGLISH_TEST".',
    dataType: 'Text',
    required: 'Required to save this row.',
    example: 'ACADEMIC',
    frontendEffect: 'Groups this requirement under the matching heading on the offering page.',
    caution: 'This is a free-text box, not a fixed list — keep the wording consistent across offerings.',
  },
  'requirements.title': {
    purpose: 'The name of this specific requirement.',
    input: 'A clear, specific requirement name.',
    dataType: 'Text',
    required: 'Required to save this row.',
    example: 'IELTS Academic',
    frontendEffect: 'Shown as the requirement name on the offering page.',
  },
  'requirements.description': {
    purpose: 'Further detail about this requirement.',
    input: 'A concise, accurate description.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown alongside the requirement title.',
  },
  'requirements.minimumScore': {
    purpose: 'The minimum score or grade needed to satisfy this requirement.',
    input: 'The real minimum score, if this requirement has one.',
    dataType: 'Text',
    required: 'Optional.',
    example: '6.5',
    frontendEffect: 'Shown alongside the requirement on the offering page.',
  },

  // ---- University Course Offerings ----
  'offerings.name': commonFieldHelp.name,
  'offerings.slug': commonFieldHelp.slug,
  'offerings.universityId': commonFieldHelp.university,
  'offerings.genericCourseId': commonFieldHelp.course,
  'offerings.campusId': {
    purpose: 'The specific campus delivering this course.',
    input: 'Select a campus belonging to the chosen University.',
    dataType: 'Relationship',
    required: 'Optional.',
    dependency: 'A University must be selected first — the list is filtered to that university’s campuses.',
    frontendEffect: 'Shown as the delivery campus on the offering page.',
  },
  'offerings.courseLevelId': {
    purpose: 'The qualification level this offering awards.',
    input: 'Select an existing Course Level, e.g. Postgraduate.',
    dataType: 'Relationship',
    required: 'Required.',
    frontendEffect: 'Shown as the level tag on the offering.',
  },
  'offerings.studyMode': {
    purpose: 'How this course is delivered.',
    input: 'Select an existing Study Mode, e.g. On-campus.',
    dataType: 'Relationship',
    required: 'Optional.',
    frontendEffect: 'Shown as the mode tag on the offering.',
  },
  'offerings.durationUnit': {
    purpose: 'The unit the Duration figures are measured in.',
    input: 'Type the unit, e.g. YEARS.',
    dataType: 'Text',
    required: 'Optional, defaults to YEARS.',
    frontendEffect: 'Shown next to the duration figures.',
    caution: 'This is a free-text box, not a fixed list — keep the wording consistent.',
  },
  'offerings.currencyCode': commonFieldHelp.currency,
  'offerings.applicationUrl': commonFieldHelp.applicationUrl,
  'offerings.sourceReference': {
    ...commonFieldHelp.sourceUrl,
    required: 'Optional — this offering does not currently block publishing when left blank, unlike a Generic Course’s own country availability mapping.',
  },
  'offerings.featuredMediaId': commonFieldHelp.media,
  'offerings.overview': commonFieldHelp.overview,
  'offerings.displayOrder': commonFieldHelp.displayOrder,

  // ---- Scholarships ----
  'scholarships.title': commonFieldHelp.title,
  'scholarships.slug': commonFieldHelp.slug,
  'scholarships.summary': commonFieldHelp.shortDescription,
  'scholarships.providerId': commonFieldHelp.provider,
  'scholarships.benefitType': {
    purpose: 'What kind of benefit this scholarship provides.',
    input: 'A short label, e.g. "Tuition fee waiver".',
    dataType: 'Text',
    required: 'Optional.',
    example: 'Tuition fee waiver',
    frontendEffect: 'Shown as a badge on the scholarship card.',
  },
  'scholarships.amount': commonFieldHelp.amount,
  'scholarships.currencyCode': commonFieldHelp.currency,
  'scholarships.deadline': commonFieldHelp.deadline,
  'scholarships.applicationUrl': commonFieldHelp.applicationUrl,
  'scholarships.sourceReference': commonFieldHelp.sourceUrl,
  'scholarships.featuredMediaId': commonFieldHelp.media,
  'scholarships.description': commonFieldHelp.description,
  'scholarships.eligibility': {
    purpose: 'Who can apply for this scholarship.',
    input: 'Real, accurate eligibility criteria.',
    dataType: 'Long text',
    required: 'Optional.',
    frontendEffect: 'Shown in the eligibility section of the scholarship page.',
  },
  'scholarships.displayOrder': commonFieldHelp.displayOrder,

  // ---- Consultants ----
  'consultants.name': commonFieldHelp.name,
  'consultants.slug': commonFieldHelp.slug,
  'consultants.shortDescription': commonFieldHelp.shortDescription,
  'consultants.email': commonFieldHelp.email,
  'consultants.phone': commonFieldHelp.phone,
  'consultants.websiteUrl': commonFieldHelp.websiteUrl,
  'consultants.verificationStatus': {
    purpose: 'Marks whether this consultant’s identity/credentials have been verified.',
    input: 'Select Verified once you have confirmed this consultant is legitimate.',
    dataType: 'Choice',
    required: 'Optional, defaults to Unverified.',
    frontendEffect: 'Shown as a trust indicator, independent of whether the record is Published.',
    caution: 'Verified and Published are independent — verifying does not publish, and publishing does not verify.',
  },
  'consultants.sourceReference': commonFieldHelp.sourceUrl,
  'consultants.featuredMediaId': commonFieldHelp.media,
  'consultants.description': commonFieldHelp.description,
  'consultants.displayOrder': commonFieldHelp.displayOrder,

  // ---- Jobs ----
  'jobs.title': commonFieldHelp.title,
  'jobs.slug': commonFieldHelp.slug,
  'jobs.summary': commonFieldHelp.shortDescription,
  'jobs.department': {
    purpose: 'Which team or department this role belongs to.',
    input: 'A short department name.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'Student Success',
    frontendEffect: 'Shown as a tag on the job listing.',
  },
  'jobs.employmentType': {
    purpose: 'The employment arrangement for this role.',
    input: 'A short label, e.g. "Full-time".',
    dataType: 'Text',
    required: 'Optional.',
    example: 'Full-time',
    frontendEffect: 'Shown as a tag on the job listing.',
    caution: 'This is a free-text box, not a fixed list — keep wording consistent (always "Full-time", not sometimes "FT").',
  },
  'jobs.location': {
    purpose: 'A free-text description of where this role is based.',
    input: 'A short location description.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'London, United Kingdom',
    frontendEffect: 'Shown as text on the job listing.',
  },
  'jobs.remoteStatus': {
    purpose: 'Whether this role can be done remotely.',
    input: 'A short label, e.g. "On-site" or "Remote".',
    dataType: 'Text',
    required: 'Optional.',
    example: 'On-site',
    frontendEffect: 'Shown as a tag on the job listing.',
    caution: 'This is a free-text box, not a fixed list.',
  },
  'jobs.applicationUrl': commonFieldHelp.applicationUrl,
  'jobs.applicationEmail': {
    purpose: 'The email address applicants should send their application to.',
    input: 'A real, monitored email address.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown as the "apply by email" option on the job listing.',
  },
  'jobs.description': commonFieldHelp.description,
  'jobs.displayOrder': commonFieldHelp.displayOrder,

  // ---- Events ----
  'events.title': commonFieldHelp.title,
  'events.slug': commonFieldHelp.slug,
  'events.summary': commonFieldHelp.shortDescription,
  'events.startsAt': {
    purpose: 'When the event begins.',
    input: 'The real date and time the event starts.',
    dataType: 'Date and time',
    required: 'Required.',
    frontendEffect: 'Shown as the event start time.',
  },
  'events.endsAt': {
    purpose: 'When the event ends.',
    input: 'The real date and time the event ends, if known.',
    dataType: 'Date and time',
    required: 'Optional.',
    frontendEffect: 'Shown as the event end time.',
    caution: 'Must be later than the start time.',
  },
  'events.timezone': {
    purpose: 'The timezone the event’s times should be interpreted in.',
    input: 'The event’s real local timezone.',
    dataType: 'Text',
    required: 'Optional, defaults to Asia/Kolkata.',
    example: 'Europe/London',
    frontendEffect: 'Affects how the event time is displayed/converted.',
    caution: 'The default is Asia/Kolkata — always check and correct it for events happening elsewhere.',
  },
  'events.eventType': {
    purpose: 'How the event is delivered.',
    input: 'Choose Offline, Online or Hybrid.',
    dataType: 'Choice',
    required: 'Optional, defaults to Offline.',
    frontendEffect: 'Shown as the event type badge.',
  },
  'events.venue': {
    purpose: 'Where an offline or hybrid event physically takes place.',
    input: 'The real venue name and address.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown as the event venue.',
  },
  'events.onlineUrl': {
    purpose: 'The link to join an online or hybrid event.',
    input: 'The real meeting/streaming link.',
    dataType: 'URL',
    required: 'Optional — relevant when Event type is Online or Hybrid.',
    frontendEffect: 'Used as the "Join" link.',
  },
  'events.featuredMediaId': commonFieldHelp.media,
  'events.registrationUrl': {
    purpose: 'Where a visitor registers to attend.',
    input: 'The real registration page or form link.',
    dataType: 'URL',
    required: 'Optional.',
    frontendEffect: 'Used as the registration link.',
  },
  'events.description': commonFieldHelp.description,
  'events.displayOrder': commonFieldHelp.displayOrder,

  // ---- Success Stories ----
  'success-stories.title': commonFieldHelp.title,
  'success-stories.slug': commonFieldHelp.slug,
  'success-stories.journey': {
    purpose: 'The main narrative shown on the story’s page.',
    input: 'The full story text.',
    dataType: 'Long text',
    required: 'Required.',
    frontendEffect: 'Shown as the main body of the success story page.',
    caution: 'If this is not a real, consenting student, the text must clearly state it is a demonstration profile — never present fabricated content as a real student’s story.',
  },
  'success-stories.attribution': {
    purpose: 'Who the story is attributed to.',
    input: 'The student’s name, or a clear demonstration label.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown as the byline.',
  },
  'success-stories.attributionNote': {
    purpose: 'A short sub-line under the attribution, e.g. course and university.',
    input: 'A short, accurate sub-line.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown alongside the attribution.',
  },
  'success-stories.featuredMediaId': commonFieldHelp.media,
  'success-stories.countryId': commonFieldHelp.country,
  'success-stories.universityId': commonFieldHelp.university,

  // ---- Testimonials ----
  'testimonials.quote': {
    purpose: 'The testimonial text itself.',
    input: 'The full quoted testimonial.',
    dataType: 'Long text',
    required: 'Required.',
    frontendEffect: 'Shown as the testimonial text.',
    caution: 'If this is not a real, consenting student, the text must clearly state it is a demonstration profile.',
  },
  'testimonials.attribution': {
    purpose: 'Who the testimonial is attributed to.',
    input: 'The student’s name, or a clear demonstration label.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown as the byline.',
  },
  'testimonials.attributionNote': {
    purpose: 'A short sub-line under the attribution.',
    input: 'A short, accurate sub-line.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown alongside the attribution.',
  },
  'testimonials.imageMediaId': commonFieldHelp.media,
  'testimonials.universityId': commonFieldHelp.university,

  // ---- Settings: General ----
  'settings.general.siteName': {
    purpose: 'Your site’s name.',
    input: 'Your organisation’s name as it should appear on the site.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'Universta',
    frontendEffect: 'Shown as the text logo in the header and footer on every page.',
  },
  'settings.general.defaultLocale': {
    purpose: 'The default language/locale code for the public site.',
    input: 'A short locale code.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'en',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified — the site currently renders English content regardless of this value.',
  },
  'settings.general.defaultTimezone': {
    purpose: 'The default timezone used when no other timezone is specified.',
    input: 'A real IANA timezone name.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'America/Toronto',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified — dates are currently shown as entered/converted per-field.',
  },
  'settings.general.supportEmail': {
    purpose: 'The support contact address used in system notices.',
    input: 'A real, monitored support email address.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Used in some system notices.',
    caution: 'Replace any placeholder/.local address with a real one before go-live.',
  },
  'settings.general.supportPhone': {
    purpose: 'The support contact phone number.',
    input: 'A real, monitored phone number.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified.',
  },

  // ---- Settings: Branding ----
  'settings.branding.logoMediaId': {
    purpose: 'Your logo image.',
    input: 'Choose an existing image from the Media Library, or upload a new one.',
    dataType: 'Image',
    required: 'Optional.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified — the live header/footer currently render a text logo rather than this image.',
  },
  'settings.branding.faviconMediaId': {
    purpose: 'The small icon shown in the browser tab.',
    input: 'Choose a small, square image from the Media Library.',
    dataType: 'Image',
    required: 'Optional.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified.',
  },
  'settings.branding.primaryColor': {
    purpose: 'Your brand’s primary colour.',
    input: 'Pick your brand colour.',
    dataType: 'Colour',
    required: 'Optional.',
    format: 'A hex colour value, e.g. #1657CF.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified — the live site currently uses its own fixed colour palette.',
  },
  'settings.branding.secondaryColor': {
    purpose: 'Your brand’s secondary colour.',
    input: 'Pick your secondary brand colour.',
    dataType: 'Colour',
    required: 'Optional.',
    format: 'A hex colour value.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified.',
  },
  'settings.branding.defaultSocialImageMediaId': {
    purpose: 'The fallback image used when a page is shared on social media and has no image of its own.',
    input: 'Choose an on-brand, wide image from the Media Library.',
    dataType: 'Image',
    required: 'Optional.',
    frontendEffect: 'Used as the social share card image on pages without their own Open Graph image.',
  },

  // ---- Settings: Contact ----
  'settings.contact.address': {
    purpose: 'Your registered or business address.',
    input: 'The real, full address.',
    dataType: 'Long text',
    required: 'Optional.',
    frontendEffect: 'Shown wherever the site displays a business address.',
  },
  'settings.contact.email': {
    purpose: 'The public contact email address.',
    input: 'A real, monitored email address.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown on public contact points.',
  },
  'settings.contact.counsellingPhone': {
    purpose: 'The phone number shown for booking counselling.',
    input: 'A real, monitored phone number.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Shown on public contact points.',
  },
  'settings.contact.whatsappLink': {
    purpose: 'A link that opens a WhatsApp chat with your team.',
    input: 'A real wa.me or WhatsApp Business link.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the WhatsApp option.',
    format: 'A valid URL.',
    frontendEffect: 'Shown as a WhatsApp contact option when set.',
  },

  // ---- Settings: Social links ----
  'settings.social.facebook': {
    purpose: 'Your Facebook page link.',
    input: 'The real page URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the icon.',
    frontendEffect: 'Shown as a social icon in the footer when set.',
  },
  'settings.social.instagram': {
    purpose: 'Your Instagram profile link.',
    input: 'The real profile URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the icon.',
    frontendEffect: 'Shown as a social icon in the footer when set.',
  },
  'settings.social.linkedin': {
    purpose: 'Your LinkedIn page link.',
    input: 'The real page URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the icon.',
    frontendEffect: 'Shown as a social icon in the footer when set.',
  },
  'settings.social.youtube': {
    purpose: 'Your YouTube channel link.',
    input: 'The real channel URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the icon.',
    frontendEffect: 'Shown as a social icon in the footer when set.',
  },
  'settings.social.twitter': {
    purpose: 'Your X/Twitter profile link.',
    input: 'The real profile URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the icon.',
    frontendEffect: 'Shown as a social icon in the footer when set.',
  },

  // ---- Settings: Global Header ----
  'settings.header.menuKey': {
    purpose: 'Which Navigation Menu supplies this header’s links.',
    input: 'The menu key of an existing Navigation Menu, usually "header".',
    dataType: 'Text',
    required: 'Optional, defaults to "header".',
    dependency: 'A Navigation Menu with this key should exist.',
    frontendEffect: 'Controls which menu’s items render in the header.',
    caution: 'Changing this to a key with no matching menu leaves the header with no links.',
  },
  'settings.header.ctaLabel': {
    purpose: 'The text on the header’s main call-to-action button.',
    input: 'A short, action-oriented label.',
    dataType: 'Text',
    required: 'Optional.',
    example: 'Book Free Counselling',
    frontendEffect: 'Header button text on every public page.',
    caution: 'This is a site-wide setting — changing it affects every page at once.',
  },
  'settings.header.ctaUrl': {
    purpose: 'Where the header’s main call-to-action button links to.',
    input: 'A real, working internal path or URL.',
    dataType: 'Text',
    required: 'Optional.',
    example: '/counselling',
    frontendEffect: 'Header button link on every public page.',
    caution: 'This is a site-wide setting — changing it affects every page at once.',
  },
  'settings.header.ctaVisible': {
    purpose: 'Shows or hides the header’s main call-to-action button.',
    input: 'Tick to show the button.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'Hides the header CTA button site-wide when unchecked.',
  },
  'settings.header.sticky': {
    purpose: 'Keeps the header visible while a visitor scrolls down the page.',
    input: 'Tick to make the header sticky.',
    dataType: 'Checkbox',
    required: 'Optional.',
    frontendEffect: 'Header stays pinned to the top of the viewport while scrolling, site-wide.',
  },
  'settings.header.announcementText': {
    purpose: 'A short message shown in an announcement bar above the header.',
    input: 'A short, current message.',
    dataType: 'Text',
    required: 'Optional — leave blank to hide the bar.',
    frontendEffect: 'Shown as a banner above the header on every public page when set and visible.',
  },
  'settings.header.announcementUrl': {
    purpose: 'Where the announcement bar links to, if anywhere.',
    input: 'A real internal path or URL.',
    dataType: 'URL',
    required: 'Optional.',
    frontendEffect: 'Makes the announcement bar clickable when set.',
  },
  'settings.header.announcementVisible': {
    purpose: 'Shows or hides the announcement bar.',
    input: 'Tick to show the bar (requires announcement text).',
    dataType: 'Checkbox',
    required: 'Optional.',
    dependency: 'Only has a visible effect when Announcement bar text is also set.',
    frontendEffect: 'Shows/hides the announcement bar site-wide.',
  },
  'settings.header.accountCtaLabel': {
    purpose: 'The label for an optional secondary account/login button in the header.',
    input: 'A short label.',
    dataType: 'Text',
    required: 'Optional.',
    dependency: 'Only shown once Account CTA destination is also set.',
    frontendEffect: 'Shown as a secondary header button once both label and destination are set.',
  },
  'settings.header.accountCtaUrl': {
    purpose: 'Where the optional secondary account/login header button links to.',
    input: 'A real internal path or URL.',
    dataType: 'URL',
    required: 'Optional — the button stays hidden until this is set.',
    frontendEffect: 'Shows a secondary header button once set.',
  },

  // ---- Settings: Global Footer ----
  'settings.footer.menuKey': {
    purpose: 'Which Navigation Menu supplies this footer’s link columns.',
    input: 'The menu key of an existing Navigation Menu, usually "footer".',
    dataType: 'Text',
    required: 'Optional, defaults to "footer".',
    dependency: 'A Navigation Menu with this key should exist.',
    frontendEffect: 'Controls which menu’s items render as footer link columns.',
  },
  'settings.footer.description': {
    purpose: 'A short description shown in the footer, usually about the organisation.',
    input: 'A concise, accurate description.',
    dataType: 'Long text',
    required: 'Optional.',
    frontendEffect: 'Shown in the footer on every public page.',
  },
  'settings.footer.counsellingCtaLabel': {
    purpose: 'The label for the footer’s counselling call-to-action.',
    input: 'A short, action-oriented label.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'Footer button text on every public page.',
  },
  'settings.footer.counsellingCtaUrl': {
    purpose: 'Where the footer’s counselling call-to-action links to.',
    input: 'A real internal path or URL.',
    dataType: 'URL',
    required: 'Optional.',
    frontendEffect: 'Footer button link on every public page.',
  },
  'settings.footer.counsellingCtaVisible': {
    purpose: 'Shows or hides the footer’s counselling call-to-action.',
    input: 'Tick to show it.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'Hides the footer CTA site-wide when unchecked.',
  },
  'settings.footer.showContact': {
    purpose: 'Shows or hides the contact details column in the footer.',
    input: 'Tick to show it.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'Hides the footer contact column site-wide when unchecked.',
  },
  'settings.footer.showSocial': {
    purpose: 'Shows or hides the social icons in the footer.',
    input: 'Tick to show them.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    dependency: 'Only shows icons for social links that are actually set.',
    frontendEffect: 'Hides the footer social icons site-wide when unchecked.',
  },
  'settings.footer.copyrightText': {
    purpose: 'The copyright line shown at the bottom of the footer.',
    input: 'A short, current copyright line.',
    dataType: 'Text',
    required: 'Optional.',
    example: '© 2026 Universta. All rights reserved.',
    frontendEffect: 'Shown at the bottom of the footer on every public page.',
  },
  'settings.footer.privacyUrl': {
    purpose: 'Where the footer’s Privacy Policy link points to.',
    input: 'A real internal path or URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the link.',
    frontendEffect: 'Shown as a footer link when set.',
  },
  'settings.footer.termsUrl': {
    purpose: 'Where the footer’s Terms link points to.',
    input: 'A real internal path or URL.',
    dataType: 'URL',
    required: 'Optional — leave blank to hide the link.',
    frontendEffect: 'Shown as a footer link when set.',
  },

  // ---- Settings: Default SEO ----
  'settings.seo.defaultTitleSuffix': {
    purpose: 'Text appended after the page title in the browser tab.',
    input: 'A short suffix, usually your site name.',
    dataType: 'Text',
    required: 'Optional.',
    example: '| Universta',
    frontendEffect: 'Appended to page titles on pages that use the shared title helper.',
  },
  'settings.seo.defaultDescription': {
    purpose: 'A fallback search-result description when a page has none of its own.',
    input: 'A general, on-brand sentence.',
    dataType: 'Text',
    required: 'Optional.',
    frontendEffect: 'This value is stored, but no public visual effect is currently verified — every page currently supplies its own fallback description already.',
  },
  'settings.seo.defaultOgImageMediaId': {
    purpose: 'The fallback social-share image used when a page has none of its own.',
    input: 'Choose an on-brand, wide image from the Media Library.',
    dataType: 'Image',
    required: 'Optional.',
    frontendEffect: 'Used as the social share card image on pages without their own Open Graph image.',
  },
  'settings.seo.defaultRobotsIndex': {
    purpose: 'The default "allow indexing" behaviour for pages that don’t set their own.',
    input: 'Leave checked for normal sites.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'Used as the fallback robots-index behaviour where a page has none of its own.',
  },
  'settings.seo.defaultRobotsFollow': {
    purpose: 'The default "allow following links" behaviour for pages that don’t set their own.',
    input: 'Leave checked for normal sites.',
    dataType: 'Checkbox',
    required: 'Optional, defaults on.',
    frontendEffect: 'Used as the fallback robots-follow behaviour where a page has none of its own.',
  },
};

/** Looks up a field's help content, falling back gracefully when a key is
 * missing (logs a warning in development instead of crashing the form). */
export function getFieldHelp(key: string): FieldHelpContent | undefined {
  const entry = fieldHelpRegistry[key];
  if (!entry && process.env.NODE_ENV !== 'production') {
    console.warn(`[field-help] Missing help content for key "${key}"`);
  }
  return entry;
}
