/**
 * The currency list the Country editor selects from.
 *
 * Currency name, code and symbol used to be three free-text inputs, so
 * nothing stopped "Euro / USD / £" being saved. They are one choice now, and
 * this table is that choice's vocabulary.
 *
 * Generated by scripts/country-table/generate.mjs -- edit that, not this.
 * ISO codes and currencies from world-countries (ISO 3166 / 4217); flag
 * colours measured from the flag-icons SVGs (MIT) by rendering and counting
 * pixels, so a share is the share of the flag a colour covers.
 */

export type CurrencyOption = { code: string; name: string; symbol: string };

export const CURRENCY_OPTIONS: readonly CurrencyOption[] = [
  {
    code: "AED",
    name: "United Arab Emirates dirham",
    symbol: "د.إ"
  },
  {
    code: "AFN",
    name: "Afghan afghani",
    symbol: "؋"
  },
  {
    code: "ALL",
    name: "Albanian lek",
    symbol: "L"
  },
  {
    code: "AMD",
    name: "Armenian dram",
    symbol: "֏"
  },
  {
    code: "ANG",
    name: "Netherlands Antillean guilder",
    symbol: "ƒ"
  },
  {
    code: "AOA",
    name: "Angolan kwanza",
    symbol: "Kz"
  },
  {
    code: "ARS",
    name: "Argentine peso",
    symbol: "$"
  },
  {
    code: "AUD",
    name: "Australian dollar",
    symbol: "$"
  },
  {
    code: "AWG",
    name: "Aruban florin",
    symbol: "ƒ"
  },
  {
    code: "AZN",
    name: "Azerbaijani manat",
    symbol: "₼"
  },
  {
    code: "BAM",
    name: "Bosnia and Herzegovina convertible mark",
    symbol: "KM"
  },
  {
    code: "BBD",
    name: "Barbadian dollar",
    symbol: "$"
  },
  {
    code: "BDT",
    name: "Bangladeshi taka",
    symbol: "৳"
  },
  {
    code: "BGN",
    name: "Bulgarian lev",
    symbol: "лв"
  },
  {
    code: "BHD",
    name: "Bahraini dinar",
    symbol: ".د.ب"
  },
  {
    code: "BIF",
    name: "Burundian franc",
    symbol: "Fr"
  },
  {
    code: "BMD",
    name: "Bermudian dollar",
    symbol: "$"
  },
  {
    code: "BND",
    name: "Brunei dollar",
    symbol: "$"
  },
  {
    code: "BOB",
    name: "Bolivian boliviano",
    symbol: "Bs."
  },
  {
    code: "BRL",
    name: "Brazilian real",
    symbol: "R$"
  },
  {
    code: "BSD",
    name: "Bahamian dollar",
    symbol: "$"
  },
  {
    code: "BTN",
    name: "Bhutanese ngultrum",
    symbol: "Nu."
  },
  {
    code: "BWP",
    name: "Botswana pula",
    symbol: "P"
  },
  {
    code: "BYN",
    name: "Belarusian ruble",
    symbol: "Br"
  },
  {
    code: "BZD",
    name: "Belize dollar",
    symbol: "$"
  },
  {
    code: "CAD",
    name: "Canadian dollar",
    symbol: "$"
  },
  {
    code: "CDF",
    name: "Congolese franc",
    symbol: "FC"
  },
  {
    code: "CHF",
    name: "Swiss franc",
    symbol: "CHF"
  },
  {
    code: "CLP",
    name: "Chilean peso",
    symbol: "$"
  },
  {
    code: "CNY",
    name: "Chinese yuan",
    symbol: "¥"
  },
  {
    code: "COP",
    name: "Colombian peso",
    symbol: "$"
  },
  {
    code: "CRC",
    name: "Costa Rican colón",
    symbol: "₡"
  },
  {
    code: "CUC",
    name: "Cuban convertible peso",
    symbol: "$"
  },
  {
    code: "CVE",
    name: "Cape Verdean escudo",
    symbol: "Esc"
  },
  {
    code: "CZK",
    name: "Czech koruna",
    symbol: "Kč"
  },
  {
    code: "DJF",
    name: "Djiboutian franc",
    symbol: "Fr"
  },
  {
    code: "DKK",
    name: "Danish krone",
    symbol: "kr"
  },
  {
    code: "DOP",
    name: "Dominican peso",
    symbol: "$"
  },
  {
    code: "DZD",
    name: "Algerian dinar",
    symbol: "د.ج"
  },
  {
    code: "EGP",
    name: "Egyptian pound",
    symbol: "£"
  },
  {
    code: "ERN",
    name: "Eritrean nakfa",
    symbol: "Nfk"
  },
  {
    code: "ETB",
    name: "Ethiopian birr",
    symbol: "Br"
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€"
  },
  {
    code: "FJD",
    name: "Fijian dollar",
    symbol: "$"
  },
  {
    code: "GBP",
    name: "British pound",
    symbol: "£"
  },
  {
    code: "GEL",
    name: "lari",
    symbol: "₾"
  },
  {
    code: "GHS",
    name: "Ghanaian cedi",
    symbol: "₵"
  },
  {
    code: "GMD",
    name: "dalasi",
    symbol: "D"
  },
  {
    code: "GNF",
    name: "Guinean franc",
    symbol: "Fr"
  },
  {
    code: "GTQ",
    name: "Guatemalan quetzal",
    symbol: "Q"
  },
  {
    code: "GYD",
    name: "Guyanese dollar",
    symbol: "$"
  },
  {
    code: "HKD",
    name: "Hong Kong dollar",
    symbol: "$"
  },
  {
    code: "HNL",
    name: "Honduran lempira",
    symbol: "L"
  },
  {
    code: "HTG",
    name: "Haitian gourde",
    symbol: "G"
  },
  {
    code: "HUF",
    name: "Hungarian forint",
    symbol: "Ft"
  },
  {
    code: "IDR",
    name: "Indonesian rupiah",
    symbol: "Rp"
  },
  {
    code: "ILS",
    name: "Israeli new shekel",
    symbol: "₪"
  },
  {
    code: "INR",
    name: "Indian rupee",
    symbol: "₹"
  },
  {
    code: "IQD",
    name: "Iraqi dinar",
    symbol: "ع.د"
  },
  {
    code: "IRR",
    name: "Iranian rial",
    symbol: "﷼"
  },
  {
    code: "ISK",
    name: "Icelandic króna",
    symbol: "kr"
  },
  {
    code: "JMD",
    name: "Jamaican dollar",
    symbol: "$"
  },
  {
    code: "JOD",
    name: "Jordanian dinar",
    symbol: "د.ا"
  },
  {
    code: "JPY",
    name: "Japanese yen",
    symbol: "¥"
  },
  {
    code: "KES",
    name: "Kenyan shilling",
    symbol: "KSh"
  },
  {
    code: "KGS",
    name: "Kyrgyzstani som",
    symbol: "с"
  },
  {
    code: "KHR",
    name: "Cambodian riel",
    symbol: "៛"
  },
  {
    code: "KMF",
    name: "Comorian franc",
    symbol: "Fr"
  },
  {
    code: "KPW",
    name: "North Korean won",
    symbol: "₩"
  },
  {
    code: "KRW",
    name: "South Korean won",
    symbol: "₩"
  },
  {
    code: "KWD",
    name: "Kuwaiti dinar",
    symbol: "د.ك"
  },
  {
    code: "KYD",
    name: "Cayman Islands dollar",
    symbol: "$"
  },
  {
    code: "KZT",
    name: "Kazakhstani tenge",
    symbol: "₸"
  },
  {
    code: "LAK",
    name: "Lao kip",
    symbol: "₭"
  },
  {
    code: "LBP",
    name: "Lebanese pound",
    symbol: "ل.ل"
  },
  {
    code: "LKR",
    name: "Sri Lankan rupee",
    symbol: "Rs"
  },
  {
    code: "LRD",
    name: "Liberian dollar",
    symbol: "$"
  },
  {
    code: "LSL",
    name: "Lesotho loti",
    symbol: "L"
  },
  {
    code: "LYD",
    name: "Libyan dinar",
    symbol: "ل.د"
  },
  {
    code: "MAD",
    name: "Moroccan dirham",
    symbol: "د.م."
  },
  {
    code: "MDL",
    name: "Moldovan leu",
    symbol: "L"
  },
  {
    code: "MGA",
    name: "Malagasy ariary",
    symbol: "Ar"
  },
  {
    code: "MKD",
    name: "denar",
    symbol: "den"
  },
  {
    code: "MMK",
    name: "Burmese kyat",
    symbol: "Ks"
  },
  {
    code: "MNT",
    name: "Mongolian tögrög",
    symbol: "₮"
  },
  {
    code: "MOP",
    name: "Macanese pataca",
    symbol: "P"
  },
  {
    code: "MRU",
    name: "Mauritanian ouguiya",
    symbol: "UM"
  },
  {
    code: "MUR",
    name: "Mauritian rupee",
    symbol: "₨"
  },
  {
    code: "MVR",
    name: "Maldivian rufiyaa",
    symbol: ".ރ"
  },
  {
    code: "MWK",
    name: "Malawian kwacha",
    symbol: "MK"
  },
  {
    code: "MXN",
    name: "Mexican peso",
    symbol: "$"
  },
  {
    code: "MYR",
    name: "Malaysian ringgit",
    symbol: "RM"
  },
  {
    code: "MZN",
    name: "Mozambican metical",
    symbol: "MT"
  },
  {
    code: "NAD",
    name: "Namibian dollar",
    symbol: "$"
  },
  {
    code: "NGN",
    name: "Nigerian naira",
    symbol: "₦"
  },
  {
    code: "NIO",
    name: "Nicaraguan córdoba",
    symbol: "C$"
  },
  {
    code: "NOK",
    name: "Norwegian krone",
    symbol: "kr"
  },
  {
    code: "NPR",
    name: "Nepalese rupee",
    symbol: "Rs"
  },
  {
    code: "NZD",
    name: "New Zealand dollar",
    symbol: "$"
  },
  {
    code: "OMR",
    name: "Omani rial",
    symbol: "﷼"
  },
  {
    code: "PAB",
    name: "Panamanian balboa",
    symbol: "B/."
  },
  {
    code: "PEN",
    name: "Peruvian sol",
    symbol: "S/"
  },
  {
    code: "PGK",
    name: "Papua New Guinean kina",
    symbol: "K"
  },
  {
    code: "PHP",
    name: "Philippine peso",
    symbol: "₱"
  },
  {
    code: "PKR",
    name: "Pakistani rupee",
    symbol: "₨"
  },
  {
    code: "PLN",
    name: "Polish złoty",
    symbol: "zł"
  },
  {
    code: "PYG",
    name: "Paraguayan guaraní",
    symbol: "₲"
  },
  {
    code: "QAR",
    name: "Qatari riyal",
    symbol: "﷼"
  },
  {
    code: "RON",
    name: "Romanian leu",
    symbol: "lei"
  },
  {
    code: "RSD",
    name: "Serbian dinar",
    symbol: "дин"
  },
  {
    code: "RUB",
    name: "Russian ruble",
    symbol: "₽"
  },
  {
    code: "RWF",
    name: "Rwandan franc",
    symbol: "Fr"
  },
  {
    code: "SAR",
    name: "Saudi riyal",
    symbol: "﷼"
  },
  {
    code: "SBD",
    name: "Solomon Islands dollar",
    symbol: "$"
  },
  {
    code: "SCR",
    name: "Seychellois rupee",
    symbol: "₨"
  },
  {
    code: "SDG",
    name: "Sudanese pound",
    symbol: "PT"
  },
  {
    code: "SEK",
    name: "Swedish krona",
    symbol: "kr"
  },
  {
    code: "SGD",
    name: "Singapore dollar",
    symbol: "$"
  },
  {
    code: "SLL",
    name: "Sierra Leonean leone",
    symbol: "Le"
  },
  {
    code: "SOS",
    name: "Somali shilling",
    symbol: "Sh"
  },
  {
    code: "SRD",
    name: "Surinamese dollar",
    symbol: "$"
  },
  {
    code: "SSP",
    name: "South Sudanese pound",
    symbol: "£"
  },
  {
    code: "STN",
    name: "São Tomé and Príncipe dobra",
    symbol: "Db"
  },
  {
    code: "SYP",
    name: "Syrian pound",
    symbol: "£"
  },
  {
    code: "SZL",
    name: "Swazi lilangeni",
    symbol: "L"
  },
  {
    code: "THB",
    name: "Thai baht",
    symbol: "฿"
  },
  {
    code: "TJS",
    name: "Tajikistani somoni",
    symbol: "ЅМ"
  },
  {
    code: "TMT",
    name: "Turkmenistan manat",
    symbol: "m"
  },
  {
    code: "TND",
    name: "Tunisian dinar",
    symbol: "د.ت"
  },
  {
    code: "TOP",
    name: "Tongan paʻanga",
    symbol: "T$"
  },
  {
    code: "TRY",
    name: "Turkish lira",
    symbol: "₺"
  },
  {
    code: "TTD",
    name: "Trinidad and Tobago dollar",
    symbol: "$"
  },
  {
    code: "TWD",
    name: "New Taiwan dollar",
    symbol: "$"
  },
  {
    code: "TZS",
    name: "Tanzanian shilling",
    symbol: "TSh"
  },
  {
    code: "UAH",
    name: "Ukrainian hryvnia",
    symbol: "₴"
  },
  {
    code: "UGX",
    name: "Ugandan shilling",
    symbol: "USh"
  },
  {
    code: "USD",
    name: "United States dollar",
    symbol: "$"
  },
  {
    code: "UYU",
    name: "Uruguayan peso",
    symbol: "$"
  },
  {
    code: "UZS",
    name: "Uzbekistani soʻm",
    symbol: "soʼm"
  },
  {
    code: "VES",
    name: "Venezuelan bolívar soberano",
    symbol: "Bs.S."
  },
  {
    code: "VND",
    name: "Vietnamese đồng",
    symbol: "₫"
  },
  {
    code: "VUV",
    name: "Vanuatu vatu",
    symbol: "Vt"
  },
  {
    code: "WST",
    name: "Samoan tālā",
    symbol: "T"
  },
  {
    code: "XAF",
    name: "Central African CFA franc",
    symbol: "Fr"
  },
  {
    code: "XCD",
    name: "Eastern Caribbean dollar",
    symbol: "$"
  },
  {
    code: "XOF",
    name: "West African CFA franc",
    symbol: "Fr"
  },
  {
    code: "XPF",
    name: "CFP franc",
    symbol: "₣"
  },
  {
    code: "YER",
    name: "Yemeni rial",
    symbol: "﷼"
  },
  {
    code: "ZAR",
    name: "South African rand",
    symbol: "R"
  },
  {
    code: "ZMW",
    name: "Zambian kwacha",
    symbol: "ZK"
  }
];

const BY_CODE = new Map(CURRENCY_OPTIONS.map((row) => [row.code, row]));

export function currencyByCode(code: string | null | undefined) {
  return code ? (BY_CODE.get(code.trim().toUpperCase()) ?? null) : null;
}

/** Matches a stored currency however it was recorded, so legacy rows that hold
 * only a name or only a symbol still select the right option. */
export function matchCurrency(value: {
  code?: string | null;
  name?: string | null;
  symbol?: string | null;
}) {
  const byCode = currencyByCode(value.code);
  if (byCode) return byCode;
  const name = value.name?.trim().toLowerCase();
  if (name) {
    const found = CURRENCY_OPTIONS.find((row) => row.name.toLowerCase() === name);
    if (found) return found;
  }
  const symbol = value.symbol?.trim();
  if (symbol) {
    const matches = CURRENCY_OPTIONS.filter((row) => row.symbol === symbol);
    /* Only when it is unambiguous -- "$" belongs to several currencies, and
     * guessing one would silently rewrite the operator's data. */
    if (matches.length === 1) return matches[0];
  }
  return null;
}

/**
 * The flag is derived from the ISO code rather than uploaded: two regional
 * indicator letters are the flag emoji for that country, so `MT` renders as
 * the Maltese flag with nothing to upload and nothing to keep in sync.
 */
export function flagEmojiFromIso(iso2: string | null | undefined) {
  const code = iso2?.trim().toUpperCase() ?? '';
  if (!/^[A-Z]{2}$/.test(code)) return '';
  return String.fromCodePoint(
    ...[...code].map((letter) => 0x1f1e6 + letter.charCodeAt(0) - 65),
  );
}
