/**
 * The currency list the Country editor selects from.
 *
 * Currency name, code and symbol used to be three free-text inputs, so
 * nothing stopped "Euro / USD / £" being saved. They are one choice now, and
 * this table is that choice's vocabulary.
 *
 * Generated by scripts/country-table/generate.mjs -- edit that, not this.
 * ISO codes and currencies from world-countries (ISO 3166 / 4217); flag
 * colours measured from the flag-icons SVGs (MIT) by rendering and counting
 * pixels, so a share is the share of the flag a colour covers.
 */

export type CurrencyOption = { code: string; name: string; symbol: string };

export const CURRENCY_OPTIONS: readonly CurrencyOption[] = [];

const BY_CODE = new Map(CURRENCY_OPTIONS.map((row) => [row.code, row]));

export function currencyByCode(code: string | null | undefined) {
  return code ? (BY_CODE.get(code.trim().toUpperCase()) ?? null) : null;
}

/** Matches a stored currency however it was recorded, so legacy rows that hold
 * only a name or only a symbol still select the right option. */
export function matchCurrency(value: {
  code?: string | null;
  name?: string | null;
  symbol?: string | null;
}) {
  const byCode = currencyByCode(value.code);
  if (byCode) return byCode;
  const name = value.name?.trim().toLowerCase();
  if (name) {
    const found = CURRENCY_OPTIONS.find((row) => row.name.toLowerCase() === name);
    if (found) return found;
  }
  const symbol = value.symbol?.trim();
  if (symbol) {
    const matches = CURRENCY_OPTIONS.filter((row) => row.symbol === symbol);
    /* Only when it is unambiguous -- "$" belongs to several currencies, and
     * guessing one would silently rewrite the operator's data. */
    if (matches.length === 1) return matches[0];
  }
  return null;
}

/**
 * The flag is derived from the ISO code rather than uploaded: two regional
 * indicator letters are the flag emoji for that country, so `MT` renders as
 * the Maltese flag with nothing to upload and nothing to keep in sync.
 */
export function flagEmojiFromIso(iso2: string | null | undefined) {
  const code = iso2?.trim().toUpperCase() ?? '';
  if (!/^[A-Z]{2}$/.test(code)) return '';
  return String.fromCodePoint(
    ...[...code].map((letter) => 0x1f1e6 + letter.charCodeAt(0) - 65),
  );
}
