/**
 * Every country this catalogue knows: its codes, its money, its flag.
 *
 * Generated by scripts/country-table/generate.mjs -- edit that, not this.
 * ISO codes and currencies from world-countries (ISO 3166 / 4217); flag
 * colours measured from the flag-icons SVGs (MIT) by rendering and counting
 * pixels, so a share is the share of the flag a colour covers.
 */

export type CountryBand = {
  /** As it appears in the flag. */
  colour: string;
  /** How much of the flag it covers, 0 to 1. */
  share: number;
};

export type CountryTableRow = {
  name: string;
  region: string;
  iso2: string;
  iso3: string;
  currencyCode: string;
  currencyName: string;
  currencySymbol: string;
  /** Most of the flag first. Two colours where the flag has two. */
  bands: readonly CountryBand[];
};

export const COUNTRY_TABLE: readonly CountryTableRow[] = [
  {
    name: 'Andorra',
    region: 'Europe',
    iso2: 'AD',
    iso3: 'AND',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#0018a8',
        share: 0.313,
      },
      {
        colour: '#d0103a',
        share: 0.313,
      },
      {
        colour: '#fedf00',
        share: 0.247,
      },
    ],
  },
  {
    name: 'United Arab Emirates',
    region: 'Middle East',
    iso2: 'AE',
    iso3: 'ARE',
    currencyCode: 'AED',
    currencyName: 'United Arab Emirates dirham',
    currencySymbol: 'د.إ',
    bands: [
      {
        colour: '#ff0000',
        share: 0.338,
      },
      {
        colour: '#00732f',
        share: 0.217,
      },
      {
        colour: '#ffffff',
        share: 0.217,
      },
    ],
  },
  {
    name: 'Afghanistan',
    region: 'Asia',
    iso2: 'AF',
    iso3: 'AFG',
    currencyCode: 'AFN',
    currencyName: 'Afghan afghani',
    currencySymbol: '؋',
    bands: [
      {
        colour: '#000001',
        share: 0.325,
      },
      {
        colour: '#009900',
        share: 0.325,
      },
      {
        colour: '#bf0000',
        share: 0.232,
      },
    ],
  },
  {
    name: 'Antigua and Barbuda',
    region: 'Latin America',
    iso2: 'AG',
    iso3: 'ATG',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ce1126',
        share: 0.483,
      },
      {
        colour: '#000001',
        share: 0.22,
      },
      {
        colour: '#0072c6',
        share: 0.103,
      },
    ],
  },
  {
    name: 'Albania',
    region: 'Europe',
    iso2: 'AL',
    iso3: 'ALB',
    currencyCode: 'ALL',
    currencyName: 'Albanian lek',
    currencySymbol: 'L',
    bands: [
      {
        colour: '#ff0000',
        share: 0.826,
      },
      {
        colour: '#010001',
        share: 0.081,
      },
    ],
  },
  {
    name: 'Armenia',
    region: 'Middle East',
    iso2: 'AM',
    iso3: 'ARM',
    currencyCode: 'AMD',
    currencyName: 'Armenian dram',
    currencySymbol: '֏',
    bands: [
      {
        colour: '#d90012',
        share: 0.333,
      },
      {
        colour: '#0033a0',
        share: 0.333,
      },
      {
        colour: '#f2a800',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Angola',
    region: 'Africa',
    iso2: 'AO',
    iso3: 'AGO',
    currencyCode: 'AOA',
    currencyName: 'Angolan kwanza',
    currencySymbol: 'Kz',
    bands: [
      {
        colour: '#ff0000',
        share: 0.46,
      },
      {
        colour: '#000001',
        share: 0.455,
      },
      {
        colour: '#feeb00',
        share: 0.027,
      },
    ],
  },
  {
    name: 'Argentina',
    region: 'Latin America',
    iso2: 'AR',
    iso3: 'ARG',
    currencyCode: 'ARS',
    currencyName: 'Argentine peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#74acdf',
        share: 0.667,
      },
      {
        colour: '#ffffff',
        share: 0.287,
      },
    ],
  },
  {
    name: 'Austria',
    region: 'Europe',
    iso2: 'AT',
    iso3: 'AUT',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#c8102e',
        share: 0.667,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Australia',
    region: 'Oceania',
    iso2: 'AU',
    iso3: 'AUS',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#00008b',
        share: 0.718,
      },
      {
        colour: '#fefefe',
        share: 0.097,
      },
      {
        colour: '#ff0101',
        share: 0.096,
      },
    ],
  },
  {
    name: 'Aruba',
    region: 'Latin America',
    iso2: 'AW',
    iso3: 'ABW',
    currencyCode: 'AWG',
    currencyName: 'Aruban florin',
    currencySymbol: 'ƒ',
    bands: [
      {
        colour: '#3399cc',
        share: 0.826,
      },
      {
        colour: '#ffff00',
        share: 0.1,
      },
    ],
  },
  {
    name: 'Azerbaijan',
    region: 'Middle East',
    iso2: 'AZ',
    iso3: 'AZE',
    currencyCode: 'AZN',
    currencyName: 'Azerbaijani manat',
    currencySymbol: '₼',
    bands: [
      {
        colour: '#00b9e4',
        share: 0.333,
      },
      {
        colour: '#3f9c35',
        share: 0.333,
      },
      {
        colour: '#ed2939',
        share: 0.296,
      },
    ],
  },
  {
    name: 'Bosnia and Herzegovina',
    region: 'Europe',
    iso2: 'BA',
    iso3: 'BIH',
    currencyCode: 'BAM',
    currencyName: 'Bosnia and Herzegovina convertible mark',
    currencySymbol: 'KM',
    bands: [
      {
        colour: '#000099',
        share: 0.519,
      },
      {
        colour: '#ffcc00',
        share: 0.356,
      },
      {
        colour: '#fefefe',
        share: 0.036,
      },
    ],
  },
  {
    name: 'Barbados',
    region: 'Latin America',
    iso2: 'BB',
    iso3: 'BRB',
    currencyCode: 'BBD',
    currencyName: 'Barbadian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#00267f',
        share: 0.65,
      },
      {
        colour: '#ffc726',
        share: 0.275,
      },
      {
        colour: '#010101',
        share: 0.022,
      },
    ],
  },
  {
    name: 'Bangladesh',
    region: 'Asia',
    iso2: 'BD',
    iso3: 'BGD',
    currencyCode: 'BDT',
    currencyName: 'Bangladeshi taka',
    currencySymbol: '৳',
    bands: [
      {
        colour: '#006a4e',
        share: 0.728,
      },
      {
        colour: '#f42a41',
        share: 0.246,
      },
    ],
  },
  {
    name: 'Belgium',
    region: 'Europe',
    iso2: 'BE',
    iso3: 'BEL',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#000001',
        share: 0.333,
      },
      {
        colour: '#ffd90c',
        share: 0.333,
      },
      {
        colour: '#f31830',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Burkina Faso',
    region: 'Africa',
    iso2: 'BF',
    iso3: 'BFA',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#de0000',
        share: 0.444,
      },
      {
        colour: '#35a100',
        share: 0.425,
      },
      {
        colour: '#fff300',
        share: 0.095,
      },
    ],
  },
  {
    name: 'Bulgaria',
    region: 'Europe',
    iso2: 'BG',
    iso3: 'BGR',
    currencyCode: 'BGN',
    currencyName: 'Bulgarian lev',
    currencySymbol: 'лв',
    bands: [
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#00966e',
        share: 0.333,
      },
      {
        colour: '#d62612',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Bahrain',
    region: 'Middle East',
    iso2: 'BH',
    iso3: 'BHR',
    currencyCode: 'BHD',
    currencyName: 'Bahraini dinar',
    currencySymbol: '.د.ب',
    bands: [
      {
        colour: '#ce1126',
        share: 0.748,
      },
      {
        colour: '#ffffff',
        share: 0.223,
      },
    ],
  },
  {
    name: 'Burundi',
    region: 'Africa',
    iso2: 'BI',
    iso3: 'BDI',
    currencyCode: 'BIF',
    currencyName: 'Burundian franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#ffffff',
        share: 0.378,
      },
      {
        colour: '#cf0921',
        share: 0.336,
      },
      {
        colour: '#18b637',
        share: 0.204,
      },
    ],
  },
  {
    name: 'Benin',
    region: 'Africa',
    iso2: 'BJ',
    iso3: 'BEN',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#319400',
        share: 0.388,
      },
      {
        colour: '#ffd600',
        share: 0.3,
      },
      {
        colour: '#de2110',
        share: 0.294,
      },
    ],
  },
  {
    name: 'Bermuda',
    region: 'Latin America',
    iso2: 'BM',
    iso3: 'BMU',
    currencyCode: 'BMD',
    currencyName: 'Bermudian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ce132b',
        share: 0.716,
      },
      {
        colour: '#fefdfd',
        share: 0.1,
      },
      {
        colour: '#010166',
        share: 0.042,
      },
    ],
  },
  {
    name: 'Brunei',
    region: 'Asia',
    iso2: 'BN',
    iso3: 'BRN',
    currencyCode: 'BND',
    currencyName: 'Brunei dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#f7e017',
        share: 0.517,
      },
      {
        colour: '#ffffff',
        share: 0.177,
      },
      {
        colour: '#000001',
        share: 0.139,
      },
    ],
  },
  {
    name: 'Bolivia',
    region: 'Latin America',
    iso2: 'BO',
    iso3: 'BOL',
    currencyCode: 'BOB',
    currencyName: 'Bolivian boliviano',
    currencySymbol: 'Bs.',
    bands: [
      {
        colour: '#d52b1e',
        share: 0.336,
      },
      {
        colour: '#007934',
        share: 0.335,
      },
      {
        colour: '#ffe000',
        share: 0.279,
      },
    ],
  },
  {
    name: 'Brazil',
    region: 'Latin America',
    iso2: 'BR',
    iso3: 'BRA',
    currencyCode: 'BRL',
    currencyName: 'Brazilian real',
    currencySymbol: 'R$',
    bands: [
      {
        colour: '#229e45',
        share: 0.593,
      },
      {
        colour: '#f8e509',
        share: 0.193,
      },
      {
        colour: '#2b49a3',
        share: 0.118,
      },
    ],
  },
  {
    name: 'Bahamas',
    region: 'Latin America',
    iso2: 'BS',
    iso3: 'BHS',
    currencyCode: 'BSD',
    currencyName: 'Bahamian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#08ced6',
        share: 0.506,
      },
      {
        colour: '#000001',
        share: 0.293,
      },
      {
        colour: '#ffe900',
        share: 0.15,
      },
    ],
  },
  {
    name: 'Bhutan',
    region: 'Asia',
    iso2: 'BT',
    iso3: 'BTN',
    currencyCode: 'BTN',
    currencyName: 'Bhutanese ngultrum',
    currencySymbol: 'Nu.',
    bands: [
      {
        colour: '#ffd520',
        share: 0.39,
      },
      {
        colour: '#ff4e12',
        share: 0.363,
      },
      {
        colour: '#f6f6f5',
        share: 0.072,
      },
    ],
  },
  {
    name: 'Botswana',
    region: 'Africa',
    iso2: 'BW',
    iso3: 'BWA',
    currencyCode: 'BWP',
    currencyName: 'Botswana pula',
    currencySymbol: 'P',
    bands: [
      {
        colour: '#00cbff',
        share: 0.667,
      },
      {
        colour: '#000001',
        share: 0.2,
      },
      {
        colour: '#ffffff',
        share: 0.1,
      },
    ],
  },
  {
    name: 'Belarus',
    region: 'Europe',
    iso2: 'BY',
    iso3: 'BLR',
    currencyCode: 'BYN',
    currencyName: 'Belarusian ruble',
    currencySymbol: 'Br',
    bands: [
      {
        colour: '#ce1720',
        share: 0.592,
      },
      {
        colour: '#007c30',
        share: 0.275,
      },
      {
        colour: '#fffdfe',
        share: 0.021,
      },
    ],
  },
  {
    name: 'Belize',
    region: 'Latin America',
    iso2: 'BZ',
    iso3: 'BLZ',
    currencyCode: 'BZD',
    currencyName: 'Belize dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#003f87',
        share: 0.454,
      },
      {
        colour: '#ce1126',
        share: 0.133,
      },
      {
        colour: '#fdfdfd',
        share: 0.13,
      },
    ],
  },
  {
    name: 'Canada',
    region: 'North America',
    iso2: 'CA',
    iso3: 'CAN',
    currencyCode: 'CAD',
    currencyName: 'Canadian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#d52b1e',
        share: 0.535,
      },
      {
        colour: '#ffffff',
        share: 0.413,
      },
      {
        colour: '#d7392c',
        share: 0.026,
      },
    ],
  },
  {
    name: 'DR Congo',
    region: 'Africa',
    iso2: 'CD',
    iso3: 'COD',
    currencyCode: 'CDF',
    currencyName: 'Congolese franc',
    currencySymbol: 'FC',
    bands: [
      {
        colour: '#007fff',
        share: 0.64,
      },
      {
        colour: '#ce1021',
        share: 0.183,
      },
      {
        colour: '#f7d618',
        share: 0.085,
      },
    ],
  },
  {
    name: 'Central African Republic',
    region: 'Africa',
    iso2: 'CF',
    iso3: 'CAF',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#ffff00',
        share: 0.207,
      },
      {
        colour: '#ffffff',
        share: 0.2,
      },
      {
        colour: '#009a00',
        share: 0.2,
      },
    ],
  },
  {
    name: 'Congo',
    region: 'Africa',
    iso2: 'CG',
    iso3: 'COG',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#ffff00',
        share: 0.358,
      },
      {
        colour: '#00ca00',
        share: 0.309,
      },
      {
        colour: '#ff0000',
        share: 0.309,
      },
    ],
  },
  {
    name: 'Switzerland',
    region: 'Europe',
    iso2: 'CH',
    iso3: 'CHE',
    currencyCode: 'CHF',
    currencyName: 'Swiss franc',
    currencySymbol: 'CHF',
    bands: [
      {
        colour: '#ff0000',
        share: 0.84,
      },
      {
        colour: '#ffffff',
        share: 0.129,
      },
    ],
  },
  {
    name: 'Ivory Coast',
    region: 'Africa',
    iso2: 'CI',
    iso3: 'CIV',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#ff9a00',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#00cd00',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Chile',
    region: 'Latin America',
    iso2: 'CL',
    iso3: 'CHL',
    currencyCode: 'CLP',
    currencyName: 'Chilean peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#d52b1e',
        share: 0.5,
      },
      {
        colour: '#ffffff',
        share: 0.323,
      },
      {
        colour: '#0039a6',
        share: 0.166,
      },
    ],
  },
  {
    name: 'Cameroon',
    region: 'Africa',
    iso2: 'CM',
    iso3: 'CMR',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#fcd116',
        share: 0.34,
      },
      {
        colour: '#007a5e',
        share: 0.333,
      },
      {
        colour: '#ce1126',
        share: 0.315,
      },
    ],
  },
  {
    name: 'China',
    region: 'Asia',
    iso2: 'CN',
    iso3: 'CHN',
    currencyCode: 'CNY',
    currencyName: 'Chinese yuan',
    currencySymbol: '¥',
    bands: [
      {
        colour: '#ee1c25',
        share: 0.956,
      },
    ],
  },
  {
    name: 'Colombia',
    region: 'Latin America',
    iso2: 'CO',
    iso3: 'COL',
    currencyCode: 'COP',
    currencyName: 'Colombian peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ffe800',
        share: 0.5,
      },
      {
        colour: '#00148e',
        share: 0.25,
      },
      {
        colour: '#da0010',
        share: 0.25,
      },
    ],
  },
  {
    name: 'Costa Rica',
    region: 'Latin America',
    iso2: 'CR',
    iso3: 'CRI',
    currencyCode: 'CRC',
    currencyName: 'Costa Rican colón',
    currencySymbol: '₡',
    bands: [
      {
        colour: '#0000b4',
        share: 0.317,
      },
      {
        colour: '#d90000',
        share: 0.317,
      },
      {
        colour: '#ffffff',
        share: 0.3,
      },
    ],
  },
  {
    name: 'Cuba',
    region: 'Latin America',
    iso2: 'CU',
    iso3: 'CUB',
    currencyCode: 'CUC',
    currencyName: 'Cuban convertible peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#002a8f',
        share: 0.413,
      },
      {
        colour: '#cb1515',
        share: 0.284,
      },
      {
        colour: '#ffffff',
        share: 0.256,
      },
    ],
  },
  {
    name: 'Cabo Verde',
    region: 'Africa',
    iso2: 'CV',
    iso3: 'CPV',
    currencyCode: 'CVE',
    currencyName: 'Cape Verdean escudo',
    currencySymbol: 'Esc',
    bands: [
      {
        colour: '#081873',
        share: 0.699,
      },
      {
        colour: '#ffffff',
        share: 0.116,
      },
      {
        colour: '#de3929',
        share: 0.065,
      },
    ],
  },
  {
    name: 'Curacao',
    region: 'Latin America',
    iso2: 'CW',
    iso3: 'CUW',
    currencyCode: 'ANG',
    currencyName: 'Netherlands Antillean guilder',
    currencySymbol: 'ƒ',
    bands: [
      {
        colour: '#002b7f',
        share: 0.843,
      },
      {
        colour: '#f9e814',
        share: 0.117,
      },
    ],
  },
  {
    name: 'Cyprus',
    region: 'Europe',
    iso2: 'CY',
    iso3: 'CYP',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ffffff',
        share: 0.851,
      },
      {
        colour: '#d47600',
        share: 0.087,
      },
    ],
  },
  {
    name: 'Czechia',
    region: 'Europe',
    iso2: 'CZ',
    iso3: 'CZE',
    currencyCode: 'CZK',
    currencyName: 'Czech koruna',
    currencySymbol: 'Kč',
    bands: [
      {
        colour: '#ffffff',
        share: 0.353,
      },
      {
        colour: '#d7141a',
        share: 0.353,
      },
      {
        colour: '#11457e',
        share: 0.269,
      },
    ],
  },
  {
    name: 'Germany',
    region: 'Europe',
    iso2: 'DE',
    iso3: 'DEU',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#000001',
        share: 0.333,
      },
      {
        colour: '#ff0000',
        share: 0.333,
      },
      {
        colour: '#ffcc00',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Djibouti',
    region: 'Africa',
    iso2: 'DJ',
    iso3: 'DJI',
    currencyCode: 'DJF',
    currencyName: 'Djiboutian franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#6699ff',
        share: 0.354,
      },
      {
        colour: '#00cc00',
        share: 0.353,
      },
      {
        colour: '#fffefe',
        share: 0.258,
      },
    ],
  },
  {
    name: 'Denmark',
    region: 'Europe',
    iso2: 'DK',
    iso3: 'DNK',
    currencyCode: 'DKK',
    currencyName: 'Danish krone',
    currencySymbol: 'kr',
    bands: [
      {
        colour: '#c8102e',
        share: 0.729,
      },
      {
        colour: '#ffffff',
        share: 0.22,
      },
    ],
  },
  {
    name: 'Dominica',
    region: 'Latin America',
    iso2: 'DM',
    iso3: 'DMA',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#108c00',
        share: 0.532,
      },
      {
        colour: '#e72910',
        share: 0.095,
      },
      {
        colour: '#ffffff',
        share: 0.081,
      },
    ],
  },
  {
    name: 'Dominican Republic',
    region: 'Latin America',
    iso2: 'DO',
    iso3: 'DOM',
    currencyCode: 'DOP',
    currencyName: 'Dominican peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#002d62',
        share: 0.34,
      },
      {
        colour: '#ce1126',
        share: 0.34,
      },
      {
        colour: '#ffffff',
        share: 0.293,
      },
    ],
  },
  {
    name: 'Algeria',
    region: 'Africa',
    iso2: 'DZ',
    iso3: 'DZA',
    currencyCode: 'DZD',
    currencyName: 'Algerian dinar',
    currencySymbol: 'د.ج',
    bands: [
      {
        colour: '#ffffff',
        share: 0.468,
      },
      {
        colour: '#006233',
        share: 0.45,
      },
      {
        colour: '#d21034',
        share: 0.051,
      },
    ],
  },
  {
    name: 'Ecuador',
    region: 'Latin America',
    iso2: 'EC',
    iso3: 'ECU',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ffe800',
        share: 0.354,
      },
      {
        colour: '#da0010',
        share: 0.214,
      },
      {
        colour: '#00148e',
        share: 0.143,
      },
    ],
  },
  {
    name: 'Estonia',
    region: 'Europe',
    iso2: 'EE',
    iso3: 'EST',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#1791ff',
        share: 0.333,
      },
      {
        colour: '#000001',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Egypt',
    region: 'Africa',
    iso2: 'EG',
    iso3: 'EGY',
    currencyCode: 'EGP',
    currencyName: 'Egyptian pound',
    currencySymbol: '£',
    bands: [
      {
        colour: '#ce1126',
        share: 0.333,
      },
      {
        colour: '#000001',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.287,
      },
    ],
  },
  {
    name: 'Eritrea',
    region: 'Africa',
    iso2: 'ER',
    iso3: 'ERI',
    currencyCode: 'ERN',
    currencyName: 'Eritrean nakfa',
    currencySymbol: 'Nfk',
    bands: [
      {
        colour: '#be0027',
        share: 0.341,
      },
      {
        colour: '#239e46',
        share: 0.242,
      },
      {
        colour: '#b4d7f4',
        share: 0.242,
      },
    ],
  },
  {
    name: 'Spain',
    region: 'Europe',
    iso2: 'ES',
    iso3: 'ESP',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#aa151b',
        share: 0.503,
      },
      {
        colour: '#f1bf00',
        share: 0.411,
      },
    ],
  },
  {
    name: 'Ethiopia',
    region: 'Africa',
    iso2: 'ET',
    iso3: 'ETH',
    currencyCode: 'ETB',
    currencyName: 'Ethiopian birr',
    currencySymbol: 'Br',
    bands: [
      {
        colour: '#298c08',
        share: 0.343,
      },
      {
        colour: '#ef2118',
        share: 0.309,
      },
      {
        colour: '#ffc621',
        share: 0.217,
      },
    ],
  },
  {
    name: 'Finland',
    region: 'Europe',
    iso2: 'FI',
    iso3: 'FIN',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ffffff',
        share: 0.542,
      },
      {
        colour: '#002f6c',
        share: 0.413,
      },
    ],
  },
  {
    name: 'Fiji',
    region: 'Oceania',
    iso2: 'FJ',
    iso3: 'FJI',
    currencyCode: 'FJD',
    currencyName: 'Fijian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#68bfe5',
        share: 0.636,
      },
      {
        colour: '#c8102e',
        share: 0.087,
      },
      {
        colour: '#fdfcfd',
        share: 0.08,
      },
    ],
  },
  {
    name: 'Micronesia',
    region: 'Oceania',
    iso2: 'FM',
    iso3: 'FSM',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#6797d6',
        share: 0.949,
      },
      {
        colour: '#fefeff',
        share: 0.023,
      },
    ],
  },
  {
    name: 'France',
    region: 'Europe',
    iso2: 'FR',
    iso3: 'FRA',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#000091',
        share: 0.325,
      },
      {
        colour: '#ffffff',
        share: 0.325,
      },
      {
        colour: '#e1000f',
        share: 0.325,
      },
    ],
  },
  {
    name: 'Gabon',
    region: 'Africa',
    iso2: 'GA',
    iso3: 'GAB',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#36a100',
        share: 0.333,
      },
      {
        colour: '#ffe700',
        share: 0.333,
      },
      {
        colour: '#006dbc',
        share: 0.333,
      },
    ],
  },
  {
    name: 'UK',
    region: 'Europe',
    iso2: 'GB',
    iso3: 'GBR',
    currencyCode: 'GBP',
    currencyName: 'British pound',
    currencySymbol: '£',
    bands: [
      {
        colour: '#c8102e',
        share: 0.371,
      },
      {
        colour: '#ffffff',
        share: 0.294,
      },
      {
        colour: '#012169',
        share: 0.188,
      },
    ],
  },
  {
    name: 'Grenada',
    region: 'Latin America',
    iso2: 'GD',
    iso3: 'GRD',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ce1126',
        share: 0.39,
      },
      {
        colour: '#fcd116',
        share: 0.248,
      },
      {
        colour: '#007a5e',
        share: 0.233,
      },
    ],
  },
  {
    name: 'Georgia',
    region: 'Middle East',
    iso2: 'GE',
    iso3: 'GEO',
    currencyCode: 'GEL',
    currencyName: 'lari',
    currencySymbol: '₾',
    bands: [
      {
        colour: '#ffffff',
        share: 0.613,
      },
      {
        colour: '#ff0000',
        share: 0.35,
      },
    ],
  },
  {
    name: 'Ghana',
    region: 'Africa',
    iso2: 'GH',
    iso3: 'GHA',
    currencyCode: 'GHS',
    currencyName: 'Ghanaian cedi',
    currencySymbol: '₵',
    bands: [
      {
        colour: '#ce1126',
        share: 0.333,
      },
      {
        colour: '#006b3f',
        share: 0.333,
      },
      {
        colour: '#fcd116',
        share: 0.295,
      },
    ],
  },
  {
    name: 'Greenland',
    region: 'Europe',
    iso2: 'GL',
    iso3: 'GRL',
    currencyCode: 'DKK',
    currencyName: 'krone',
    currencySymbol: 'kr.',
    bands: [
      {
        colour: '#ffffff',
        share: 0.489,
      },
      {
        colour: '#d00c33',
        share: 0.487,
      },
    ],
  },
  {
    name: 'Gambia',
    region: 'Africa',
    iso2: 'GM',
    iso3: 'GMB',
    currencyCode: 'GMD',
    currencyName: 'dalasi',
    currencySymbol: 'D',
    bands: [
      {
        colour: '#000099',
        share: 0.3,
      },
      {
        colour: '#ff0000',
        share: 0.267,
      },
      {
        colour: '#009900',
        share: 0.267,
      },
    ],
  },
  {
    name: 'Guinea',
    region: 'Africa',
    iso2: 'GN',
    iso3: 'GIN',
    currencyCode: 'GNF',
    currencyName: 'Guinean franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#ff0000',
        share: 0.333,
      },
      {
        colour: '#ffff00',
        share: 0.333,
      },
      {
        colour: '#009900',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Equatorial Guinea',
    region: 'Africa',
    iso2: 'GQ',
    iso3: 'GNQ',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#3e9a00',
        share: 0.3,
      },
      {
        colour: '#e32118',
        share: 0.299,
      },
      {
        colour: '#fefefe',
        share: 0.222,
      },
    ],
  },
  {
    name: 'Greece',
    region: 'Europe',
    iso2: 'GR',
    iso3: 'GRC',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#0d5eaf',
        share: 0.516,
      },
      {
        colour: '#ffffff',
        share: 0.39,
      },
      {
        colour: '#1f6ab5',
        share: 0.026,
      },
    ],
  },
  {
    name: 'Guatemala',
    region: 'Latin America',
    iso2: 'GT',
    iso3: 'GTM',
    currencyCode: 'GTQ',
    currencyName: 'Guatemalan quetzal',
    currencySymbol: 'Q',
    bands: [
      {
        colour: '#4997d0',
        share: 0.65,
      },
      {
        colour: '#ffffff',
        share: 0.269,
      },
    ],
  },
  {
    name: 'Guinea-Bissau',
    region: 'Africa',
    iso2: 'GW',
    iso3: 'GNB',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#fcd116',
        share: 0.329,
      },
      {
        colour: '#009e49',
        share: 0.329,
      },
      {
        colour: '#ce1126',
        share: 0.312,
      },
    ],
  },
  {
    name: 'Guyana',
    region: 'Latin America',
    iso2: 'GY',
    iso3: 'GUY',
    currencyCode: 'GYD',
    currencyName: 'Guyanese dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#399408',
        share: 0.498,
      },
      {
        colour: '#de2110',
        share: 0.163,
      },
      {
        colour: '#ffde08',
        share: 0.157,
      },
    ],
  },
  {
    name: 'Hong Kong',
    region: 'Asia',
    iso2: 'HK',
    iso3: 'HKG',
    currencyCode: 'HKD',
    currencyName: 'Hong Kong dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ec1b2e',
        share: 0.873,
      },
      {
        colour: '#fffefe',
        share: 0.067,
      },
    ],
  },
  {
    name: 'Honduras',
    region: 'Latin America',
    iso2: 'HN',
    iso3: 'HND',
    currencyCode: 'HNL',
    currencyName: 'Honduran lempira',
    currencySymbol: 'L',
    bands: [
      {
        colour: '#18c3df',
        share: 0.672,
      },
      {
        colour: '#ffffff',
        share: 0.31,
      },
    ],
  },
  {
    name: 'Croatia',
    region: 'Europe',
    iso2: 'HR',
    iso3: 'HRV',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#171796',
        share: 0.319,
      },
      {
        colour: '#ff0000',
        share: 0.318,
      },
      {
        colour: '#ffffff',
        share: 0.268,
      },
    ],
  },
  {
    name: 'Haiti',
    region: 'Latin America',
    iso2: 'HT',
    iso3: 'HTI',
    currencyCode: 'HTG',
    currencyName: 'Haitian gourde',
    currencySymbol: 'G',
    bands: [
      {
        colour: '#00209f',
        share: 0.467,
      },
      {
        colour: '#d21034',
        share: 0.467,
      },
    ],
  },
  {
    name: 'Hungary',
    region: 'Europe',
    iso2: 'HU',
    iso3: 'HUN',
    currencyCode: 'HUF',
    currencyName: 'Hungarian forint',
    currencySymbol: 'Ft',
    bands: [
      {
        colour: '#d43516',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#388d00',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Indonesia',
    region: 'Asia',
    iso2: 'ID',
    iso3: 'IDN',
    currencyCode: 'IDR',
    currencyName: 'Indonesian rupiah',
    currencySymbol: 'Rp',
    bands: [
      {
        colour: '#e70011',
        share: 0.5,
      },
      {
        colour: '#ffffff',
        share: 0.5,
      },
    ],
  },
  {
    name: 'Ireland',
    region: 'Europe',
    iso2: 'IE',
    iso3: 'IRL',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#009a49',
        share: 0.325,
      },
      {
        colour: '#ffffff',
        share: 0.325,
      },
      {
        colour: '#ff7900',
        share: 0.325,
      },
    ],
  },
  {
    name: 'Israel',
    region: 'Middle East',
    iso2: 'IL',
    iso3: 'ISR',
    currencyCode: 'ILS',
    currencyName: 'Israeli new shekel',
    currencySymbol: '₪',
    bands: [
      {
        colour: '#ffffff',
        share: 0.638,
      },
      {
        colour: '#0038b8',
        share: 0.256,
      },
    ],
  },
  {
    name: 'India',
    region: 'Asia',
    iso2: 'IN',
    iso3: 'IND',
    currencyCode: 'INR',
    currencyName: 'Indian rupee',
    currencySymbol: '₹',
    bands: [
      {
        colour: '#ff9933',
        share: 0.333,
      },
      {
        colour: '#128807',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.291,
      },
    ],
  },
  {
    name: 'Iraq',
    region: 'Middle East',
    iso2: 'IQ',
    iso3: 'IRQ',
    currencyCode: 'IQD',
    currencyName: 'Iraqi dinar',
    currencySymbol: 'ع.د',
    bands: [
      {
        colour: '#ce1126',
        share: 0.333,
      },
      {
        colour: '#000001',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.287,
      },
    ],
  },
  {
    name: 'Iran',
    region: 'Middle East',
    iso2: 'IR',
    iso3: 'IRN',
    currencyCode: 'IRR',
    currencyName: 'Iranian rial',
    currencySymbol: '﷼',
    bands: [
      {
        colour: '#ffffff',
        share: 0.288,
      },
      {
        colour: '#da0000',
        share: 0.275,
      },
      {
        colour: '#239f40',
        share: 0.267,
      },
    ],
  },
  {
    name: 'Iceland',
    region: 'Europe',
    iso2: 'IS',
    iso3: 'ISL',
    currencyCode: 'ISK',
    currencyName: 'Icelandic króna',
    currencySymbol: 'kr',
    bands: [
      {
        colour: '#003897',
        share: 0.632,
      },
      {
        colour: '#d72828',
        share: 0.168,
      },
      {
        colour: '#ffffff',
        share: 0.1,
      },
    ],
  },
  {
    name: 'Italy',
    region: 'Europe',
    iso2: 'IT',
    iso3: 'ITA',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#009246',
        share: 0.325,
      },
      {
        colour: '#ffffff',
        share: 0.325,
      },
      {
        colour: '#ce2b37',
        share: 0.325,
      },
    ],
  },
  {
    name: 'Jamaica',
    region: 'Latin America',
    iso2: 'JM',
    iso3: 'JAM',
    currencyCode: 'JMD',
    currencyName: 'Jamaican dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#000001',
        share: 0.32,
      },
      {
        colour: '#009900',
        share: 0.315,
      },
      {
        colour: '#ffcc00',
        share: 0.305,
      },
    ],
  },
  {
    name: 'Jordan',
    region: 'Middle East',
    iso2: 'JO',
    iso3: 'JOR',
    currencyCode: 'JOD',
    currencyName: 'Jordanian dinar',
    currencySymbol: 'د.ا',
    bands: [
      {
        colour: '#ff0000',
        share: 0.356,
      },
      {
        colour: '#000001',
        share: 0.246,
      },
      {
        colour: '#009900',
        share: 0.246,
      },
    ],
  },
  {
    name: 'Japan',
    region: 'Asia',
    iso2: 'JP',
    iso3: 'JPN',
    currencyCode: 'JPY',
    currencyName: 'Japanese yen',
    currencySymbol: '¥',
    bands: [
      {
        colour: '#ffffff',
        share: 0.761,
      },
      {
        colour: '#bc002d',
        share: 0.215,
      },
    ],
  },
  {
    name: 'Kenya',
    region: 'Africa',
    iso2: 'KE',
    iso3: 'KEN',
    currencyCode: 'KES',
    currencyName: 'Kenyan shilling',
    currencySymbol: 'KSh',
    bands: [
      {
        colour: '#000001',
        share: 0.29,
      },
      {
        colour: '#006600',
        share: 0.283,
      },
      {
        colour: '#bb0000',
        share: 0.28,
      },
    ],
  },
  {
    name: 'Kyrgyzstan',
    region: 'Asia',
    iso2: 'KG',
    iso3: 'KGZ',
    currencyCode: 'KGS',
    currencyName: 'Kyrgyzstani som',
    currencySymbol: 'с',
    bands: [
      {
        colour: '#ff0000',
        share: 0.821,
      },
      {
        colour: '#fffb00',
        share: 0.026,
      },
    ],
  },
  {
    name: 'Cambodia',
    region: 'Asia',
    iso2: 'KH',
    iso3: 'KHM',
    currencyCode: 'KHR',
    currencyName: 'Cambodian riel',
    currencySymbol: '៛',
    bands: [
      {
        colour: '#032ea1',
        share: 0.5,
      },
      {
        colour: '#e00025',
        share: 0.352,
      },
      {
        colour: '#c7c7c7',
        share: 0.032,
      },
    ],
  },
  {
    name: 'Kiribati',
    region: 'Oceania',
    iso2: 'KI',
    iso3: 'KIR',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#e73e2d',
        share: 0.443,
      },
      {
        colour: '#005989',
        share: 0.186,
      },
      {
        colour: '#ffffff',
        share: 0.171,
      },
    ],
  },
  {
    name: 'Comoros',
    region: 'Africa',
    iso2: 'KM',
    iso3: 'COM',
    currencyCode: 'KMF',
    currencyName: 'Comorian franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#239e46',
        share: 0.218,
      },
      {
        colour: '#ffff00',
        share: 0.213,
      },
      {
        colour: '#3b5aa3',
        share: 0.212,
      },
    ],
  },
  {
    name: 'Saint Kitts and Nevis',
    region: 'Latin America',
    iso2: 'KN',
    iso3: 'KNA',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#000001',
        share: 0.305,
      },
      {
        colour: '#c70000',
        share: 0.284,
      },
      {
        colour: '#35a100',
        share: 0.268,
      },
    ],
  },
  {
    name: 'North Korea',
    region: 'Asia',
    iso2: 'KP',
    iso3: 'PRK',
    currencyCode: 'KPW',
    currencyName: 'North Korean won',
    currencySymbol: '₩',
    bands: [
      {
        colour: '#c60000',
        share: 0.428,
      },
      {
        colour: '#3e5698',
        share: 0.367,
      },
      {
        colour: '#ffffff',
        share: 0.144,
      },
    ],
  },
  {
    name: 'South Korea',
    region: 'Asia',
    iso2: 'KR',
    iso3: 'KOR',
    currencyCode: 'KRW',
    currencyName: 'South Korean won',
    currencySymbol: '₩',
    bands: [
      {
        colour: '#ffffff',
        share: 0.716,
      },
      {
        colour: '#0047a0',
        share: 0.064,
      },
      {
        colour: '#cd2e3a',
        share: 0.064,
      },
    ],
  },
  {
    name: 'Kuwait',
    region: 'Middle East',
    iso2: 'KW',
    iso3: 'KWT',
    currencyCode: 'KWD',
    currencyName: 'Kuwaiti dinar',
    currencySymbol: 'د.ك',
    bands: [
      {
        colour: '#00d941',
        share: 0.267,
      },
      {
        colour: '#f31830',
        share: 0.267,
      },
      {
        colour: '#000001',
        share: 0.242,
      },
    ],
  },
  {
    name: 'Cayman Islands',
    region: 'Latin America',
    iso2: 'KY',
    iso3: 'CYM',
    currencyCode: 'KYD',
    currencyName: 'Cayman Islands dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#000066',
        share: 0.563,
      },
      {
        colour: '#c8102e',
        share: 0.088,
      },
      {
        colour: '#fdfdfd',
        share: 0.083,
      },
    ],
  },
  {
    name: 'Kazakhstan',
    region: 'Asia',
    iso2: 'KZ',
    iso3: 'KAZ',
    currencyCode: 'KZT',
    currencyName: 'Kazakhstani tenge',
    currencySymbol: '₸',
    bands: [
      {
        colour: '#00abc2',
        share: 0.775,
      },
      {
        colour: '#ffec2d',
        share: 0.04,
      },
    ],
  },
  {
    name: 'Laos',
    region: 'Asia',
    iso2: 'LA',
    iso3: 'LAO',
    currencyCode: 'LAK',
    currencyName: 'Lao kip',
    currencySymbol: '₭',
    bands: [
      {
        colour: '#ce1126',
        share: 0.5,
      },
      {
        colour: '#002868',
        share: 0.383,
      },
      {
        colour: '#ffffff',
        share: 0.102,
      },
    ],
  },
  {
    name: 'Lebanon',
    region: 'Middle East',
    iso2: 'LB',
    iso3: 'LBN',
    currencyCode: 'LBP',
    currencyName: 'Lebanese pound',
    currencySymbol: 'ل.ل',
    bands: [
      {
        colour: '#ee161f',
        share: 0.5,
      },
      {
        colour: '#ffffff',
        share: 0.384,
      },
      {
        colour: '#01a851',
        share: 0.063,
      },
    ],
  },
  {
    name: 'Saint Lucia',
    region: 'Latin America',
    iso2: 'LC',
    iso3: 'LCA',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#65cfff',
        share: 0.779,
      },
      {
        colour: '#ffce00',
        share: 0.092,
      },
      {
        colour: '#000001',
        share: 0.044,
      },
    ],
  },
  {
    name: 'Liechtenstein',
    region: 'Europe',
    iso2: 'LI',
    iso3: 'LIE',
    currencyCode: 'CHF',
    currencyName: 'Swiss franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#ce1126',
        share: 0.5,
      },
      {
        colour: '#002b7f',
        share: 0.446,
      },
    ],
  },
  {
    name: 'Sri Lanka',
    region: 'Asia',
    iso2: 'LK',
    iso3: 'LKA',
    currencyCode: 'LKR',
    currencyName: 'Sri Lankan rupee',
    currencySymbol: 'Rs',
    bands: [
      {
        colour: '#8d2029',
        share: 0.371,
      },
      {
        colour: '#ffb700',
        share: 0.239,
      },
      {
        colour: '#005641',
        share: 0.108,
      },
    ],
  },
  {
    name: 'Liberia',
    region: 'Africa',
    iso2: 'LR',
    iso3: 'LBR',
    currencyCode: 'LRD',
    currencyName: 'Liberian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#cc0000',
        share: 0.412,
      },
      {
        colour: '#ffffff',
        share: 0.328,
      },
      {
        colour: '#000066',
        share: 0.126,
      },
    ],
  },
  {
    name: 'Lesotho',
    region: 'Africa',
    iso2: 'LS',
    iso3: 'LSO',
    currencyCode: 'LSL',
    currencyName: 'Lesotho loti',
    currencySymbol: 'L',
    bands: [
      {
        colour: '#ffffff',
        share: 0.351,
      },
      {
        colour: '#00209f',
        share: 0.3,
      },
      {
        colour: '#009543',
        share: 0.3,
      },
    ],
  },
  {
    name: 'Lithuania',
    region: 'Europe',
    iso2: 'LT',
    iso3: 'LTU',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#fdb913',
        share: 0.333,
      },
      {
        colour: '#006a44',
        share: 0.333,
      },
      {
        colour: '#c1272d',
        share: 0.317,
      },
    ],
  },
  {
    name: 'Luxembourg',
    region: 'Europe',
    iso2: 'LU',
    iso3: 'LUX',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ed2939',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#00a1de',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Latvia',
    region: 'Europe',
    iso2: 'LV',
    iso3: 'LVA',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#981e32',
        share: 0.8,
      },
      {
        colour: '#ffffff',
        share: 0.2,
      },
    ],
  },
  {
    name: 'Libya',
    region: 'Africa',
    iso2: 'LY',
    iso3: 'LBY',
    currencyCode: 'LYD',
    currencyName: 'Libyan dinar',
    currencySymbol: 'ل.د',
    bands: [
      {
        colour: '#000001',
        share: 0.474,
      },
      {
        colour: '#e70013',
        share: 0.25,
      },
      {
        colour: '#239e46',
        share: 0.25,
      },
    ],
  },
  {
    name: 'Morocco',
    region: 'Africa',
    iso2: 'MA',
    iso3: 'MAR',
    currencyCode: 'MAD',
    currencyName: 'Moroccan dirham',
    currencySymbol: 'د.م.',
    bands: [
      {
        colour: '#c1272d',
        share: 0.971,
      },
    ],
  },
  {
    name: 'Monaco',
    region: 'Europe',
    iso2: 'MC',
    iso3: 'MCO',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#f31830',
        share: 0.5,
      },
      {
        colour: '#ffffff',
        share: 0.5,
      },
    ],
  },
  {
    name: 'Moldova',
    region: 'Europe',
    iso2: 'MD',
    iso3: 'MDA',
    currencyCode: 'MDL',
    currencyName: 'Moldovan leu',
    currencySymbol: 'L',
    bands: [
      {
        colour: '#de2110',
        share: 0.312,
      },
      {
        colour: '#00319c',
        share: 0.307,
      },
      {
        colour: '#ffde00',
        share: 0.162,
      },
    ],
  },
  {
    name: 'Montenegro',
    region: 'Europe',
    iso2: 'ME',
    iso3: 'MNE',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#c40308',
        share: 0.664,
      },
      {
        colour: '#d3ae3b',
        share: 0.19,
      },
    ],
  },
  {
    name: 'Madagascar',
    region: 'Africa',
    iso2: 'MG',
    iso3: 'MDG',
    currencyCode: 'MGA',
    currencyName: 'Malagasy ariary',
    currencySymbol: 'Ar',
    bands: [
      {
        colour: '#fc3d32',
        share: 0.335,
      },
      {
        colour: '#007e3a',
        share: 0.335,
      },
      {
        colour: '#ffffff',
        share: 0.329,
      },
    ],
  },
  {
    name: 'Marshall Islands',
    region: 'Oceania',
    iso2: 'MH',
    iso3: 'MHL',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#3b5aa3',
        share: 0.64,
      },
      {
        colour: '#fefeff',
        share: 0.153,
      },
      {
        colour: '#e2ae57',
        share: 0.077,
      },
    ],
  },
  {
    name: 'North Macedonia',
    region: 'Europe',
    iso2: 'MK',
    iso3: 'MKD',
    currencyCode: 'MKD',
    currencyName: 'denar',
    currencySymbol: 'den',
    bands: [
      {
        colour: '#d20000',
        share: 0.61,
      },
      {
        colour: '#ffe600',
        share: 0.277,
      },
    ],
  },
  {
    name: 'Mali',
    region: 'Africa',
    iso2: 'ML',
    iso3: 'MLI',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#009a00',
        share: 0.329,
      },
      {
        colour: '#ffff00',
        share: 0.329,
      },
      {
        colour: '#ff0000',
        share: 0.329,
      },
    ],
  },
  {
    name: 'Myanmar',
    region: 'Asia',
    iso2: 'MM',
    iso3: 'MMR',
    currencyCode: 'MMK',
    currencyName: 'Burmese kyat',
    currencySymbol: 'Ks',
    bands: [
      {
        colour: '#fecb00',
        share: 0.325,
      },
      {
        colour: '#ea2839',
        share: 0.308,
      },
      {
        colour: '#34b233',
        share: 0.243,
      },
    ],
  },
  {
    name: 'Mongolia',
    region: 'Asia',
    iso2: 'MN',
    iso3: 'MNG',
    currencyCode: 'MNT',
    currencyName: 'Mongolian tögrög',
    currencySymbol: '₮',
    bands: [
      {
        colour: '#da2032',
        share: 0.537,
      },
      {
        colour: '#0066b3',
        share: 0.325,
      },
      {
        colour: '#ffd900',
        share: 0.05,
      },
    ],
  },
  {
    name: 'Macau',
    region: 'Asia',
    iso2: 'MO',
    iso3: 'MAC',
    currencyCode: 'MOP',
    currencyName: 'Macanese pataca',
    currencySymbol: 'P',
    bands: [
      {
        colour: '#00785e',
        share: 0.872,
      },
      {
        colour: '#fefffe',
        share: 0.048,
      },
    ],
  },
  {
    name: 'Mauritania',
    region: 'Africa',
    iso2: 'MR',
    iso3: 'MRT',
    currencyCode: 'MRU',
    currencyName: 'Mauritanian ouguiya',
    currencySymbol: 'UM',
    bands: [
      {
        colour: '#006233',
        share: 0.622,
      },
      {
        colour: '#cd2a3e',
        share: 0.3,
      },
      {
        colour: '#ffc400',
        share: 0.044,
      },
    ],
  },
  {
    name: 'Malta',
    region: 'Europe',
    iso2: 'MT',
    iso3: 'MLT',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#cf142b',
        share: 0.5,
      },
      {
        colour: '#ffffff',
        share: 0.434,
      },
    ],
  },
  {
    name: 'Mauritius',
    region: 'Africa',
    iso2: 'MU',
    iso3: 'MUS',
    currencyCode: 'MUR',
    currencyName: 'Mauritian rupee',
    currencySymbol: '₨',
    bands: [
      {
        colour: '#ee2737',
        share: 0.25,
      },
      {
        colour: '#151f6d',
        share: 0.25,
      },
      {
        colour: '#ffcd00',
        share: 0.25,
      },
    ],
  },
  {
    name: 'Maldives',
    region: 'Asia',
    iso2: 'MV',
    iso3: 'MDV',
    currencyCode: 'MVR',
    currencyName: 'Maldivian rufiyaa',
    currencySymbol: '.ރ',
    bands: [
      {
        colour: '#d21034',
        share: 0.688,
      },
      {
        colour: '#007e3a',
        share: 0.29,
      },
    ],
  },
  {
    name: 'Malawi',
    region: 'Africa',
    iso2: 'MW',
    iso3: 'MWI',
    currencyCode: 'MWK',
    currencyName: 'Malawian kwacha',
    currencySymbol: 'MK',
    bands: [
      {
        colour: '#f41408',
        share: 0.355,
      },
      {
        colour: '#21873b',
        share: 0.333,
      },
      {
        colour: '#000001',
        share: 0.23,
      },
    ],
  },
  {
    name: 'Mexico',
    region: 'Latin America',
    iso2: 'MX',
    iso3: 'MEX',
    currencyCode: 'MXN',
    currencyName: 'Mexican peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#006847',
        share: 0.333,
      },
      {
        colour: '#ce1126',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.281,
      },
    ],
  },
  {
    name: 'Malaysia',
    region: 'Asia',
    iso2: 'MY',
    iso3: 'MYS',
    currencyCode: 'MYR',
    currencyName: 'Malaysian ringgit',
    currencySymbol: 'RM',
    bands: [
      {
        colour: '#cc0000',
        share: 0.283,
      },
      {
        colour: '#ffffff',
        share: 0.283,
      },
      {
        colour: '#000066',
        share: 0.228,
      },
    ],
  },
  {
    name: 'Mozambique',
    region: 'Africa',
    iso2: 'MZ',
    iso3: 'MOZ',
    currencyCode: 'MZN',
    currencyName: 'Mozambican metical',
    currencySymbol: 'MT',
    bands: [
      {
        colour: '#ffca00',
        share: 0.26,
      },
      {
        colour: '#009a00',
        share: 0.256,
      },
      {
        colour: '#ff0000',
        share: 0.199,
      },
    ],
  },
  {
    name: 'Namibia',
    region: 'Africa',
    iso2: 'NA',
    iso3: 'NAM',
    currencyCode: 'NAD',
    currencyName: 'Namibian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#c70000',
        share: 0.338,
      },
      {
        colour: '#38a100',
        share: 0.281,
      },
      {
        colour: '#3662a2',
        share: 0.225,
      },
    ],
  },
  {
    name: 'New Caledonia',
    region: 'Oceania',
    iso2: 'NC',
    iso3: 'NCL',
    currencyCode: 'XPF',
    currencyName: 'CFP franc',
    currencySymbol: '₣',
    bands: [
      {
        colour: '#0035ad',
        share: 0.279,
      },
      {
        colour: '#009543',
        share: 0.278,
      },
      {
        colour: '#fae600',
        share: 0.175,
      },
    ],
  },
  {
    name: 'Niger',
    region: 'Africa',
    iso2: 'NE',
    iso3: 'NER',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#e05206',
        share: 0.375,
      },
      {
        colour: '#0db02b',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.281,
      },
    ],
  },
  {
    name: 'Nigeria',
    region: 'Africa',
    iso2: 'NG',
    iso3: 'NGA',
    currencyCode: 'NGN',
    currencyName: 'Nigerian naira',
    currencySymbol: '₦',
    bands: [
      {
        colour: '#008753',
        share: 0.65,
      },
      {
        colour: '#ffffff',
        share: 0.325,
      },
    ],
  },
  {
    name: 'Nicaragua',
    region: 'Latin America',
    iso2: 'NI',
    iso3: 'NIC',
    currencyCode: 'NIO',
    currencyName: 'Nicaraguan córdoba',
    currencySymbol: 'C$',
    bands: [
      {
        colour: '#0067c6',
        share: 0.667,
      },
      {
        colour: '#ffffff',
        share: 0.302,
      },
    ],
  },
  {
    name: 'Netherlands',
    region: 'Europe',
    iso2: 'NL',
    iso3: 'NLD',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ae1c28',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#21468b',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Norway',
    region: 'Europe',
    iso2: 'NO',
    iso3: 'NOR',
    currencyCode: 'NOK',
    currencyName: 'Norwegian krone',
    currencySymbol: 'kr',
    bands: [
      {
        colour: '#ed2939',
        share: 0.587,
      },
      {
        colour: '#002664',
        share: 0.168,
      },
      {
        colour: '#ffffff',
        share: 0.147,
      },
    ],
  },
  {
    name: 'Nepal',
    region: 'Asia',
    iso2: 'NP',
    iso3: 'NPL',
    currencyCode: 'NPR',
    currencyName: 'Nepalese rupee',
    currencySymbol: 'Rs',
    bands: [
      {
        colour: '#ce0000',
        share: 0.572,
      },
      {
        colour: '#000063',
        share: 0.132,
      },
      {
        colour: '#fffefe',
        share: 0.111,
      },
    ],
  },
  {
    name: 'Nauru',
    region: 'Oceania',
    iso2: 'NR',
    iso3: 'NRU',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#002170',
        share: 0.855,
      },
      {
        colour: '#ffb20d',
        share: 0.067,
      },
      {
        colour: '#ffffff',
        share: 0.024,
      },
    ],
  },
  {
    name: 'New Zealand',
    region: 'Oceania',
    iso2: 'NZ',
    iso3: 'NZL',
    currencyCode: 'NZD',
    currencyName: 'New Zealand dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#00247d',
        share: 0.725,
      },
      {
        colour: '#c8102e',
        share: 0.088,
      },
      {
        colour: '#fefdfd',
        share: 0.071,
      },
    ],
  },
  {
    name: 'Oman',
    region: 'Middle East',
    iso2: 'OM',
    iso3: 'OMN',
    currencyCode: 'OMR',
    currencyName: 'Omani rial',
    currencySymbol: '﷼',
    bands: [
      {
        colour: '#ef2d29',
        share: 0.466,
      },
      {
        colour: '#009025',
        share: 0.242,
      },
      {
        colour: '#ffffff',
        share: 0.232,
      },
    ],
  },
  {
    name: 'Panama',
    region: 'Latin America',
    iso2: 'PA',
    iso3: 'PAN',
    currencyCode: 'PAB',
    currencyName: 'Panamanian balboa',
    currencySymbol: 'B/.',
    bands: [
      {
        colour: '#ffffff',
        share: 0.438,
      },
      {
        colour: '#0000ab',
        share: 0.265,
      },
      {
        colour: '#db0000',
        share: 0.232,
      },
    ],
  },
  {
    name: 'Peru',
    region: 'Latin America',
    iso2: 'PE',
    iso3: 'PER',
    currencyCode: 'PEN',
    currencyName: 'Peruvian sol',
    currencySymbol: 'S/',
    bands: [
      {
        colour: '#d91023',
        share: 0.65,
      },
      {
        colour: '#ffffff',
        share: 0.325,
      },
    ],
  },
  {
    name: 'Papua New Guinea',
    region: 'Oceania',
    iso2: 'PG',
    iso3: 'PNG',
    currencyCode: 'PGK',
    currencyName: 'Papua New Guinean kina',
    currencySymbol: 'K',
    bands: [
      {
        colour: '#000001',
        share: 0.47,
      },
      {
        colour: '#ff0000',
        share: 0.419,
      },
      {
        colour: '#ffcc00',
        share: 0.046,
      },
    ],
  },
  {
    name: 'Philippines',
    region: 'Asia',
    iso2: 'PH',
    iso3: 'PHL',
    currencyCode: 'PHP',
    currencyName: 'Philippine peso',
    currencySymbol: '₱',
    bands: [
      {
        colour: '#0038a8',
        share: 0.332,
      },
      {
        colour: '#ce1126',
        share: 0.332,
      },
      {
        colour: '#ffffff',
        share: 0.233,
      },
    ],
  },
  {
    name: 'Pakistan',
    region: 'Asia',
    iso2: 'PK',
    iso3: 'PAK',
    currencyCode: 'PKR',
    currencyName: 'Pakistani rupee',
    currencySymbol: '₨',
    bands: [
      {
        colour: '#0c590b',
        share: 0.714,
      },
      {
        colour: '#ffffff',
        share: 0.248,
      },
    ],
  },
  {
    name: 'Poland',
    region: 'Europe',
    iso2: 'PL',
    iso3: 'POL',
    currencyCode: 'PLN',
    currencyName: 'Polish złoty',
    currencySymbol: 'zł',
    bands: [
      {
        colour: '#ffffff',
        share: 0.5,
      },
      {
        colour: '#dc143c',
        share: 0.5,
      },
    ],
  },
  {
    name: 'Puerto Rico',
    region: 'Latin America',
    iso2: 'PR',
    iso3: 'PRI',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ed0000',
        share: 0.425,
      },
      {
        colour: '#0050f0',
        share: 0.282,
      },
      {
        colour: '#ffffff',
        share: 0.257,
      },
    ],
  },
  {
    name: 'Palestine',
    region: 'Middle East',
    iso2: 'PS',
    iso3: 'PSE',
    currencyCode: 'EGP',
    currencyName: 'Egyptian pound',
    currencySymbol: 'E£',
    bands: [
      {
        colour: '#000000',
        share: 0.275,
      },
      {
        colour: '#009639',
        share: 0.275,
      },
      {
        colour: '#ed2e38',
        share: 0.239,
      },
    ],
  },
  {
    name: 'Portugal',
    region: 'Europe',
    iso2: 'PT',
    iso3: 'PRT',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ff0000',
        share: 0.551,
      },
      {
        colour: '#006600',
        share: 0.34,
      },
    ],
  },
  {
    name: 'Palau',
    region: 'Oceania',
    iso2: 'PW',
    iso3: 'PLW',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#4aadd6',
        share: 0.803,
      },
      {
        colour: '#ffde00',
        share: 0.176,
      },
    ],
  },
  {
    name: 'Paraguay',
    region: 'Latin America',
    iso2: 'PY',
    iso3: 'PRY',
    currencyCode: 'PYG',
    currencyName: 'Paraguayan guaraní',
    currencySymbol: '₲',
    bands: [
      {
        colour: '#d52b1e',
        share: 0.333,
      },
      {
        colour: '#0038a8',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.298,
      },
    ],
  },
  {
    name: 'Qatar',
    region: 'Middle East',
    iso2: 'QA',
    iso3: 'QAT',
    currencyCode: 'QAR',
    currencyName: 'Qatari riyal',
    currencySymbol: '﷼',
    bands: [
      {
        colour: '#8d1b3d',
        share: 0.654,
      },
      {
        colour: '#ffffff',
        share: 0.306,
      },
    ],
  },
  {
    name: 'Romania',
    region: 'Europe',
    iso2: 'RO',
    iso3: 'ROU',
    currencyCode: 'RON',
    currencyName: 'Romanian leu',
    currencySymbol: 'lei',
    bands: [
      {
        colour: '#00319c',
        share: 0.333,
      },
      {
        colour: '#ffde00',
        share: 0.333,
      },
      {
        colour: '#de2110',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Serbia',
    region: 'Europe',
    iso2: 'RS',
    iso3: 'SRB',
    currencyCode: 'RSD',
    currencyName: 'Serbian dinar',
    currencySymbol: 'дин',
    bands: [
      {
        colour: '#ffffff',
        share: 0.309,
      },
      {
        colour: '#c6363c',
        share: 0.3,
      },
      {
        colour: '#0c4076',
        share: 0.233,
      },
    ],
  },
  {
    name: 'Russia',
    region: 'Europe',
    iso2: 'RU',
    iso3: 'RUS',
    currencyCode: 'RUB',
    currencyName: 'Russian ruble',
    currencySymbol: '₽',
    bands: [
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#0039a6',
        share: 0.333,
      },
      {
        colour: '#d52b1e',
        share: 0.333,
      },
    ],
  },
  {
    name: 'Rwanda',
    region: 'Africa',
    iso2: 'RW',
    iso3: 'RWA',
    currencyCode: 'RWF',
    currencyName: 'Rwandan franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#00a1de',
        share: 0.46,
      },
      {
        colour: '#fad201',
        share: 0.25,
      },
      {
        colour: '#20603d',
        share: 0.25,
      },
    ],
  },
  {
    name: 'Saudi Arabia',
    region: 'Middle East',
    iso2: 'SA',
    iso3: 'SAU',
    currencyCode: 'SAR',
    currencyName: 'Saudi riyal',
    currencySymbol: '﷼',
    bands: [
      {
        colour: '#165d31',
        share: 0.854,
      },
      {
        colour: '#fbfcfb',
        share: 0.02,
      },
    ],
  },
  {
    name: 'Solomon Islands',
    region: 'Oceania',
    iso2: 'SB',
    iso3: 'SLB',
    currencyCode: 'SBD',
    currencyName: 'Solomon Islands dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#0000d6',
        share: 0.546,
      },
      {
        colour: '#006000',
        share: 0.278,
      },
      {
        colour: '#fecc00',
        share: 0.085,
      },
    ],
  },
  {
    name: 'Seychelles',
    region: 'Africa',
    iso2: 'SC',
    iso3: 'SYC',
    currencyCode: 'SCR',
    currencyName: 'Seychellois rupee',
    currencySymbol: '₨',
    bands: [
      {
        colour: '#d92223',
        share: 0.318,
      },
      {
        colour: '#003d88',
        share: 0.16,
      },
      {
        colour: '#007a39',
        share: 0.158,
      },
    ],
  },
  {
    name: 'Sudan',
    region: 'Africa',
    iso2: 'SD',
    iso3: 'SDN',
    currencyCode: 'SDG',
    currencyName: 'Sudanese pound',
    currencySymbol: 'PT',
    bands: [
      {
        colour: '#ff0000',
        share: 0.275,
      },
      {
        colour: '#000001',
        share: 0.275,
      },
      {
        colour: '#009a00',
        share: 0.242,
      },
    ],
  },
  {
    name: 'Sweden',
    region: 'Europe',
    iso2: 'SE',
    iso3: 'SWE',
    currencyCode: 'SEK',
    currencyName: 'Swedish krona',
    currencySymbol: 'kr',
    bands: [
      {
        colour: '#005293',
        share: 0.68,
      },
      {
        colour: '#fecb00',
        share: 0.32,
      },
    ],
  },
  {
    name: 'Singapore',
    region: 'Asia',
    iso2: 'SG',
    iso3: 'SGP',
    currencyCode: 'SGD',
    currencyName: 'Singapore dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ffffff',
        share: 0.521,
      },
      {
        colour: '#df0000',
        share: 0.451,
      },
    ],
  },
  {
    name: 'Slovenia',
    region: 'Europe',
    iso2: 'SI',
    iso3: 'SVN',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#d50000',
        share: 0.333,
      },
      {
        colour: '#0000bf',
        share: 0.331,
      },
      {
        colour: '#ffffff',
        share: 0.305,
      },
    ],
  },
  {
    name: 'Slovakia',
    region: 'Europe',
    iso2: 'SK',
    iso3: 'SVK',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ee1c25',
        share: 0.379,
      },
      {
        colour: '#ffffff',
        share: 0.327,
      },
      {
        colour: '#0b4ea2',
        share: 0.249,
      },
    ],
  },
  {
    name: 'Sierra Leone',
    region: 'Africa',
    iso2: 'SL',
    iso3: 'SLE',
    currencyCode: 'SLL',
    currencyName: 'Sierra Leonean leone',
    currencySymbol: 'Le',
    bands: [
      {
        colour: '#00cd00',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#0000cd',
        share: 0.333,
      },
    ],
  },
  {
    name: 'San Marino',
    region: 'Europe',
    iso2: 'SM',
    iso3: 'SMR',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ffffff',
        share: 0.434,
      },
      {
        colour: '#19b6ef',
        share: 0.4,
      },
    ],
  },
  {
    name: 'Senegal',
    region: 'Africa',
    iso2: 'SN',
    iso3: 'SEN',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#0b7226',
        share: 0.361,
      },
      {
        colour: '#bc0000',
        share: 0.333,
      },
      {
        colour: '#ffff00',
        share: 0.288,
      },
    ],
  },
  {
    name: 'Somalia',
    region: 'Africa',
    iso2: 'SO',
    iso3: 'SOM',
    currencyCode: 'SOS',
    currencyName: 'Somali shilling',
    currencySymbol: 'Sh',
    bands: [
      {
        colour: '#40a6ff',
        share: 0.935,
      },
      {
        colour: '#ffffff',
        share: 0.05,
      },
    ],
  },
  {
    name: 'Suriname',
    region: 'Latin America',
    iso2: 'SR',
    iso3: 'SUR',
    currencyCode: 'SRD',
    currencyName: 'Surinamese dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#377e3f',
        share: 0.4,
      },
      {
        colour: '#b40a2d',
        share: 0.357,
      },
      {
        colour: '#ffffff',
        share: 0.2,
      },
    ],
  },
  {
    name: 'South Sudan',
    region: 'Africa',
    iso2: 'SS',
    iso3: 'SSD',
    currencyCode: 'SSP',
    currencyName: 'South Sudanese pound',
    currencySymbol: '£',
    bands: [
      {
        colour: '#0f47af',
        share: 0.284,
      },
      {
        colour: '#078930',
        share: 0.239,
      },
      {
        colour: '#000001',
        share: 0.239,
      },
    ],
  },
  {
    name: 'Sao Tome and Principe',
    region: 'Africa',
    iso2: 'ST',
    iso3: 'STP',
    currencyCode: 'STN',
    currencyName: 'São Tomé and Príncipe dobra',
    currencySymbol: 'Db',
    bands: [
      {
        colour: '#12ad2b',
        share: 0.503,
      },
      {
        colour: '#ffce00',
        share: 0.246,
      },
      {
        colour: '#d21034',
        share: 0.181,
      },
    ],
  },
  {
    name: 'El Salvador',
    region: 'Latin America',
    iso2: 'SV',
    iso3: 'SLV',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#0f47af',
        share: 0.667,
      },
      {
        colour: '#ffffff',
        share: 0.284,
      },
    ],
  },
  {
    name: 'Syria',
    region: 'Middle East',
    iso2: 'SY',
    iso3: 'SYR',
    currencyCode: 'SYP',
    currencyName: 'Syrian pound',
    currencySymbol: '£',
    bands: [
      {
        colour: '#007a3d',
        share: 0.333,
      },
      {
        colour: '#000000',
        share: 0.333,
      },
      {
        colour: '#ffffff',
        share: 0.27,
      },
    ],
  },
  {
    name: 'Eswatini',
    region: 'Africa',
    iso2: 'SZ',
    iso3: 'SWZ',
    currencyCode: 'SZL',
    currencyName: 'Swazi lilangeni',
    currencySymbol: 'L',
    bands: [
      {
        colour: '#3e5eb9',
        share: 0.367,
      },
      {
        colour: '#b10c0c',
        share: 0.262,
      },
      {
        colour: '#ffd900',
        share: 0.1,
      },
    ],
  },
  {
    name: 'Chad',
    region: 'Africa',
    iso2: 'TD',
    iso3: 'TCD',
    currencyCode: 'XAF',
    currencyName: 'Central African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#002664',
        share: 0.325,
      },
      {
        colour: '#fecb00',
        share: 0.325,
      },
      {
        colour: '#c60c30',
        share: 0.325,
      },
    ],
  },
  {
    name: 'Togo',
    region: 'Africa',
    iso2: 'TG',
    iso3: 'TGO',
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencySymbol: 'Fr',
    bands: [
      {
        colour: '#118600',
        share: 0.411,
      },
      {
        colour: '#ffe300',
        share: 0.293,
      },
      {
        colour: '#d80000',
        share: 0.236,
      },
    ],
  },
  {
    name: 'Thailand',
    region: 'Asia',
    iso2: 'TH',
    iso3: 'THA',
    currencyCode: 'THB',
    currencyName: 'Thai baht',
    currencySymbol: '฿',
    bands: [
      {
        colour: '#a51931',
        share: 0.333,
      },
      {
        colour: '#2d2a4a',
        share: 0.317,
      },
      {
        colour: '#f4f5f8',
        share: 0.3,
      },
    ],
  },
  {
    name: 'Tajikistan',
    region: 'Asia',
    iso2: 'TJ',
    iso3: 'TJK',
    currencyCode: 'TJS',
    currencyName: 'Tajikistani somoni',
    currencySymbol: 'ЅМ',
    bands: [
      {
        colour: '#ffffff',
        share: 0.355,
      },
      {
        colour: '#cc0000',
        share: 0.283,
      },
      {
        colour: '#006600',
        share: 0.283,
      },
    ],
  },
  {
    name: 'Timor-Leste',
    region: 'Asia',
    iso2: 'TL',
    iso3: 'TLS',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#cb000f',
        share: 0.613,
      },
      {
        colour: '#000001',
        share: 0.212,
      },
      {
        colour: '#f8c00c',
        share: 0.101,
      },
    ],
  },
  {
    name: 'Turkmenistan',
    region: 'Asia',
    iso2: 'TM',
    iso3: 'TKM',
    currencyCode: 'TMT',
    currencyName: 'Turkmenistan manat',
    currencySymbol: 'm',
    bands: [
      {
        colour: '#00843d',
        share: 0.768,
      },
      {
        colour: '#d22630',
        share: 0.029,
      },
    ],
  },
  {
    name: 'Tunisia',
    region: 'Africa',
    iso2: 'TN',
    iso3: 'TUN',
    currencyCode: 'TND',
    currencyName: 'Tunisian dinar',
    currencySymbol: 'د.ت',
    bands: [
      {
        colour: '#e70013',
        share: 0.878,
      },
      {
        colour: '#ffffff',
        share: 0.08,
      },
    ],
  },
  {
    name: 'Tonga',
    region: 'Oceania',
    iso2: 'TO',
    iso3: 'TON',
    currencyCode: 'TOP',
    currencyName: 'Tongan paʻanga',
    currencySymbol: 'T$',
    bands: [
      {
        colour: '#c10000',
        share: 0.859,
      },
      {
        colour: '#ffffff',
        share: 0.123,
      },
    ],
  },
  {
    name: 'Turkey',
    region: 'Middle East',
    iso2: 'TR',
    iso3: 'TUR',
    currencyCode: 'TRY',
    currencyName: 'Turkish lira',
    currencySymbol: '₺',
    bands: [
      {
        colour: '#e30a17',
        share: 0.909,
      },
      {
        colour: '#fffefe',
        share: 0.053,
      },
    ],
  },
  {
    name: 'Trinidad and Tobago',
    region: 'Latin America',
    iso2: 'TT',
    iso3: 'TTO',
    currencyCode: 'TTD',
    currencyName: 'Trinidad and Tobago dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#e00000',
        share: 0.708,
      },
      {
        colour: '#000001',
        share: 0.173,
      },
      {
        colour: '#fefdfd',
        share: 0.059,
      },
    ],
  },
  {
    name: 'Tuvalu',
    region: 'Oceania',
    iso2: 'TV',
    iso3: 'TUV',
    currencyCode: 'AUD',
    currencyName: 'Australian dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#009fca',
        share: 0.675,
      },
      {
        colour: '#c8102e',
        share: 0.087,
      },
      {
        colour: '#fefdfd',
        share: 0.071,
      },
    ],
  },
  {
    name: 'Taiwan',
    region: 'Asia',
    iso2: 'TW',
    iso3: 'TWN',
    currencyCode: 'TWD',
    currencyName: 'New Taiwan dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ff0000',
        share: 0.719,
      },
      {
        colour: '#000095',
        share: 0.226,
      },
      {
        colour: '#fefefe',
        share: 0.023,
      },
    ],
  },
  {
    name: 'Tanzania',
    region: 'Africa',
    iso2: 'TZ',
    iso3: 'TZA',
    currencyCode: 'TZS',
    currencyName: 'Tanzanian shilling',
    currencySymbol: 'TSh',
    bands: [
      {
        colour: '#000001',
        share: 0.296,
      },
      {
        colour: '#009900',
        share: 0.276,
      },
      {
        colour: '#0099ff',
        share: 0.276,
      },
    ],
  },
  {
    name: 'Ukraine',
    region: 'Europe',
    iso2: 'UA',
    iso3: 'UKR',
    currencyCode: 'UAH',
    currencyName: 'Ukrainian hryvnia',
    currencySymbol: '₴',
    bands: [
      {
        colour: '#0057b8',
        share: 0.5,
      },
      {
        colour: '#ffd700',
        share: 0.5,
      },
    ],
  },
  {
    name: 'Uganda',
    region: 'Africa',
    iso2: 'UG',
    iso3: 'UGA',
    currencyCode: 'UGX',
    currencyName: 'Ugandan shilling',
    currencySymbol: 'USh',
    bands: [
      {
        colour: '#ffe700',
        share: 0.333,
      },
      {
        colour: '#000001',
        share: 0.304,
      },
      {
        colour: '#de3908',
        share: 0.303,
      },
    ],
  },
  {
    name: 'USA',
    region: 'North America',
    iso2: 'US',
    iso3: 'USA',
    currencyCode: 'USD',
    currencyName: 'United States dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ffffff',
        share: 0.292,
      },
      {
        colour: '#bd3d44',
        share: 0.29,
      },
      {
        colour: '#192f5d',
        share: 0.192,
      },
    ],
  },
  {
    name: 'Uruguay',
    region: 'Latin America',
    iso2: 'UY',
    iso3: 'URY',
    currencyCode: 'UYU',
    currencyName: 'Uruguayan peso',
    currencySymbol: '$',
    bands: [
      {
        colour: '#ffffff',
        share: 0.529,
      },
      {
        colour: '#0038a8',
        share: 0.315,
      },
    ],
  },
  {
    name: 'Uzbekistan',
    region: 'Asia',
    iso2: 'UZ',
    iso3: 'UZB',
    currencyCode: 'UZS',
    currencyName: 'Uzbekistani soʻm',
    currencySymbol: 'soʼm',
    bands: [
      {
        colour: '#1eb53a',
        share: 0.317,
      },
      {
        colour: '#ffffff',
        share: 0.305,
      },
      {
        colour: '#0099b5',
        share: 0.288,
      },
    ],
  },
  {
    name: 'Vatican City',
    region: 'Europe',
    iso2: 'VA',
    iso3: 'VAT',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#ffe000',
        share: 0.5,
      },
      {
        colour: '#ffffff',
        share: 0.427,
      },
    ],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    region: 'Latin America',
    iso2: 'VC',
    iso3: 'VCT',
    currencyCode: 'XCD',
    currencyName: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    bands: [
      {
        colour: '#f4f100',
        share: 0.447,
      },
      {
        colour: '#199a00',
        share: 0.275,
      },
      {
        colour: '#0058aa',
        share: 0.225,
      },
    ],
  },
  {
    name: 'Venezuela',
    region: 'Latin America',
    iso2: 'VE',
    iso3: 'VEN',
    currencyCode: 'VES',
    currencyName: 'Venezuelan bolívar soberano',
    currencySymbol: 'Bs.S.',
    bands: [
      {
        colour: '#ffcc00',
        share: 0.333,
      },
      {
        colour: '#cf142b',
        share: 0.333,
      },
      {
        colour: '#00247d',
        share: 0.305,
      },
    ],
  },
  {
    name: 'Vietnam',
    region: 'Asia',
    iso2: 'VN',
    iso3: 'VNM',
    currencyCode: 'VND',
    currencyName: 'Vietnamese đồng',
    currencySymbol: '₫',
    bands: [
      {
        colour: '#da251d',
        share: 0.907,
      },
      {
        colour: '#ffff00',
        share: 0.069,
      },
    ],
  },
  {
    name: 'Vanuatu',
    region: 'Oceania',
    iso2: 'VU',
    iso3: 'VUT',
    currencyCode: 'VUV',
    currencyName: 'Vanuatu vatu',
    currencySymbol: 'Vt',
    bands: [
      {
        colour: '#d21034',
        share: 0.305,
      },
      {
        colour: '#009543',
        share: 0.305,
      },
      {
        colour: '#000000',
        share: 0.212,
      },
    ],
  },
  {
    name: 'Samoa',
    region: 'Oceania',
    iso2: 'WS',
    iso3: 'WSM',
    currencyCode: 'WST',
    currencyName: 'Samoan tālā',
    currencySymbol: 'T',
    bands: [
      {
        colour: '#ce1126',
        share: 0.75,
      },
      {
        colour: '#002b7f',
        share: 0.219,
      },
    ],
  },
  {
    name: 'Kosovo',
    region: 'Europe',
    iso2: 'XK',
    iso3: 'UNK',
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencySymbol: '€',
    bands: [
      {
        colour: '#244aa5',
        share: 0.86,
      },
      {
        colour: '#d0a650',
        share: 0.085,
      },
    ],
  },
  {
    name: 'Yemen',
    region: 'Middle East',
    iso2: 'YE',
    iso3: 'YEM',
    currencyCode: 'YER',
    currencyName: 'Yemeni rial',
    currencySymbol: '﷼',
    bands: [
      {
        colour: '#ffffff',
        share: 0.333,
      },
      {
        colour: '#f10600',
        share: 0.317,
      },
      {
        colour: '#000001',
        share: 0.317,
      },
    ],
  },
  {
    name: 'South Africa',
    region: 'Africa',
    iso2: 'ZA',
    iso3: 'ZAF',
    currencyCode: 'ZAR',
    currencyName: 'South African rand',
    currencySymbol: 'R',
    bands: [
      {
        colour: '#007847',
        share: 0.328,
      },
      {
        colour: '#e1392d',
        share: 0.196,
      },
      {
        colour: '#000c8a',
        share: 0.196,
      },
    ],
  },
  {
    name: 'Zambia',
    region: 'Africa',
    iso2: 'ZM',
    iso3: 'ZMB',
    currencyCode: 'ZMW',
    currencyName: 'Zambian kwacha',
    currencySymbol: 'ZK',
    bands: [
      {
        colour: '#198a00',
        share: 0.695,
      },
      {
        colour: '#ef7d00',
        share: 0.081,
      },
      {
        colour: '#000001',
        share: 0.079,
      },
    ],
  },
  {
    name: 'Zimbabwe',
    region: 'Africa',
    iso2: 'ZW',
    iso3: 'ZWE',
    currencyCode: 'BWP',
    currencyName: 'Botswana pula',
    currencySymbol: 'P',
    bands: [
      {
        colour: '#006400',
        share: 0.239,
      },
      {
        colour: '#ffd200',
        share: 0.197,
      },
      {
        colour: '#ffffff',
        share: 0.188,
      },
    ],
  },
];

const BY_ISO2 = new Map(COUNTRY_TABLE.map((row) => [row.iso2, row]));

export function countryTableRow(iso2: string | null | undefined) {
  return iso2 ? (BY_ISO2.get(iso2.trim().toUpperCase()) ?? null) : null;
}
