/**
 * Every country this catalogue knows: its codes, its money, its flag.
 *
 * Generated by scripts/country-table/generate.mjs -- edit that, not this.
 * ISO codes and currencies from world-countries (ISO 3166 / 4217); flag
 * colours measured from the flag-icons SVGs (MIT) by rendering and counting
 * pixels, so a share is the share of the flag a colour covers.
 */

export type CountryBand = {
  /** As it appears in the flag. */
  colour: string;
  /** How much of the flag it covers, 0 to 1. */
  share: number;
};

export type CountryTableRow = {
  name: string;
  region: string;
  iso2: string;
  iso3: string;
  currencyCode: string;
  currencyName: string;
  currencySymbol: string;
  /** Most of the flag first. Two colours where the flag has two. */
  bands: readonly CountryBand[];
};

export const COUNTRY_TABLE: readonly CountryTableRow[] = [];

const BY_ISO2 = new Map(COUNTRY_TABLE.map((row) => [row.iso2, row]));

export function countryTableRow(iso2: string | null | undefined) {
  return iso2 ? (BY_ISO2.get(iso2.trim().toUpperCase()) ?? null) : null;
}
