import type { CountryFacts } from './content';

/**
 * Twelve further destinations, written to the same rule as the first eight:
 * each described from what is actually true of it.
 *
 * Figures that move -- rankings, visa fees, processing times, maintenance
 * amounts a government revises -- are absent or null. Where a number has been
 * stable for years (Japan's standard national-university fee, Switzerland's
 * six-month job-search period) it is given; everything else is a range labelled
 * indicative or a sentence telling the student where to confirm it.
 */
export const MORE_COUNTRIES: CountryFacts[] = [
  {
    name: 'United States',
    slug: 'united-states',
    iso2: 'US',
    iso3: 'USA',
    continentSlug: 'north-america',
    capital: 'Washington, D.C.',
    language: 'English',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    currencySymbol: '$',
    nationality: 'American',
    tagline: 'The widest choice of universities anywhere, and a degree built around breadth',
    heading: 'Study in the United States',
    positioning:
      'The United States has more universities, and more kinds of university, than any other destination: large public research universities, small liberal-arts colleges, technical institutes and private universities with very large endowments. An undergraduate degree usually takes four years and asks students to study across several fields before declaring a major, while master’s programmes commonly run for one to two years and doctoral study is funded far more often than in most countries.',
    teaching:
      'Teaching is in English throughout, with continuous assessment — assignments, quizzes, participation and exams across the term — rather than a single examination at the end.',
    system:
      'There is no national university system. Each institution sets its own admission criteria, and undergraduate applications are made to many universities at once, often through a shared application platform, with standardised test requirements that vary by institution and have changed in recent years. Graduate applications go department by department, and research programmes frequently fund students through teaching or research assistantships.',
    strengths: [
      'computer science and engineering',
      'business and economics',
      'the natural sciences',
      'medicine and public health',
      'the social sciences',
    ],
    costShape:
      'Tuition varies more than anywhere else: public universities charge out-of-state and international students considerably more than residents, and private universities publish a single high sticker price that institutional aid often reduces. Living costs depend heavily on location, with the coastal cities far more expensive than university towns in the Midwest and South.',
    partTime:
      'Students on a study visa are usually limited to on-campus work during term, with a cap on weekly hours while classes are in session. Off-campus work is tied to specific authorisations related to the course of study, so a budget should not assume it.',
    postStudy:
      'A practical training period after graduation lets graduates work in their field for a limited time, with an extension available for many science, technology, engineering and mathematics degrees. Longer-term work routes are competitive and employer-sponsored, so treat staying on as a possibility rather than a plan.',
    cityLine:
      'Boston and Cambridge concentrate an unusual number of research universities in one place. The San Francisco Bay Area pairs them with the technology industry, Pittsburgh and Ann Arbor offer major universities at lower cost, and Atlanta combines a large technical institute with a growing job market.',
    intakeMonths: [8, 1],
    features: [
      'TOP_RANKED_UNIVERSITIES',
      'WIDE_SUBJECT_CHOICE',
      'STRONG_RESEARCH_FUNDING',
      'STRONG_STEM_INSTITUTIONS',
      'LARGE_GRADUATE_JOB_MARKET',
      'ENGLISH_TAUGHT_DEGREES',
      'POST_STUDY_WORK_AVAILABLE',
      'JANUARY_INTAKE_AVAILABLE',
      'SCHOLARSHIP_FRIENDLY',
    ],
    tests: ['IELTS', 'TOEFL', 'PTE', 'DUOLINGO'],
    tuitionMin: '20000',
    tuitionMax: '60000',
    livingMin: '1000',
    livingMax: '2500',
    partTimeAllowed: true,
    partTimeHours: null,
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'LIMITED',
    visaType: 'F-1 student visa',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'The United States rewards applicants who apply widely and early. With thousands of institutions and aid that differs from one to the next, the shortlist — and the net cost after scholarships and assistantships — matters more here than anywhere else.',
  },
  {
    name: 'New Zealand',
    slug: 'new-zealand',
    iso2: 'NZ',
    iso3: 'NZL',
    continentSlug: 'australia-new-zealand',
    capital: 'Wellington',
    language: 'English and Māori',
    currencyName: 'New Zealand Dollar',
    currencyCode: 'NZD',
    currencySymbol: '$',
    nationality: 'New Zealander',
    tagline: 'Eight universities, all of them research institutions, in a country built for the outdoors',
    heading: 'Study in New Zealand',
    positioning:
      'New Zealand has only eight universities, and every one of them is a public research university, so the gap between institutions is narrower than in larger countries. Degrees follow a British-influenced structure — three-year bachelor’s degrees, one- or two-year master’s programmes — and classes are small by international standards.',
    teaching:
      'Teaching is in English, with a practical emphasis and coursework that counts alongside examinations.',
    system:
      'The universities admit international students directly, each with its own entry requirements. Alongside them sit polytechnics and institutes of technology offering applied qualifications, which matter if a vocational route suits the career you want.',
    strengths: [
      'agriculture and environmental science',
      'engineering',
      'the life sciences',
      'tourism and hospitality',
      'the creative industries',
    ],
    costShape:
      'Tuition for international students sits in the middle of the English-speaking range, and living costs are highest in Auckland and lower in the smaller university cities, where rent makes the biggest difference.',
    partTime:
      'Student visas for degree-level study commonly allow a limited number of working hours a week in term and full-time work in scheduled breaks. The exact allowance has been revised recently, so check the conditions printed on your visa.',
    postStudy:
      'A post-study work visa lets eligible graduates stay and work for a period that depends on the level of qualification and where it was studied. Its terms are set by immigration policy and are worth confirming for your intake.',
    cityLine:
      'Auckland is the largest city and the most expensive. Wellington, the capital, is compact and student-heavy, and Christchurch and Dunedin offer lower costs and a strong university-town character.',
    intakeMonths: [2, 7],
    features: [
      'ENGLISH_TAUGHT_DEGREES',
      'POST_STUDY_WORK_AVAILABLE',
      'PART_TIME_ALLOWED',
      'STRONG_RESEARCH_FUNDING',
      'SCHOLARSHIP_FRIENDLY',
    ],
    tests: ['IELTS', 'TOEFL', 'PTE'],
    tuitionMin: '22000',
    tuitionMax: '45000',
    livingMin: '1300',
    livingMax: '2000',
    partTimeAllowed: true,
    partTimeHours: null,
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Fee paying student visa',
    ieltsRequirement: 'REQUIRED',
    waiverAvailable: true,
    closing:
      'New Zealand suits students who want a research university without the scale of a large system. With eight universities, choosing the city is as much a part of the decision as choosing the programme.',
  },
  {
    name: 'France',
    slug: 'france',
    iso2: 'FR',
    iso3: 'FRA',
    continentSlug: 'europe',
    capital: 'Paris',
    language: 'French',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencySymbol: '€',
    nationality: 'French',
    tagline: 'Public universities at modest fees, and grandes écoles with a direct line to industry',
    heading: 'Study in France',
    positioning:
      'France runs two systems side by side: public universities, which are open, large and inexpensive, and the grandes écoles — selective engineering and business schools with close ties to employers. Degrees follow the European licence–master–doctorate structure, and a growing number of master’s programmes are taught entirely in English.',
    teaching:
      'Most undergraduate teaching is in French. Many master’s programmes, particularly in business and engineering, are taught in English, and French is worth learning for daily life whichever you choose.',
    system:
      'Public university fees are set nationally, with differentiated rates for students from outside the European Union and many exemptions granted by institutions. Grandes écoles set their own admission and fees. Students from many countries apply through a national online procedure managed by Campus France before applying for a visa.',
    strengths: [
      'engineering',
      'business and management',
      'mathematics',
      'fashion and design',
      'the humanities and the arts',
    ],
    costShape:
      'Public universities are among the least expensive in Western Europe for tuition, while business schools and some grandes écoles charge fees comparable to the English-speaking world. Paris costs markedly more to live in than Lyon, Toulouse or Grenoble, and housing assistance is available to many students.',
    partTime:
      'Students with a long-stay study visa are permitted to work part time, up to an annual allowance that works out at roughly half-time across the year. It supplements a budget rather than funding one.',
    postStudy:
      'Graduates at master’s level and above can apply for a temporary residence permit to look for work or create a business. Its duration and conditions are set by the authorities and are worth confirming before you graduate.',
    cityLine:
      'Paris concentrates the most institutions and the highest costs. Lyon, Toulouse and Grenoble are major university cities with strong engineering and research, at a noticeably lower cost of living.',
    intakeMonths: [9, 1],
    features: [
      'EU_MEMBER_STATE',
      'SCHENGEN_VISA',
      'LOW_TUITION_FEES',
      'ENGLISH_TAUGHT_DEGREES',
      'GOVERNMENT_SCHOLARSHIPS_AVAILABLE',
      'PART_TIME_ALLOWED',
      'POST_STUDY_WORK_AVAILABLE',
      'STRONG_ENGINEERING_AND_TECHNOLOGY',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '2800',
    tuitionMax: '30000',
    livingMin: '800',
    livingMax: '1400',
    partTimeAllowed: true,
    partTimeHours: null,
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Long-stay student visa (VLS-TS)',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'France rewards students who decide early which of its two systems they want. A public university and a grande école lead to different experiences at very different costs, and the right choice depends on the career you are aiming for.',
  },
  {
    name: 'Italy',
    slug: 'italy',
    iso2: 'IT',
    iso3: 'ITA',
    continentSlug: 'europe',
    capital: 'Rome',
    language: 'Italian',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencySymbol: '€',
    nationality: 'Italian',
    tagline: 'Some of Europe’s oldest universities, with fees tied to what a family can pay',
    heading: 'Study in Italy',
    positioning:
      'Italy is home to some of the oldest universities in the world and to strong technical universities in Milan and Turin. Public university fees are usually scaled to family income, which can make them very low, and the number of master’s programmes taught in English has grown steadily.',
    teaching:
      'Undergraduate teaching is mostly in Italian, while English-taught programmes are common at master’s level, especially in engineering, economics and design. Oral examinations are a distinctive feature of assessment.',
    system:
      'Public universities follow the European three-cycle structure. Applicants from outside the European Union usually pre-enrol through the Italian mission in their country before applying for a visa, and some programmes also set their own admission tests.',
    strengths: [
      'architecture and design',
      'engineering',
      'economics and management',
      'fashion',
      'art, history and the humanities',
    ],
    costShape:
      'Public universities charge fees scaled to family income, which can make tuition low. Private universities cost considerably more. Milan is the most expensive city to live in, while Bologna, Padua, Turin and Rome sit at a more moderate level.',
    partTime:
      'Students with a study residence permit may work part time, within a weekly and an annual limit on hours.',
    postStudy:
      'Graduates can convert their permit to look for work after finishing their degree. The duration and conditions are set nationally and are worth confirming when you complete your studies.',
    cityLine:
      'Milan pairs a technical university with the country’s business and design centre. Bologna is the archetypal student city, Rome combines history with a large public university, and Turin and Padua offer strong universities at lower cost.',
    intakeMonths: [9, 2],
    features: [
      'EU_MEMBER_STATE',
      'SCHENGEN_VISA',
      'LOW_TUITION_FEES',
      'BUDGET_FRIENDLY',
      'ENGLISH_TAUGHT_DEGREES',
      'GOVERNMENT_SCHOLARSHIPS_AVAILABLE',
      'PART_TIME_ALLOWED',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '900',
    tuitionMax: '20000',
    livingMin: '700',
    livingMax: '1200',
    partTimeAllowed: true,
    partTimeHours: '20',
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'National (Type D) study visa',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'Italy suits students who value an old academic tradition and low public fees, and who are ready for an administrative process that rewards starting early — pre-enrolment, the visa and the residence permit each take time.',
  },
  {
    name: 'Spain',
    slug: 'spain',
    iso2: 'ES',
    iso3: 'ESP',
    continentSlug: 'europe',
    capital: 'Madrid',
    language: 'Spanish',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencySymbol: '€',
    nationality: 'Spanish',
    tagline: 'Business schools with global reach, and public universities at modest cost',
    heading: 'Study in Spain',
    positioning:
      'Spain combines internationally known business schools with a large public university system and a cost of living below Western Europe’s most expensive countries. Master’s programmes often run for one year, and English-taught options are concentrated in business, engineering and tourism.',
    teaching:
      'Most public-university teaching is in Spanish, and in Catalonia partly in Catalan. Business schools and many master’s programmes teach in English.',
    system:
      'Public universities are organised by region, which also sets their fees. Private universities and business schools set their own admission and fees and often run multiple intakes a year.',
    strengths: [
      'business and management',
      'tourism and hospitality',
      'architecture',
      'engineering',
      'languages and the humanities',
    ],
    costShape:
      'Public university fees are modest by European standards, while business schools charge premium fees. Madrid and Barcelona cost the most to live in, and Valencia, Seville and Granada are noticeably cheaper.',
    partTime:
      'Students with a study authorisation may work part time alongside their studies, within a weekly limit on hours that was raised in recent years.',
    postStudy:
      'Graduates can apply for a permit to search for work or to start a business after completing their degree. Confirm the current conditions when you apply.',
    cityLine:
      'Madrid and Barcelona host the major business schools and the widest choice of programmes. Valencia, Seville and Granada offer large student populations at a lower cost of living.',
    intakeMonths: [9, 2],
    features: [
      'EU_MEMBER_STATE',
      'SCHENGEN_VISA',
      'BUDGET_FRIENDLY',
      'ENGLISH_TAUGHT_DEGREES',
      'PART_TIME_ALLOWED',
      'POST_STUDY_WORK_AVAILABLE',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '1000',
    tuitionMax: '25000',
    livingMin: '700',
    livingMax: '1300',
    partTimeAllowed: true,
    partTimeHours: '30',
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Student visa (Type D)',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'Spain rewards students who are clear about whether they want a business school or a public university. The two differ sharply in cost, language of teaching and the network a graduate leaves with.',
  },
  {
    name: 'Sweden',
    slug: 'sweden',
    iso2: 'SE',
    iso3: 'SWE',
    continentSlug: 'europe',
    capital: 'Stockholm',
    language: 'Swedish',
    currencyName: 'Swedish Krona',
    currencyCode: 'SEK',
    currencySymbol: 'kr',
    nationality: 'Swedish',
    tagline: 'English-taught master’s degrees in a system built around independent work',
    heading: 'Study in Sweden',
    positioning:
      'Sweden offers a large number of English-taught master’s programmes in a university culture built on independent study, group work and informal relationships with teaching staff. Courses are usually taken one at a time in short, intensive blocks rather than several in parallel.',
    teaching:
      'Master’s teaching is widely in English. Bachelor’s programmes are mostly in Swedish, with a smaller English-taught offer.',
    system:
      'Applications to most programmes go through a single national application service with shared deadlines. Students from outside the European Union pay tuition fees, which are set by each university and programme.',
    strengths: [
      'engineering and technology',
      'environmental science and sustainability',
      'design',
      'the life sciences',
      'business',
    ],
    costShape:
      'Tuition for students from outside the European Union is substantial, and living costs are high in Stockholm, lower in Lund, Uppsala and Gothenburg. The Migration Agency sets a monthly maintenance amount that residence-permit applicants must show, and it is revised periodically.',
    partTime:
      'Students with a residence permit for studies are allowed to work alongside their studies, and there is no fixed cap on hours, though a full-time programme leaves limited room.',
    postStudy:
      'Graduates can apply for a residence permit to look for work or start a business after completing their studies. Confirm the current duration and conditions with the Migration Agency.',
    cityLine:
      'Stockholm is the capital and the most expensive. Lund and Uppsala are classic university towns, and Gothenburg combines a large university with a strong engineering and industrial base.',
    intakeMonths: [8, 1],
    features: [
      'EU_MEMBER_STATE',
      'SCHENGEN_VISA',
      'ENGLISH_TAUGHT_DEGREES',
      'STRONG_RESEARCH_FUNDING',
      'GOVERNMENT_SCHOLARSHIPS_AVAILABLE',
      'PART_TIME_ALLOWED',
      'POST_STUDY_WORK_AVAILABLE',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '80000',
    tuitionMax: '295000',
    livingMin: '9000',
    livingMax: '14000',
    partTimeAllowed: true,
    partTimeHours: null,
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Residence permit for studies',
    ieltsRequirement: 'REQUIRED',
    waiverAvailable: true,
    closing:
      'Sweden suits students who work well on their own and value a flat, informal academic culture. The fees are real, so scholarships and the national application deadlines are worth planning around early.',
  },
  {
    name: 'Denmark',
    slug: 'denmark',
    iso2: 'DK',
    iso3: 'DNK',
    continentSlug: 'europe',
    capital: 'Copenhagen',
    language: 'Danish',
    currencyName: 'Danish Krone',
    currencyCode: 'DKK',
    currencySymbol: 'kr',
    nationality: 'Danish',
    tagline: 'Problem-based learning, English-taught master’s degrees and a strong design tradition',
    heading: 'Study in Denmark',
    positioning:
      'Denmark’s universities are known for project- and problem-based learning, in which students work in groups on real problems, often with companies. English-taught programmes are common at master’s level, and the country has a strong tradition in design, engineering and the life sciences.',
    teaching:
      'Master’s teaching is widely in English; bachelor’s programmes are mostly in Danish with a growing English-taught offer.',
    system:
      'Bachelor’s applications go through a national admission portal with a common deadline, while master’s applications are made directly to universities. Students from outside the European Union pay tuition set by each institution.',
    strengths: [
      'engineering',
      'design and architecture',
      'the life sciences and pharmaceuticals',
      'renewable energy',
      'business',
    ],
    costShape:
      'Tuition for students from outside the European Union is set by each university, and living costs are high, especially in Copenhagen. Aarhus, Odense and Aalborg are somewhat cheaper.',
    partTime:
      'Students from outside the European Union with a residence permit may usually work a limited number of hours a week during term and full time in the summer months.',
    postStudy:
      'Graduates may be eligible for a permit that lets them stay and look for work for a period after completing their degree. Check the current terms with the Danish immigration authorities.',
    cityLine:
      'Copenhagen is the capital and the most expensive. Aarhus is a large university city, Aalborg is known for problem-based engineering, and Odense sits between them in size and cost.',
    intakeMonths: [9, 2],
    features: [
      'EU_MEMBER_STATE',
      'SCHENGEN_VISA',
      'ENGLISH_TAUGHT_DEGREES',
      'STRONG_RESEARCH_FUNDING',
      'PART_TIME_ALLOWED',
      'POST_STUDY_WORK_AVAILABLE',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '45000',
    tuitionMax: '120000',
    livingMin: '7000',
    livingMax: '11000',
    partTimeAllowed: true,
    partTimeHours: '20',
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Residence permit for studies',
    ieltsRequirement: 'REQUIRED',
    waiverAvailable: true,
    closing:
      'Denmark suits students who learn best by working on problems with others. Group projects carry real weight in assessment, so expect to spend much of the degree collaborating.',
  },
  {
    name: 'Finland',
    slug: 'finland',
    iso2: 'FI',
    iso3: 'FIN',
    continentSlug: 'europe',
    capital: 'Helsinki',
    language: 'Finnish and Swedish',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    currencySymbol: '€',
    nationality: 'Finnish',
    tagline: 'Research universities and applied-science universities, with scholarships built into the fees',
    heading: 'Study in Finland',
    positioning:
      'Finland has two kinds of higher education institution: research universities and universities of applied sciences, which focus on practical, work-oriented degrees. Many programmes are taught in English, and universities commonly offer scholarships that reduce the tuition fee for strong applicants.',
    teaching:
      'Many bachelor’s and master’s programmes are taught in English. Finnish or Swedish helps considerably with daily life and part-time work.',
    system:
      'Applications go through a national joint application service with set application periods. Students from outside the European Union pay tuition, and each institution runs its own scholarship scheme.',
    strengths: [
      'technology and engineering',
      'education',
      'design',
      'forestry and environmental science',
      'health sciences',
    ],
    costShape:
      'Tuition for students from outside the European Union is moderate by Northern European standards and often reduced by institutional scholarships. Living costs are highest in Helsinki and lower in Tampere, Turku and Oulu.',
    partTime:
      'Students with a residence permit for studies may work part time within an average weekly limit during term, and without limit during official holidays.',
    postStudy:
      'Graduates can apply for an extended permit to look for work or start a business after graduation. Confirm the current terms with the Finnish Immigration Service.',
    cityLine:
      'Helsinki and the neighbouring city of Espoo host the largest universities. Tampere, Turku and Oulu are university cities with lower living costs and strong technology sectors.',
    intakeMonths: [8, 1],
    features: [
      'EU_MEMBER_STATE',
      'SCHENGEN_VISA',
      'ENGLISH_TAUGHT_DEGREES',
      'SCHOLARSHIP_FRIENDLY',
      'PART_TIME_ALLOWED',
      'POST_STUDY_WORK_AVAILABLE',
      'STRONG_RESEARCH_FUNDING',
    ],
    tests: ['IELTS', 'TOEFL', 'PTE'],
    tuitionMin: '8000',
    tuitionMax: '18000',
    livingMin: '700',
    livingMax: '1100',
    partTimeAllowed: true,
    partTimeHours: '30',
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Residence permit for studies',
    ieltsRequirement: 'REQUIRED',
    waiverAvailable: true,
    closing:
      'Finland suits students who want a calm, well-organised system and are comfortable with winters that are long and dark. Deciding between a research university and a university of applied sciences is the first real choice.',
  },
  {
    name: 'Switzerland',
    slug: 'switzerland',
    iso2: 'CH',
    iso3: 'CHE',
    continentSlug: 'europe',
    capital: 'Bern',
    language: 'German, French, Italian and Romansh',
    currencyName: 'Swiss Franc',
    currencyCode: 'CHF',
    currencySymbol: 'CHF',
    nationality: 'Swiss',
    tagline: 'World-leading technical universities at low public fees, in a country that costs a lot to live in',
    heading: 'Study in Switzerland',
    positioning:
      'Switzerland’s two federal institutes of technology are among the most respected technical universities in the world, and public university fees are low even for international students. The catch is the cost of living, which is among the highest anywhere.',
    teaching:
      'Bachelor’s teaching is usually in the local language of the canton — German, French or Italian. Many master’s programmes are taught in English.',
    system:
      'There are cantonal universities, the two federal institutes of technology and universities of applied sciences. Admission is made directly to each institution, and some programmes are highly selective at master’s level.',
    strengths: [
      'engineering and technology',
      'the natural sciences',
      'hospitality management',
      'finance and banking',
      'international relations',
    ],
    costShape:
      'Public tuition is low, but living costs are among the highest in the world. Zurich and Geneva are the most expensive cities, and applicants must show sufficient funds for their stay.',
    partTime:
      'Students from outside the European Union may usually begin working part time after an initial period of study, within a weekly limit during term.',
    postStudy:
      'Graduates from outside the European Union may stay for a period of up to six months after graduation to look for a job in Switzerland.',
    cityLine:
      'Zurich and Lausanne host the two federal institutes of technology. Geneva is home to international organisations, and Basel and Bern offer strong cantonal universities.',
    intakeMonths: [9, 2],
    features: [
      'SCHENGEN_VISA',
      'TOP_RANKED_UNIVERSITIES',
      'LOW_TUITION_FEES',
      'STRONG_RESEARCH_FUNDING',
      'STRONG_ENGINEERING_AND_TECHNOLOGY',
      'GOVERNMENT_SCHOLARSHIPS_AVAILABLE',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '1000',
    tuitionMax: '4000',
    livingMin: '1800',
    livingMax: '2600',
    partTimeAllowed: true,
    partTimeHours: '15',
    postStudyAvailable: true,
    postStudyMinMonths: 6,
    postStudyMaxMonths: 6,
    pathwayStrength: 'LIMITED',
    visaType: 'National (Type D) visa and residence permit',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'Switzerland suits students admitted to its most demanding programmes and able to meet a high cost of living. The fee is the smallest part of the budget; rent and daily costs are the largest.',
  },
  {
    name: 'Japan',
    slug: 'japan',
    iso2: 'JP',
    iso3: 'JPN',
    continentSlug: 'asia',
    capital: 'Tokyo',
    language: 'Japanese',
    currencyName: 'Japanese Yen',
    currencyCode: 'JPY',
    currencySymbol: '¥',
    nationality: 'Japanese',
    tagline: 'Research universities, a standard national fee and a growing range of English-taught degrees',
    heading: 'Study in Japan',
    positioning:
      'Japan has strong national research universities, especially in engineering and the sciences, and a standard tuition fee at national universities that is modest by international standards. English-taught degree programmes are offered at a growing number of universities, alongside Japanese-taught programmes that require language proficiency.',
    teaching:
      'Most teaching is in Japanese. English-taught programmes exist at both bachelor’s and master’s level at many major universities.',
    system:
      'National, public and private universities set their own admission. Many international students apply for research or graduate study with the support of a prospective supervisor, and some take a Japanese-language preparatory course first.',
    strengths: [
      'engineering and robotics',
      'the natural sciences',
      'materials science',
      'medicine and the life sciences',
      'Japanese studies and culture',
    ],
    costShape:
      'National universities charge a standard tuition fee that has been stable for many years, while private universities charge more. Tokyo is the most expensive city to live in, and regional university cities are considerably cheaper.',
    partTime:
      'International students may work part time with permission, within a weekly limit during term and more during long vacations.',
    postStudy:
      'Graduates can stay to look for work under a job-hunting status, and employment in Japan leads to a work visa. Check the current conditions with the Immigration Services Agency.',
    cityLine:
      'Tokyo hosts the largest number of universities and the highest costs. Kyoto and Osaka are major university cities, and Sendai, Nagoya and Fukuoka offer strong universities at lower cost.',
    intakeMonths: [4, 10],
    features: [
      'STRONG_ENGINEERING_AND_TECHNOLOGY',
      'STRONG_RESEARCH_FUNDING',
      'GOVERNMENT_SCHOLARSHIPS_AVAILABLE',
      'SCHOLARSHIP_FRIENDLY',
      'PART_TIME_ALLOWED',
      'ENGLISH_TAUGHT_DEGREES',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '535800',
    tuitionMax: '1500000',
    livingMin: '80000',
    livingMax: '150000',
    partTimeAllowed: true,
    partTimeHours: '28',
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'Student visa (College Student status of residence)',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'Japan suits students prepared to engage with the language, even on an English-taught degree. The standard national fee and the government scholarship make it more affordable than its reputation suggests.',
  },
  {
    name: 'South Korea',
    slug: 'south-korea',
    iso2: 'KR',
    iso3: 'KOR',
    continentSlug: 'asia',
    capital: 'Seoul',
    language: 'Korean',
    currencyName: 'South Korean Won',
    currencyCode: 'KRW',
    currencySymbol: '₩',
    nationality: 'South Korean',
    tagline: 'Technology-led universities and a government scholarship that covers the full degree',
    heading: 'Study in South Korea',
    positioning:
      'South Korea’s leading universities are closely tied to one of the world’s most advanced technology economies, and a government scholarship programme funds international students for full degrees. English-taught programmes are common in engineering, business and graduate study.',
    teaching:
      'Teaching is a mix of Korean and English; many graduate programmes and some undergraduate programmes run largely in English.',
    system:
      'Universities admit international students directly, with spring and autumn intakes. Korean-language proficiency, measured by a national test, is required for many Korean-taught programmes.',
    strengths: [
      'electrical and electronic engineering',
      'computer science',
      'materials and semiconductors',
      'business',
      'media and culture',
    ],
    costShape:
      'Tuition is moderate compared with Western destinations, and private universities charge more than national ones. Seoul is the most expensive city to live in, and cities such as Daejeon and Busan are cheaper.',
    partTime:
      'International students may work part time with permission, with the allowance linked to their course level and Korean-language ability.',
    postStudy:
      'Graduates can apply for a job-seeker status after completing their degree. Check the current conditions with the Korea Immigration Service.',
    cityLine:
      'Seoul concentrates the most prominent universities. Daejeon is a centre for science and technology research, and Busan and Pohang host major universities outside the capital.',
    intakeMonths: [3, 9],
    features: [
      'GOVERNMENT_SCHOLARSHIPS_AVAILABLE',
      'STRONG_ENGINEERING_AND_TECHNOLOGY',
      'STRONG_STEM_INSTITUTIONS',
      'SCHOLARSHIP_FRIENDLY',
      'PART_TIME_ALLOWED',
      'BUDGET_FRIENDLY',
    ],
    tests: ['IELTS', 'TOEFL'],
    tuitionMin: '5000000',
    tuitionMax: '16000000',
    livingMin: '900000',
    livingMax: '1600000',
    partTimeAllowed: true,
    partTimeHours: null,
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'MODERATE',
    visaType: 'D-2 student visa',
    ieltsRequirement: 'VARIES',
    waiverAvailable: true,
    closing:
      'South Korea suits students interested in technology and ready to learn at least some Korean. The government scholarship is the single most important funding route to plan around.',
  },
  {
    name: 'United Arab Emirates',
    slug: 'united-arab-emirates',
    iso2: 'AE',
    iso3: 'ARE',
    continentSlug: 'middle-east',
    capital: 'Abu Dhabi',
    language: 'Arabic, with English widely used',
    currencyName: 'UAE Dirham',
    currencyCode: 'AED',
    currencySymbol: 'د.إ',
    nationality: 'Emirati',
    tagline: 'International branch campuses and English-taught degrees at a regional hub',
    heading: 'Study in the United Arab Emirates',
    positioning:
      'The United Arab Emirates hosts many international branch campuses of universities from the United Kingdom, Australia, India and elsewhere, alongside its own national universities. Teaching is almost always in English, and several universities run intakes in both autumn and spring.',
    teaching:
      'English is the main language of teaching at most institutions, including the branch campuses.',
    system:
      'Institutions are licensed and accredited nationally and, for branch campuses, also by the home university’s own authorities. Admission is made directly to each institution, and many offer foundation years.',
    strengths: [
      'business and finance',
      'engineering',
      'computer science',
      'hospitality and tourism',
      'media and design',
    ],
    costShape:
      'Tuition ranges widely between national universities and international branch campuses. Housing is the largest living cost, and Dubai and Abu Dhabi are more expensive than the northern emirates.',
    partTime:
      'Students may work part time with the appropriate permission, and some universities offer on-campus roles.',
    postStudy:
      'Some graduates may be eligible for residence options after graduation, including for outstanding students. Check the current conditions with the federal authorities.',
    cityLine:
      'Dubai hosts most branch campuses and a large expatriate job market. Abu Dhabi, the capital, is home to national universities, and Sharjah has its own university city.',
    intakeMonths: [9, 1],
    features: [
      'ENGLISH_TAUGHT_DEGREES',
      'JANUARY_INTAKE_AVAILABLE',
      'PART_TIME_ALLOWED',
      'WIDE_SUBJECT_CHOICE',
    ],
    tests: ['IELTS', 'TOEFL', 'PTE'],
    tuitionMin: '35000',
    tuitionMax: '100000',
    livingMin: '3000',
    livingMax: '6500',
    partTimeAllowed: true,
    partTimeHours: null,
    postStudyAvailable: true,
    postStudyMinMonths: null,
    postStudyMaxMonths: null,
    pathwayStrength: 'LIMITED',
    visaType: 'Student residence visa',
    ieltsRequirement: 'REQUIRED',
    waiverAvailable: false,
    closing:
      'The United Arab Emirates suits students who want an internationally recognised degree close to home in South Asia or the Middle East. Check that a branch campus awards the same degree as its home university before you apply.',
  },
];
