import type { CityFacts } from './places';

/**
 * The university cities of the twelve further destinations: one entry for
 * every city a university in `universities-more.ts` names, described in the
 * same four parts as the first set.
 */
export const MORE_CITIES: Record<string, CityFacts[]> = {
  'united-states': [
    {
      name: 'Cambridge',
      state: 'Massachusetts',
      featured: true,
      blurb: 'A small city across the river from Boston, home to two of the world’s best-known research universities.',
      studying: 'Life revolves around the universities, their laboratories and a dense cluster of research-driven companies nearby.',
      living: 'Among the most expensive places to rent in the country; shared housing and university accommodation are the norm.',
      moving: 'Walkable and well served by the subway into Boston, with rail and air links along the East Coast.',
    },
    {
      name: 'Stanford',
      state: 'California',
      blurb: 'A university community at the heart of Silicon Valley, between San Francisco and San Jose.',
      studying: 'The campus is self-contained, and the technology industry around it shapes internships and research.',
      living: 'Housing in the surrounding area is very expensive, which makes university accommodation especially valuable.',
      moving: 'A car or bicycle is useful; commuter rail connects to San Francisco and San Jose.',
    },
    {
      name: 'Berkeley',
      state: 'California',
      blurb: 'A university city on the east side of San Francisco Bay, defined by its public research university.',
      studying: 'A large, diverse student body and an energetic campus culture, with the Bay Area’s industries close by.',
      living: 'Rents are high across the Bay Area; many students share apartments near campus.',
      moving: 'Regional rail runs directly into San Francisco, and the city is compact enough to cycle.',
    },
    {
      name: 'Pittsburgh',
      state: 'Pennsylvania',
      blurb: 'A former steel city reinvented around universities, healthcare and robotics research.',
      studying: 'Several universities sit close together in one neighbourhood, with strong links to local technology companies.',
      living: 'Considerably cheaper than the coastal cities, with a good supply of student housing.',
      moving: 'Buses serve the university district well, and the city has direct flights across the country.',
    },
  ],
  'new-zealand': [
    {
      name: 'Auckland',
      state: 'Auckland',
      featured: true,
      blurb: 'New Zealand’s largest city, built around two harbours and home to its largest university.',
      studying: 'The widest choice of programmes and part-time work in the country.',
      living: 'The most expensive city in New Zealand, with rent the biggest part of any budget.',
      moving: 'Buses and trains serve the centre; the international airport connects across the Pacific and to Asia.',
    },
    {
      name: 'Wellington',
      state: 'Wellington',
      blurb: 'The capital, compact and windy, with a large student population and a strong creative sector.',
      studying: 'Government, law and the film industry give students distinctive internship options.',
      living: 'Somewhat cheaper than Auckland, though housing close to the centre is in demand.',
      moving: 'Walkable, with buses and a cable car serving the hillside campus.',
    },
    {
      name: 'Christchurch',
      state: 'Canterbury',
      blurb: 'The largest city in the South Island, rebuilt with new infrastructure after the 2011 earthquake.',
      studying: 'A strong engineering and science university with a campus outside the city centre.',
      living: 'Lower rents than the North Island cities and a relaxed pace of life.',
      moving: 'Flat and easy to cycle, with good access to the mountains and the coast.',
    },
    {
      name: 'Dunedin',
      state: 'Otago',
      blurb: 'A small southern city with a Scottish heritage, known as New Zealand’s student town.',
      studying: 'The university dominates the city, and a large share of residents are students.',
      living: 'One of the cheaper places to study in the country, with flatting close to campus.',
      moving: 'Walkable around the university, with a regional airport for domestic flights.',
    },
  ],
  france: [
    {
      name: 'Paris',
      state: 'Île-de-France',
      featured: true,
      blurb: 'The capital and the country’s largest concentration of universities, grandes écoles and research institutes.',
      studying: 'An unmatched choice of institutions, libraries and internships, in a city that expects students to be independent.',
      living: 'Housing is expensive and competitive; student residences and housing assistance make a real difference.',
      moving: 'The metro and suburban rail cover the region, and high-speed trains reach most of France and neighbouring countries.',
    },
    {
      name: 'Palaiseau',
      state: 'Île-de-France',
      blurb: 'A town south of Paris at the centre of the Paris-Saclay science and technology cluster.',
      studying: 'Several engineering schools and research centres share a campus built for science and innovation.',
      living: 'Cheaper than central Paris, with on-campus residences for many students.',
      moving: 'Suburban rail and buses connect to central Paris in under an hour.',
    },
    {
      name: 'Lyon',
      state: 'Auvergne-Rhône-Alpes',
      blurb: 'France’s third city, a historic centre of trade with a large student population.',
      studying: 'Strong in engineering, life sciences and business, with a lively student district.',
      living: 'Considerably cheaper than Paris, with a good supply of student housing.',
      moving: 'Metro and tram lines cover the city, and high-speed trains reach Paris in about two hours.',
    },
    {
      name: 'Toulouse',
      state: 'Occitanie',
      blurb: 'The centre of Europe’s aerospace industry and a major university city in the south-west.',
      studying: 'Engineering, aeronautics and space science are exceptionally strong here.',
      living: 'Affordable by French standards, with a young population and a warm climate.',
      moving: 'Metro and buses serve the city; the airport links to European capitals.',
    },
    {
      name: 'Grenoble',
      state: 'Auvergne-Rhône-Alpes',
      blurb: 'An Alpine city with a strong tradition of engineering, physics and research.',
      studying: 'Universities work closely with national research laboratories and technology companies.',
      living: 'Moderate living costs, with the mountains on the doorstep.',
      moving: 'Trams and cycling paths cover the city, and trains connect to Lyon and Paris.',
    },
  ],
  italy: [
    {
      name: 'Milan',
      state: 'Lombardy',
      featured: true,
      blurb: 'Italy’s business, fashion and design capital, with a large technical university.',
      studying: 'Engineering, architecture, design and economics dominate, with close links to industry.',
      living: 'The most expensive Italian city to live in; housing should be arranged early.',
      moving: 'An extensive metro and rail network, with fast trains to the rest of Italy.',
    },
    {
      name: 'Bologna',
      state: 'Emilia-Romagna',
      blurb: 'A medieval city built around the oldest university in continuous operation.',
      studying: 'The archetypal Italian student city, with a very large student population.',
      living: 'Moderate costs, though demand for rooms near the centre is high.',
      moving: 'Walkable and well connected by high-speed rail to Milan, Florence and Rome.',
    },
    {
      name: 'Rome',
      state: 'Lazio',
      blurb: 'The capital, home to one of Europe’s largest universities.',
      studying: 'A vast choice of programmes in a city where history is part of daily life.',
      living: 'Moderate to high costs depending on the neighbourhood.',
      moving: 'Buses, trams and a metro cover the city; trains connect to the rest of the country.',
    },
    {
      name: 'Turin',
      state: 'Piedmont',
      blurb: 'An industrial city in the north-west with a strong technical university and automotive heritage.',
      studying: 'Engineering and architecture are the main draws.',
      living: 'Cheaper than Milan, with elegant arcaded streets and a good supply of rooms.',
      moving: 'A metro line and trams serve the city; high-speed trains reach Milan quickly.',
    },
    {
      name: 'Padua',
      state: 'Veneto',
      blurb: 'A historic university city close to Venice.',
      studying: 'One of Europe’s oldest universities, strong in medicine, engineering and the sciences.',
      living: 'Moderate costs and a compact, student-friendly centre.',
      moving: 'Easy to cycle, with regional trains to Venice in under half an hour.',
    },
  ],
  spain: [
    {
      name: 'Madrid',
      state: 'Community of Madrid',
      featured: true,
      blurb: 'The capital, with large public universities and several international business schools.',
      studying: 'The widest choice of programmes in Spain and a large graduate job market.',
      living: 'One of the more expensive Spanish cities, especially for rent.',
      moving: 'An extensive metro, and high-speed trains to most of the country.',
    },
    {
      name: 'Barcelona',
      state: 'Catalonia',
      blurb: 'A Mediterranean city with major universities, business schools and a strong design scene.',
      studying: 'Teaching may be in Catalan, Spanish or English depending on the programme.',
      living: 'Rents are high near the centre; many students share flats further out.',
      moving: 'Metro, buses and cycling paths cover the city, with trains to France and Madrid.',
    },
    {
      name: 'Valencia',
      state: 'Valencian Community',
      blurb: 'Spain’s third city, on the Mediterranean coast.',
      studying: 'A large public university and a technical university, with a relaxed student life.',
      living: 'Noticeably cheaper than Madrid and Barcelona.',
      moving: 'Metro and trams serve the city; high-speed trains reach Madrid in under two hours.',
    },
    {
      name: 'Granada',
      state: 'Andalusia',
      blurb: 'A historic city in southern Spain beneath the Sierra Nevada.',
      studying: 'A large university with one of the biggest international student communities in Spain.',
      living: 'Among the cheapest university cities in Western Europe.',
      moving: 'Compact and walkable, with buses and a metro line.',
    },
  ],
  sweden: [
    {
      name: 'Stockholm',
      state: 'Stockholm County',
      featured: true,
      blurb: 'The capital, spread across islands, with a large technology and research sector.',
      studying: 'Strong technical and medical universities and the country’s largest job market.',
      living: 'The most expensive city in Sweden, with a long queue for housing.',
      moving: 'Excellent public transport across the islands and to the airport.',
    },
    {
      name: 'Lund',
      state: 'Skåne',
      blurb: 'A classic university town in the far south, close to Copenhagen.',
      studying: 'Student life is organised around student associations known as nations.',
      living: 'Cheaper than Stockholm, though housing is in demand at the start of term.',
      moving: 'Easy to cycle, with trains to Malmö and across the bridge to Copenhagen.',
    },
    {
      name: 'Uppsala',
      state: 'Uppsala County',
      blurb: 'A historic university city north of Stockholm.',
      studying: 'Scandinavia’s oldest university, with a strong tradition of student nations.',
      living: 'More affordable than Stockholm, with cycling the main way to get around.',
      moving: 'Trains reach Stockholm and its airport in well under an hour.',
    },
    {
      name: 'Gothenburg',
      state: 'Västra Götaland',
      blurb: 'Sweden’s second city, a west-coast port with a strong industrial and engineering base.',
      studying: 'A technical university and a large general university, both close to industry.',
      living: 'Cheaper than Stockholm, with an easy-going student culture.',
      moving: 'Trams cover the city, and trains connect to Oslo, Copenhagen and Stockholm.',
    },
  ],
  denmark: [
    {
      name: 'Copenhagen',
      state: 'Capital Region',
      featured: true,
      blurb: 'The capital, a cycling city with universities, design and life-science companies.',
      studying: 'The widest choice of programmes and the country’s largest job market.',
      living: 'Expensive, and student housing should be arranged well in advance.',
      moving: 'Cycling is the norm; the metro and trains connect to Sweden and the airport.',
    },
    {
      name: 'Aarhus',
      state: 'Central Denmark',
      blurb: 'Denmark’s second city, on the east coast of Jutland, with a young population.',
      studying: 'A large research university and a strong student culture.',
      living: 'Cheaper than Copenhagen, with more student housing available.',
      moving: 'Buses and a light rail line, with trains to Copenhagen.',
    },
    {
      name: 'Aalborg',
      state: 'North Denmark',
      blurb: 'A northern city known for its university’s problem-based learning model.',
      studying: 'Engineering and planning students work in project groups throughout their degree.',
      living: 'Among the more affordable places to study in Denmark.',
      moving: 'A compact city with buses and an airport for domestic and European flights.',
    },
  ],
  finland: [
    {
      name: 'Helsinki',
      state: 'Uusimaa',
      featured: true,
      blurb: 'The capital, on the Baltic coast, with the country’s largest university.',
      studying: 'The widest choice of programmes and a growing technology start-up scene.',
      living: 'The most expensive city in Finland, though student housing foundations help.',
      moving: 'Trams, metro and ferries, with trains across the country.',
    },
    {
      name: 'Espoo',
      state: 'Uusimaa',
      blurb: 'A city next to Helsinki, home to a large technology and business university campus.',
      studying: 'A campus built around technology, design and entrepreneurship.',
      living: 'Similar to Helsinki, with student housing near the campus.',
      moving: 'The metro connects directly to central Helsinki.',
    },
    {
      name: 'Tampere',
      state: 'Pirkanmaa',
      blurb: 'An inland city between two lakes, with a strong technology and industrial heritage.',
      studying: 'A multidisciplinary university working closely with local companies.',
      living: 'Cheaper than the capital region, with a lively student scene.',
      moving: 'A tram line and buses, with trains to Helsinki in under two hours.',
    },
    {
      name: 'Turku',
      state: 'Southwest Finland',
      blurb: 'Finland’s oldest city, on the south-west coast.',
      studying: 'Finnish- and Swedish-language universities share the city.',
      living: 'Moderate costs, with a compact centre.',
      moving: 'Buses and ferries to Sweden, with trains to Helsinki.',
    },
    {
      name: 'Oulu',
      state: 'North Ostrobothnia',
      blurb: 'A northern city with a strong technology sector.',
      studying: 'Known for wireless communication research and a close-knit campus.',
      living: 'Among the cheapest university cities in Finland, with long winters.',
      moving: 'A very bike-friendly city, with flights and trains to Helsinki.',
    },
  ],
  switzerland: [
    {
      name: 'Zurich',
      state: 'Zurich',
      featured: true,
      blurb: 'Switzerland’s largest city and financial centre, home to its leading technical university.',
      studying: 'Two major universities side by side, with strong links to industry and banking.',
      living: 'Among the most expensive cities in the world to live in.',
      moving: 'Excellent trams and trains, with the national rail network radiating from the city.',
    },
    {
      name: 'Lausanne',
      state: 'Vaud',
      blurb: 'A French-speaking city on Lake Geneva with a federal institute of technology.',
      studying: 'A lakeside campus shared by two universities.',
      living: 'Expensive, though a little cheaper than Zurich and Geneva.',
      moving: 'A metro line climbs the hillside city; trains reach Geneva quickly.',
    },
    {
      name: 'Geneva',
      state: 'Geneva',
      blurb: 'A French-speaking city home to many international organisations.',
      studying: 'International relations and law benefit from the United Nations and other bodies nearby.',
      living: 'Very expensive, with housing the largest cost.',
      moving: 'Trams and buses serve the city, and the airport links across Europe.',
    },
    {
      name: 'Basel',
      state: 'Basel-Stadt',
      blurb: 'A city on the Rhine where Switzerland meets France and Germany.',
      studying: 'Switzerland’s oldest university, close to a large pharmaceutical industry.',
      living: 'Expensive, though some students live across the border for lower rent.',
      moving: 'Trams cross the city and into neighbouring countries.',
    },
  ],
  japan: [
    {
      name: 'Tokyo',
      state: 'Tokyo',
      featured: true,
      blurb: 'The capital and the world’s largest metropolitan area, with more universities than anywhere else in Japan.',
      studying: 'The widest choice of programmes and the country’s largest job market.',
      living: 'The most expensive Japanese city, although shared housing and dormitories help.',
      moving: 'One of the world’s best rail networks.',
    },
    {
      name: 'Kyoto',
      state: 'Kyoto',
      blurb: 'The former imperial capital, full of temples and home to a major research university.',
      studying: 'A quieter pace and a strong tradition in the sciences.',
      living: 'Cheaper than Tokyo, with many students living close to campus.',
      moving: 'Buses and cycling, with fast trains to Osaka and Tokyo.',
    },
    {
      name: 'Osaka',
      state: 'Osaka',
      blurb: 'Japan’s commercial centre in the Kansai region, known for its food.',
      studying: 'Strong universities in engineering, medicine and the sciences.',
      living: 'Cheaper than Tokyo, with a large supply of rental housing.',
      moving: 'An extensive subway and rail network and an international airport.',
    },
    {
      name: 'Sendai',
      state: 'Miyagi',
      blurb: 'The largest city in the Tohoku region, known as the City of Trees.',
      studying: 'A major national research university with a large international student community.',
      living: 'Considerably cheaper than Tokyo.',
      moving: 'Subway lines and buses, with the bullet train reaching Tokyo in under two hours.',
    },
  ],
  'south-korea': [
    {
      name: 'Seoul',
      state: 'Seoul',
      featured: true,
      blurb: 'The capital, home to the country’s best-known universities and most of its large companies.',
      studying: 'An intense, fast-moving academic culture with close ties to industry.',
      living: 'The most expensive Korean city, though university dormitories are common.',
      moving: 'An extensive subway network and fast trains to other cities.',
    },
    {
      name: 'Daejeon',
      state: 'Daejeon',
      blurb: 'A science city in the centre of the country, home to government research institutes.',
      studying: 'The centre of Korean research in science and technology.',
      living: 'Considerably cheaper than Seoul.',
      moving: 'A subway line and buses, with high-speed trains to Seoul in about an hour.',
    },
    {
      name: 'Pohang',
      state: 'North Gyeongsang',
      blurb: 'A coastal industrial city in the south-east, known for steelmaking.',
      studying: 'A small, research-intensive science and technology university.',
      living: 'Among the cheapest places to study in Korea.',
      moving: 'Buses serve the city, with rail connections to Seoul.',
    },
  ],
  'united-arab-emirates': [
    {
      name: 'Dubai',
      state: 'Dubai',
      featured: true,
      blurb: 'A global business city and home to most of the country’s international branch campuses.',
      studying: 'Branch campuses of universities from several countries, largely in dedicated academic districts.',
      living: 'Housing is the largest cost; shared accommodation is common among students.',
      moving: 'A metro and tram network, with one of the world’s busiest airports.',
    },
    {
      name: 'Abu Dhabi',
      state: 'Abu Dhabi',
      blurb: 'The capital and the largest emirate, home to national universities and research centres.',
      studying: 'Strong in engineering and energy-related research.',
      living: 'Expensive, though somewhat cheaper than Dubai for some kinds of housing.',
      moving: 'Buses and taxis, with road links to Dubai.',
    },
    {
      name: 'Al Ain',
      state: 'Abu Dhabi',
      blurb: 'An oasis city inland from Abu Dhabi, known for its green spaces.',
      studying: 'Home to the country’s first national university.',
      living: 'Cheaper than the coastal cities.',
      moving: 'Buses and road links to Abu Dhabi and Dubai.',
    },
    {
      name: 'Sharjah',
      state: 'Sharjah',
      blurb: 'The emirate next to Dubai, known for culture and its dedicated university city.',
      studying: 'Several universities share a large university district.',
      living: 'Cheaper than Dubai, with many students commuting.',
      moving: 'Road links to Dubai, though traffic can be heavy.',
    },
  ],
};
