import type { ScholarshipFacts } from './scholarships';

/**
 * Further scholarships, written to the rule of `scholarships.ts`: what the
 * programme is and who it is for, with amounts, deadlines and eligible
 * countries left to the official page, which is the only reliable source.
 */
export const MORE_SCHOLARSHIP_PROVIDERS: Record<string, { name: string; url: string | null }> = {
  'fulbright-program': { name: 'Fulbright Program (U.S. Department of State)', url: 'https://foreign.fulbrightonline.org' },
  'knight-hennessy-scholars': { name: 'Knight-Hennessy Scholars, Stanford University', url: 'https://knight-hennessy.stanford.edu' },
  'manaaki-new-zealand': { name: 'Manaaki New Zealand Scholarships (New Zealand Government)', url: 'https://www.nzscholarships.govt.nz' },
  'campus-france': { name: 'Campus France', url: 'https://www.campusfrance.org' },
  'french-embassy-india': { name: 'French Embassy in India', url: 'https://www.inde.campusfrance.org' },
  'italian-ministry-foreign-affairs': { name: 'Italian Ministry of Foreign Affairs and International Cooperation', url: 'https://studyinitaly.esteri.it' },
  'swedish-institute': { name: 'Swedish Institute', url: 'https://si.se' },
  'study-in-finland': { name: 'Finnish universities (Finland Scholarship)', url: 'https://www.studyinfinland.fi' },
  'swiss-federal-commission-scholarships': { name: 'Federal Commission for Scholarships for Foreign Students (Switzerland)', url: 'https://www.sbfi.admin.ch' },
  'eth-zurich': { name: 'ETH Zurich', url: 'https://ethz.ch' },
  'japan-mext': { name: 'Japanese Government (MEXT)', url: 'https://www.studyinjapan.go.jp' },
  'korea-niied': { name: 'National Institute for International Education (Korea)', url: 'https://www.studyinkorea.go.kr' },
  'rhodes-trust': { name: 'Rhodes Trust', url: 'https://www.rhodeshouse.ox.ac.uk' },
  'gates-cambridge-trust': { name: 'Gates Cambridge Trust', url: 'https://www.gatescambridge.org' },
  'university-of-toronto': { name: 'University of Toronto', url: 'https://future.utoronto.ca' },
  'study-in-denmark': { name: 'Danish Agency for Higher Education and Science', url: 'https://studyindenmark.dk' },
};

export const MORE_SCHOLARSHIPS: ScholarshipFacts[] = [
  {
    title: 'Fulbright Foreign Student Program', slug: 'fulbright-foreign-student-program',
    provider: 'Fulbright Program (U.S. Department of State)', providerSlug: 'fulbright-program',
    providerUrl: 'https://foreign.fulbrightonline.org', countries: ['united-states'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://foreign.fulbrightonline.org',
    summary: 'The U.S. government’s flagship exchange programme, funding graduate study and research in the United States for students from many countries.',
    what: 'Fulbright supports graduate students, young professionals and artists to study and research in the United States. It is administered country by country, so the fields, levels and terms offered differ between countries.',
    who: 'Applicants generally need a first degree and must be citizens of a participating country. Each country’s commission or U.S. embassy sets its own additional criteria.',
    applying: 'Applications are made through the Fulbright commission or U.S. embassy in the applicant’s own country, each with its own timetable. The official site lists the country pages.',
  },
  {
    title: 'Knight-Hennessy Scholars', slug: 'knight-hennessy-scholars',
    provider: 'Knight-Hennessy Scholars, Stanford University', providerSlug: 'knight-hennessy-scholars',
    providerUrl: 'https://knight-hennessy.stanford.edu', countries: ['united-states'],
    benefitType: 'FULL_FUNDING',
    applicationUrl: 'https://knight-hennessy.stanford.edu',
    summary: 'A graduate scholarship at Stanford University that funds a full graduate degree in any of its schools.',
    what: 'Knight-Hennessy funds graduate study at Stanford across its schools, together with a leadership development programme that runs alongside the degree.',
    who: 'Open to applicants of any nationality applying to a full-time graduate programme at Stanford, with selection based on independence of thought, purposeful leadership and a civic mindset.',
    applying: 'Candidates apply to the scholarship and, separately, to the Stanford graduate programme. Deadlines are published on the programme’s website.',
  },
  {
    title: 'Manaaki New Zealand Scholarships', slug: 'manaaki-new-zealand-scholarships',
    provider: 'Manaaki New Zealand Scholarships (New Zealand Government)', providerSlug: 'manaaki-new-zealand',
    providerUrl: 'https://www.nzscholarships.govt.nz', countries: ['new-zealand'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://www.nzscholarships.govt.nz',
    summary: 'The New Zealand government’s scholarship programme for students from eligible developing countries.',
    what: 'Manaaki scholarships fund study in New Zealand, with an emphasis on subjects that support development in the scholar’s home country.',
    who: 'Eligibility is by citizenship of a participating country, and priority fields differ from one country to another.',
    applying: 'Applications open annually on the official website, which lists eligible countries, study levels and priority areas for each cycle.',
  },
  {
    title: 'Eiffel Excellence Scholarship Programme', slug: 'eiffel-excellence-scholarship-programme',
    provider: 'Campus France', providerSlug: 'campus-france',
    providerUrl: 'https://www.campusfrance.org', countries: ['france'],
    benefitType: 'PARTIAL_FUNDING', featured: true,
    applicationUrl: 'https://www.campusfrance.org',
    summary: 'A French government scholarship for international students at master’s and doctoral level.',
    what: 'The Eiffel programme, run by the French Ministry for Europe and Foreign Affairs, supports international students on master’s programmes and doctoral study in France with an allowance and related costs.',
    who: 'Candidates are nominated by French higher education institutions, and the programme focuses on particular fields of study.',
    applying: 'Students do not apply directly; the French institution applies on their behalf. Contact the international office of the institution you are applying to.',
  },
  {
    title: 'Charpak Scholarship', slug: 'charpak-scholarship',
    provider: 'French Embassy in India', providerSlug: 'french-embassy-india',
    providerUrl: 'https://www.inde.campusfrance.org', countries: ['france'],
    benefitType: 'PARTIAL_FUNDING',
    applicationUrl: 'https://www.inde.campusfrance.org',
    summary: 'Scholarships from the French Embassy in India for Indian students going to France.',
    what: 'The Charpak programme supports Indian students on master’s programmes, exchange semesters and research internships in France.',
    who: 'Indian nationals admitted to or applying for eligible programmes in France.',
    applying: 'Applications are made through Campus France India, which publishes each cycle’s streams and deadlines.',
  },
  {
    title: 'Italian Government Scholarships', slug: 'italian-government-scholarships',
    provider: 'Italian Ministry of Foreign Affairs and International Cooperation', providerSlug: 'italian-ministry-foreign-affairs',
    providerUrl: 'https://studyinitaly.esteri.it', countries: ['italy'],
    benefitType: 'PARTIAL_FUNDING',
    applicationUrl: 'https://studyinitaly.esteri.it',
    summary: 'Scholarships from the Italian government for international students at Italian universities and institutes.',
    what: 'The ministry offers scholarships for degree programmes, research and Italian language and culture courses, alongside separate regional scholarships awarded on income.',
    who: 'International students enrolling at Italian institutions, with eligible countries and levels set in each call.',
    applying: 'Applications are made online through the ministry’s Study in Italy portal during the annual call.',
  },
  {
    title: 'Swedish Institute Scholarships for Global Professionals', slug: 'swedish-institute-scholarships-for-global-professionals',
    provider: 'Swedish Institute', providerSlug: 'swedish-institute',
    providerUrl: 'https://si.se', countries: ['sweden'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://si.se',
    summary: 'Scholarships covering tuition and living costs for master’s study in Sweden by professionals from eligible countries.',
    what: 'The Swedish Institute funds master’s study in Sweden for people with work and leadership experience who aim to contribute to sustainable development.',
    who: 'Citizens of eligible countries with a certain amount of work and leadership experience, admitted to an eligible master’s programme.',
    applying: 'Applicants first apply to a master’s programme through the national admissions service, then to the scholarship in the Swedish Institute’s application period.',
  },
  {
    title: 'Danish Government Scholarships', slug: 'danish-government-scholarships',
    provider: 'Danish Agency for Higher Education and Science', providerSlug: 'study-in-denmark',
    providerUrl: 'https://studyindenmark.dk', countries: ['denmark'],
    benefitType: 'PARTIAL_FUNDING',
    applicationUrl: 'https://studyindenmark.dk',
    summary: 'Government-funded tuition waivers and grants for highly qualified students from outside the European Union, awarded through Danish universities.',
    what: 'The Danish government funds a number of full or partial tuition waivers and grants each year, distributed by the universities themselves.',
    who: 'Students from outside the European Union admitted to a full degree programme at a Danish institution.',
    applying: 'There is no separate national application; ask the international office of the university you are applying to.',
  },
  {
    title: 'Finland Scholarship', slug: 'finland-scholarship',
    provider: 'Finnish universities (Finland Scholarship)', providerSlug: 'study-in-finland',
    providerUrl: 'https://www.studyinfinland.fi', countries: ['finland'],
    benefitType: 'PARTIAL_FUNDING',
    applicationUrl: 'https://www.studyinfinland.fi',
    summary: 'A government-funded scholarship, awarded by Finnish universities, covering tuition and a relocation grant.',
    what: 'The Finland Scholarship covers tuition for the normal duration of a bachelor’s or master’s degree and includes a one-off grant towards moving to Finland.',
    who: 'Students from outside the European Union who are required to pay tuition, admitted to an eligible programme.',
    applying: 'Applications are made to the university alongside the degree application; each university sets its own criteria.',
  },
  {
    title: 'Swiss Government Excellence Scholarships', slug: 'swiss-government-excellence-scholarships',
    provider: 'Federal Commission for Scholarships for Foreign Students (Switzerland)', providerSlug: 'swiss-federal-commission-scholarships',
    providerUrl: 'https://www.sbfi.admin.ch', countries: ['switzerland'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://www.sbfi.admin.ch',
    summary: 'Scholarships for international researchers and doctoral candidates at Swiss universities.',
    what: 'The Swiss government funds doctoral, postdoctoral and research scholarships, and in some countries art scholarships, at Swiss public universities.',
    who: 'Graduates from eligible countries with a research project and the support of a professor at a Swiss university.',
    applying: 'Applications go through the Swiss embassy in the applicant’s country, which publishes the country-specific deadline.',
  },
  {
    title: 'ETH Zurich Excellence Scholarship and Opportunity Programme', slug: 'eth-zurich-excellence-scholarship-and-opportunity-programme',
    provider: 'ETH Zurich', providerSlug: 'eth-zurich',
    providerUrl: 'https://ethz.ch', countries: ['switzerland'],
    benefitType: 'FULL_FUNDING',
    applicationUrl: 'https://ethz.ch',
    summary: 'ETH Zurich’s merit scholarship for outstanding students on its master’s programmes.',
    what: 'The programme supports excellent master’s students at ETH Zurich with a scholarship covering study and living costs and a tuition waiver.',
    who: 'Outstanding students applying to a master’s programme at ETH Zurich, of any nationality.',
    applying: 'Applications are made together with the master’s application, within ETH’s published application window.',
  },
  {
    title: 'MEXT Scholarship', slug: 'mext-scholarship',
    provider: 'Japanese Government (MEXT)', providerSlug: 'japan-mext',
    providerUrl: 'https://www.studyinjapan.go.jp', countries: ['japan'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://www.studyinjapan.go.jp',
    summary: 'The Japanese government scholarship for international students, covering tuition, a monthly allowance and travel.',
    what: 'MEXT scholarships support undergraduate, research and specialised training students at Japanese universities.',
    who: 'Citizens of countries with diplomatic relations with Japan, meeting the age and academic requirements of each category.',
    applying: 'Most applicants apply through the Japanese embassy in their country; some apply through a Japanese university’s recommendation.',
  },
  {
    title: 'Global Korea Scholarship', slug: 'global-korea-scholarship',
    provider: 'National Institute for International Education (Korea)', providerSlug: 'korea-niied',
    providerUrl: 'https://www.studyinkorea.go.kr', countries: ['south-korea'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://www.studyinkorea.go.kr',
    summary: 'The Korean government’s scholarship covering tuition, living costs, travel and a year of Korean-language study.',
    what: 'GKS supports undergraduate and graduate study in South Korea, usually beginning with a year of Korean-language training.',
    who: 'Citizens of eligible countries meeting the academic and age requirements for each track.',
    applying: 'Applications are made through a Korean embassy or directly to a participating university, depending on the track.',
  },
  {
    title: 'Rhodes Scholarship', slug: 'rhodes-scholarship',
    provider: 'Rhodes Trust', providerSlug: 'rhodes-trust',
    providerUrl: 'https://www.rhodeshouse.ox.ac.uk', countries: ['united-kingdom'],
    benefitType: 'FULL_FUNDING', featured: true,
    applicationUrl: 'https://www.rhodeshouse.ox.ac.uk',
    summary: 'A postgraduate scholarship for study at the University of Oxford.',
    what: 'The Rhodes Scholarship funds postgraduate study at Oxford for students selected for academic excellence, character and leadership.',
    who: 'Eligibility is organised by country or region, each with its own age and citizenship criteria.',
    applying: 'Applications are made through the constituency for the applicant’s country, with deadlines published on the Rhodes House website.',
  },
  {
    title: 'Gates Cambridge Scholarship', slug: 'gates-cambridge-scholarship',
    provider: 'Gates Cambridge Trust', providerSlug: 'gates-cambridge-trust',
    providerUrl: 'https://www.gatescambridge.org', countries: ['united-kingdom'],
    benefitType: 'FULL_FUNDING',
    applicationUrl: 'https://www.gatescambridge.org',
    summary: 'A full-cost scholarship for postgraduate study at the University of Cambridge by students from outside the United Kingdom.',
    what: 'Gates Cambridge funds postgraduate study at Cambridge for students with outstanding academic ability and a commitment to improving the lives of others.',
    who: 'Applicants from any country outside the United Kingdom applying for a full-time postgraduate course at Cambridge.',
    applying: 'Candidates apply through the University of Cambridge’s graduate application, ticking the Gates Cambridge option.',
  },
  {
    title: 'Lester B. Pearson International Scholarship', slug: 'lester-b-pearson-international-scholarship',
    provider: 'University of Toronto', providerSlug: 'university-of-toronto',
    providerUrl: 'https://future.utoronto.ca', countries: ['canada'],
    benefitType: 'FULL_FUNDING',
    applicationUrl: 'https://future.utoronto.ca',
    summary: 'The University of Toronto’s scholarship for exceptional international secondary-school students.',
    what: 'The scholarship covers tuition, books, incidental fees and residence for four years of undergraduate study at the University of Toronto.',
    who: 'International students in their final year of secondary school who are nominated by their school.',
    applying: 'Students are nominated by their secondary school and apply to the university by its published deadline.',
  },
  {
    title: 'Holland Scholarship', slug: 'holland-scholarship',
    provider: 'Nuffic', providerSlug: 'nuffic',
    providerUrl: 'https://www.studyinnl.org', countries: ['netherlands'],
    benefitType: 'PARTIAL_FUNDING',
    applicationUrl: 'https://www.studyinnl.org',
    summary: 'A one-off grant for international students from outside the European Economic Area starting a degree in the Netherlands.',
    what: 'Funded by the Dutch Ministry of Education and participating institutions, the Holland Scholarship is a one-time payment in the first year of study.',
    who: 'Students from outside the European Economic Area who have not studied in the Netherlands before, applying to a participating institution.',
    applying: 'Applications are made to the participating university, each with its own deadline.',
  },
];
