import type { UniversityFacts } from './universities';

/**
 * Universities of the twelve further destinations, written to the same rule as
 * the first set: stable facts only -- where it is, when it was founded, what
 * it is known for -- and no rankings, fees or admission rates, which move.
 */
const U = (
  facts: Omit<UniversityFacts, 'extraCampuses'>,
): UniversityFacts => facts;

export const MORE_UNIVERSITIES: UniversityFacts[] = [
  // ------------------------------------------------------------ United States
  U({
    name: 'Massachusetts Institute of Technology', slug: 'massachusetts-institute-of-technology',
    countrySlug: 'united-states', city: 'Cambridge', institutionType: 'Private', founded: 1861, featured: true,
    character: 'MIT is a private research university built around science and engineering, known for turning research into companies and technologies.',
    strengths: ['computer science and artificial intelligence', 'engineering', 'physics', 'economics', 'architecture'],
    teaching: 'Problem sets and laboratory work dominate, and undergraduates are encouraged to join research groups early.',
    campus: 'A compact campus along the Charles River, facing Boston, with laboratories and start-ups clustered around it.',
    afterwards: 'Graduates move into technology, research, finance and entrepreneurship, often founding companies of their own.',
  }),
  U({
    name: 'Harvard University', slug: 'harvard-university',
    countrySlug: 'united-states', city: 'Cambridge', institutionType: 'Private', founded: 1636, featured: true,
    character: 'Harvard is the oldest institution of higher education in the United States and a private research university with a very broad range of professional schools.',
    strengths: ['law', 'business', 'medicine and public health', 'government and economics', 'the humanities'],
    teaching: 'Undergraduates follow a liberal-arts curriculum before specialising, while the professional schools are known for case-based teaching.',
    campus: 'Historic yards and residential houses in Cambridge, with the business and medical schools across the river in Boston.',
    afterwards: 'Graduates go into law, government, business, medicine and academia, supported by an extensive alumni network.',
  }),
  U({
    name: 'Stanford University', slug: 'stanford-university',
    countrySlug: 'united-states', city: 'Stanford', institutionType: 'Private', founded: 1885, featured: true,
    character: 'Stanford is a private research university at the centre of Silicon Valley, closely linked to the technology industry around it.',
    strengths: ['computer science', 'engineering', 'business', 'medicine', 'economics'],
    teaching: 'An interdisciplinary culture, with students encouraged to combine technical and design thinking.',
    campus: 'A very large campus between San Francisco and San Jose, with residential life on site.',
    afterwards: 'Graduates are strongly represented in technology companies, start-ups and venture capital.',
  }),
  U({
    name: 'University of California, Berkeley', slug: 'university-of-california-berkeley',
    countrySlug: 'united-states', city: 'Berkeley', institutionType: 'Public', founded: 1868,
    character: 'UC Berkeley is the founding campus of the University of California and one of the leading public research universities in the country.',
    strengths: ['engineering and computer science', 'chemistry', 'economics', 'public policy', 'environmental science'],
    teaching: 'Large introductory classes give way to small upper-division seminars and research opportunities.',
    campus: 'A hillside campus above San Francisco Bay, next to the city’s downtown.',
    afterwards: 'Graduates move into technology, research, public service and graduate study.',
  }),
  U({
    name: 'Carnegie Mellon University', slug: 'carnegie-mellon-university',
    countrySlug: 'united-states', city: 'Pittsburgh', institutionType: 'Private', founded: 1900,
    character: 'Carnegie Mellon is a private research university known for computer science, robotics and a strong arts school.',
    strengths: ['computer science', 'robotics', 'artificial intelligence', 'information systems', 'drama and design'],
    teaching: 'Project-based and technical, with close collaboration between computing, engineering and the arts.',
    campus: 'A campus in Pittsburgh’s Oakland district, near other universities and hospitals.',
    afterwards: 'Graduates are recruited heavily by technology companies and research labs.',
  }),
  // -------------------------------------------------------------- New Zealand
  U({
    name: 'University of Auckland', slug: 'university-of-auckland',
    countrySlug: 'new-zealand', city: 'Auckland', institutionType: 'Public', founded: 1883, featured: true,
    character: 'The University of Auckland is New Zealand’s largest university, with the widest range of programmes in the country.',
    strengths: ['engineering', 'medicine and health sciences', 'business', 'law', 'the creative arts'],
    teaching: 'A mix of lectures, tutorials and practical work, with coursework counting alongside exams.',
    campus: 'A city-centre campus beside Albert Park, with further campuses around the Auckland region.',
    afterwards: 'Graduates join Auckland’s business, health and engineering sectors or continue to research.',
  }),
  U({
    name: 'Victoria University of Wellington', slug: 'victoria-university-of-wellington',
    countrySlug: 'new-zealand', city: 'Wellington', institutionType: 'Public', founded: 1897,
    character: 'Victoria University of Wellington, in the capital, is known for law, public policy and the humanities.',
    strengths: ['law', 'public policy', 'international relations', 'architecture and design', 'earth sciences'],
    teaching: 'Small tutorial groups and strong links to government and the creative industries.',
    campus: 'A hillside campus above the city, reached by the cable car, with faculties in the central city.',
    afterwards: 'Graduates are well placed for the public service, law and the creative sector.',
  }),
  U({
    name: 'University of Canterbury', slug: 'university-of-canterbury',
    countrySlug: 'new-zealand', city: 'Christchurch', institutionType: 'Public', founded: 1873,
    character: 'The University of Canterbury is known for engineering and the sciences, on a spacious campus in Christchurch.',
    strengths: ['engineering', 'computer science', 'geology', 'environmental science', 'forestry'],
    teaching: 'Practical, project-based engineering with a strong focus on the natural environment.',
    campus: 'A green campus west of the city centre, rebuilt and modernised after the earthquakes.',
    afterwards: 'Graduates move into engineering, technology and environmental management.',
  }),
  U({
    name: 'University of Otago', slug: 'university-of-otago',
    countrySlug: 'new-zealand', city: 'Dunedin', institutionType: 'Public', founded: 1869,
    character: 'The University of Otago is New Zealand’s oldest university, known for health sciences and a strong residential student life.',
    strengths: ['medicine', 'dentistry', 'pharmacy', 'the life sciences', 'surveying'],
    teaching: 'Health sciences combine lectures with early clinical and laboratory experience.',
    campus: 'A historic campus along the Water of Leith in the heart of Dunedin.',
    afterwards: 'Graduates are well represented across New Zealand’s health professions.',
  }),
  // ------------------------------------------------------------------- France
  U({
    name: 'Sciences Po', slug: 'sciences-po',
    countrySlug: 'france', city: 'Paris', institutionType: 'Public', founded: 1872, featured: true,
    character: 'Sciences Po is a university specialising in the social sciences, known for politics, international affairs and public policy.',
    strengths: ['political science', 'international relations', 'economics', 'law', 'journalism'],
    teaching: 'Seminar-based, with many courses taught in English and a year abroad in the undergraduate programme.',
    campus: 'Buildings in central Paris, with regional undergraduate campuses elsewhere in France.',
    afterwards: 'Graduates go into diplomacy, public service, international organisations, consulting and media.',
  }),
  U({
    name: 'École Polytechnique', slug: 'ecole-polytechnique',
    countrySlug: 'france', city: 'Palaiseau', institutionType: 'Public', founded: 1794, featured: true,
    character: 'École Polytechnique is a leading French engineering school, known for mathematics and the sciences.',
    strengths: ['mathematics', 'physics', 'computer science', 'engineering', 'economics'],
    teaching: 'A rigorous scientific education with small classes and close links to research laboratories.',
    campus: 'A campus at the heart of the Paris-Saclay science and technology cluster, south of Paris.',
    afterwards: 'Graduates move into engineering, research, finance and senior roles in industry and the state.',
  }),
  U({
    name: 'INSA Lyon', slug: 'insa-lyon',
    countrySlug: 'france', city: 'Lyon', institutionType: 'Public', founded: 1957,
    character: 'INSA Lyon is a public engineering school that admits students straight after secondary school into a five-year engineering programme.',
    strengths: ['mechanical engineering', 'civil engineering', 'computer science', 'materials science', 'biosciences'],
    teaching: 'Two years of foundation science followed by specialised engineering departments.',
    campus: 'A dedicated campus in Villeurbanne, beside Lyon, with student residences on site.',
    afterwards: 'Graduates are recruited widely by French and international engineering companies.',
  }),
  U({
    name: 'Université Toulouse III – Paul Sabatier', slug: 'universite-toulouse-iii-paul-sabatier',
    countrySlug: 'france', city: 'Toulouse', institutionType: 'Public', founded: 1969,
    character: 'Paul Sabatier University is Toulouse’s science, technology and health university.',
    strengths: ['aerospace and space science', 'physics', 'biology', 'medicine', 'computer science'],
    teaching: 'Lectures and practical work, with research laboratories shared with national research bodies.',
    campus: 'A large campus in the south of the city, on the metro line.',
    afterwards: 'Graduates move into aerospace, research, health and technology.',
  }),
  U({
    name: 'Grenoble INP', slug: 'grenoble-inp',
    countrySlug: 'france', city: 'Grenoble', institutionType: 'Public', founded: 1900,
    character: 'Grenoble INP is a group of engineering schools with roots in the city’s electrical engineering tradition.',
    strengths: ['electrical engineering', 'energy', 'industrial engineering', 'computer science', 'materials'],
    teaching: 'Engineering degrees built around projects and internships with industry.',
    campus: 'Schools spread across Grenoble’s university campus and innovation district.',
    afterwards: 'Graduates join the energy, electronics and technology sectors.',
  }),
  // -------------------------------------------------------------------- Italy
  U({
    name: 'Politecnico di Milano', slug: 'politecnico-di-milano',
    countrySlug: 'italy', city: 'Milan', institutionType: 'Public', founded: 1863, featured: true,
    character: 'Politecnico di Milano is Italy’s largest technical university, known for engineering, architecture and design.',
    strengths: ['architecture', 'design', 'mechanical engineering', 'civil engineering', 'management engineering'],
    teaching: 'Studio-based teaching in design and architecture and project work in engineering, with many master’s programmes in English.',
    campus: 'Campuses in Milan’s Città Studi and Bovisa districts, with regional sites in Lombardy.',
    afterwards: 'Graduates move into engineering, architecture, design studios and consulting.',
  }),
  U({
    name: 'University of Bologna', slug: 'university-of-bologna',
    countrySlug: 'italy', city: 'Bologna', institutionType: 'Public', founded: 1088, featured: true,
    character: 'The University of Bologna is widely regarded as the oldest university in continuous operation, with a very broad range of subjects.',
    strengths: ['law', 'economics', 'medicine', 'agricultural science', 'the humanities'],
    teaching: 'Lectures and oral examinations, with a large offer of English-taught master’s programmes.',
    campus: 'University buildings woven through Bologna’s historic centre, with campuses across Romagna.',
    afterwards: 'Graduates move into law, business, public administration and research.',
  }),
  U({
    name: 'Sapienza University of Rome', slug: 'sapienza-university-of-rome',
    countrySlug: 'italy', city: 'Rome', institutionType: 'Public', founded: 1303,
    character: 'Sapienza is one of the largest universities in Europe, covering almost every field.',
    strengths: ['classics and archaeology', 'engineering', 'physics', 'medicine', 'architecture'],
    teaching: 'Large lectures and oral exams, with English-taught programmes at master’s level.',
    campus: 'A central city campus near Termini station, with faculties across Rome.',
    afterwards: 'Graduates go into research, public service, engineering and cultural heritage.',
  }),
  U({
    name: 'Politecnico di Torino', slug: 'politecnico-di-torino',
    countrySlug: 'italy', city: 'Turin', institutionType: 'Public', founded: 1859,
    character: 'Politecnico di Torino is a technical university closely tied to the automotive and aerospace industries.',
    strengths: ['automotive engineering', 'aerospace engineering', 'electrical engineering', 'architecture', 'computer engineering'],
    teaching: 'Engineering programmes with many courses in English and strong industry partnerships.',
    campus: 'A main campus in central Turin, with a separate architecture campus in a historic castle.',
    afterwards: 'Graduates join automotive, aerospace, energy and technology companies.',
  }),
  U({
    name: 'University of Padua', slug: 'university-of-padua',
    countrySlug: 'italy', city: 'Padua', institutionType: 'Public', founded: 1222,
    character: 'The University of Padua is one of Europe’s oldest universities, with a long tradition in medicine and science.',
    strengths: ['medicine', 'psychology', 'engineering', 'astronomy', 'agricultural science'],
    teaching: 'A broad range of programmes, with a growing number of master’s degrees taught in English.',
    campus: 'Historic buildings in the city centre alongside modern science campuses.',
    afterwards: 'Graduates move into health, engineering, research and the Veneto’s industrial economy.',
  }),
  // -------------------------------------------------------------------- Spain
  U({
    name: 'University of Barcelona', slug: 'university-of-barcelona',
    countrySlug: 'spain', city: 'Barcelona', institutionType: 'Public', founded: 1450, featured: true,
    character: 'The University of Barcelona is Catalonia’s largest public university, strong across medicine, science and the humanities.',
    strengths: ['medicine', 'biology', 'chemistry', 'economics', 'the humanities'],
    teaching: 'Teaching in Catalan and Spanish, with some programmes and courses in English.',
    campus: 'A historic building in the city centre and several campuses across Barcelona.',
    afterwards: 'Graduates move into health, research, education and business.',
  }),
  U({
    name: 'Complutense University of Madrid', slug: 'complutense-university-of-madrid',
    countrySlug: 'spain', city: 'Madrid', institutionType: 'Public', founded: 1499,
    character: 'Complutense is one of Spain’s largest and oldest universities, with a very wide range of faculties.',
    strengths: ['law', 'medicine', 'communication', 'fine arts', 'economics'],
    teaching: 'Mostly in Spanish, with a small number of English-taught programmes.',
    campus: 'A large university city in the north-west of Madrid, with a second campus at Somosaguas.',
    afterwards: 'Graduates go into law, media, public administration and business.',
  }),
  U({
    name: 'ESADE Business School', slug: 'esade-business-school',
    countrySlug: 'spain', city: 'Barcelona', institutionType: 'Private', founded: 1958, featured: true,
    character: 'ESADE is a private business and law school known for international management programmes.',
    strengths: ['business administration', 'finance', 'marketing', 'entrepreneurship', 'law'],
    teaching: 'Case-based teaching with a strong focus on teamwork and international exchange.',
    campus: 'Campuses in Barcelona and Sant Cugat, with a centre in Madrid.',
    afterwards: 'Graduates go into consulting, finance, marketing and entrepreneurship across Europe.',
  }),
  U({
    name: 'University of Valencia', slug: 'university-of-valencia',
    countrySlug: 'spain', city: 'Valencia', institutionType: 'Public', founded: 1499,
    character: 'The University of Valencia is a large public university with a long tradition in medicine and science.',
    strengths: ['medicine', 'pharmacy', 'chemistry', 'economics', 'psychology'],
    teaching: 'Mostly in Spanish and Valencian, with some English-taught master’s programmes.',
    campus: 'Three main campuses in the city, including a historic building in the old town.',
    afterwards: 'Graduates move into health, research and business in the Valencian region.',
  }),
  U({
    name: 'University of Granada', slug: 'university-of-granada',
    countrySlug: 'spain', city: 'Granada', institutionType: 'Public', founded: 1531,
    character: 'The University of Granada is one of Spain’s most popular universities with international and exchange students.',
    strengths: ['translation and languages', 'computer science', 'mathematics', 'pharmacy', 'history'],
    teaching: 'Mostly in Spanish, with a well-established programme of Spanish courses for international students.',
    campus: 'Faculties spread across the city, from the historic centre to modern science campuses.',
    afterwards: 'Graduates move into education, translation, research and technology.',
  }),
  // ------------------------------------------------------------------- Sweden
  U({
    name: 'KTH Royal Institute of Technology', slug: 'kth-royal-institute-of-technology',
    countrySlug: 'sweden', city: 'Stockholm', institutionType: 'Public', founded: 1827, featured: true,
    character: 'KTH is Sweden’s largest technical university, covering engineering, architecture and technology.',
    strengths: ['electrical engineering', 'computer science', 'energy', 'architecture', 'industrial management'],
    teaching: 'English-taught master’s programmes with project work and close industry collaboration.',
    campus: 'A historic main campus in central Stockholm, with further campuses around the city.',
    afterwards: 'Graduates join Sweden’s technology, telecommunications and engineering companies.',
  }),
  U({
    name: 'Lund University', slug: 'lund-university',
    countrySlug: 'sweden', city: 'Lund', institutionType: 'Public', founded: 1666, featured: true,
    character: 'Lund University is one of Scandinavia’s largest universities, with a strong international profile.',
    strengths: ['engineering', 'medicine', 'economics and management', 'environmental science', 'law'],
    teaching: 'Courses taken one at a time, with many English-taught master’s programmes.',
    campus: 'A university that fills the small city of Lund, with student nations at the centre of social life.',
    afterwards: 'Graduates move into research, the life-science industry and international business.',
  }),
  U({
    name: 'Uppsala University', slug: 'uppsala-university',
    countrySlug: 'sweden', city: 'Uppsala', institutionType: 'Public', founded: 1477,
    character: 'Uppsala University is the oldest university in the Nordic countries, strong in the sciences and medicine.',
    strengths: ['pharmacy', 'medicine', 'physics', 'peace and conflict studies', 'computer science'],
    teaching: 'Independent study with seminars and laboratory work, and English-taught master’s programmes.',
    campus: 'Historic university buildings in the city centre alongside modern science campuses.',
    afterwards: 'Graduates go into research, pharmaceuticals, public service and international organisations.',
  }),
  U({
    name: 'Chalmers University of Technology', slug: 'chalmers-university-of-technology',
    countrySlug: 'sweden', city: 'Gothenburg', institutionType: 'Private', founded: 1829,
    character: 'Chalmers is a technical university run by a foundation, with close ties to Sweden’s manufacturing industry.',
    strengths: ['mechanical engineering', 'automotive engineering', 'shipping and marine technology', 'computer science', 'architecture'],
    teaching: 'Project-based master’s programmes taught in English, many with industry partners.',
    campus: 'Two campuses in Gothenburg, one of them on the waterfront.',
    afterwards: 'Graduates join automotive, maritime and technology companies.',
  }),
  // ------------------------------------------------------------------ Denmark
  U({
    name: 'University of Copenhagen', slug: 'university-of-copenhagen',
    countrySlug: 'denmark', city: 'Copenhagen', institutionType: 'Public', founded: 1479, featured: true,
    character: 'The University of Copenhagen is Denmark’s oldest and largest university.',
    strengths: ['the life sciences', 'medicine', 'pharmaceutical sciences', 'economics', 'law'],
    teaching: 'Research-led teaching with English-taught master’s programmes.',
    campus: 'Four campuses spread across the city.',
    afterwards: 'Graduates join the life-science industry, public service and research.',
  }),
  U({
    name: 'Technical University of Denmark', slug: 'technical-university-of-denmark',
    countrySlug: 'denmark', city: 'Copenhagen', institutionType: 'Public', founded: 1829,
    character: 'DTU is Denmark’s leading technical university, known for engineering and sustainable energy.',
    strengths: ['wind and sustainable energy', 'biotechnology', 'electrical engineering', 'computer science', 'mechanical engineering'],
    teaching: 'Engineering programmes taught largely in English, with project work and industry collaboration.',
    campus: 'A main campus at Kongens Lyngby, north of Copenhagen.',
    afterwards: 'Graduates join engineering, energy and technology companies.',
  }),
  U({
    name: 'Aarhus University', slug: 'aarhus-university',
    countrySlug: 'denmark', city: 'Aarhus', institutionType: 'Public', founded: 1928,
    character: 'Aarhus University is a large research university in Denmark’s second city.',
    strengths: ['business and economics', 'agricultural science', 'engineering', 'the natural sciences', 'health sciences'],
    teaching: 'Research-led teaching with English-taught master’s programmes.',
    campus: 'A central park campus in Aarhus with its distinctive yellow-brick buildings.',
    afterwards: 'Graduates move into business, research, agriculture and health.',
  }),
  U({
    name: 'Aalborg University', slug: 'aalborg-university',
    countrySlug: 'denmark', city: 'Aalborg', institutionType: 'Public', founded: 1974,
    character: 'Aalborg University is known for problem-based learning, in which students work in project groups throughout their degree.',
    strengths: ['engineering', 'urban planning', 'wireless communication', 'computer science', 'sustainable design'],
    teaching: 'Every semester is built around a group project on a real problem.',
    campus: 'Campuses in Aalborg, Copenhagen and Esbjerg.',
    afterwards: 'Graduates are known among employers for teamwork and project skills.',
  }),
  // ------------------------------------------------------------------ Finland
  U({
    name: 'University of Helsinki', slug: 'university-of-helsinki',
    countrySlug: 'finland', city: 'Helsinki', institutionType: 'Public', founded: 1640, featured: true,
    character: 'The University of Helsinki is Finland’s oldest and largest university.',
    strengths: ['education', 'the life sciences', 'computer science', 'environmental science', 'law'],
    teaching: 'Research-led teaching with many English-taught master’s programmes.',
    campus: 'Four campuses across Helsinki, including one in the historic centre.',
    afterwards: 'Graduates move into research, public service, education and technology.',
  }),
  U({
    name: 'Aalto University', slug: 'aalto-university',
    countrySlug: 'finland', city: 'Espoo', institutionType: 'Public', founded: 2010, featured: true,
    character: 'Aalto University brings together technology, business and art and design in a single university.',
    strengths: ['engineering', 'design', 'business', 'computer science', 'architecture'],
    teaching: 'Interdisciplinary and project-based, with a strong entrepreneurship culture.',
    campus: 'A campus in Otaniemi, Espoo, connected to central Helsinki by metro.',
    afterwards: 'Graduates join technology companies, design studios and start-ups.',
  }),
  U({
    name: 'Tampere University', slug: 'tampere-university',
    countrySlug: 'finland', city: 'Tampere', institutionType: 'Public', founded: 2019,
    character: 'Tampere University was formed from the merger of a university and a university of technology, combining technology, health and society.',
    strengths: ['engineering', 'computer science', 'health sciences', 'social sciences', 'education'],
    teaching: 'English-taught master’s programmes with close company collaboration.',
    campus: 'Campuses in the city centre and at Hervanta, a technology district.',
    afterwards: 'Graduates join technology, health and industrial companies.',
  }),
  U({
    name: 'University of Turku', slug: 'university-of-turku',
    countrySlug: 'finland', city: 'Turku', institutionType: 'Public', founded: 1920,
    character: 'The University of Turku is a multidisciplinary university on Finland’s south-west coast.',
    strengths: ['medicine', 'biotechnology', 'education', 'economics', 'computer science'],
    teaching: 'Research-led teaching with English-taught master’s programmes.',
    campus: 'A campus close to the city centre, shared with other institutions.',
    afterwards: 'Graduates move into health, research and business.',
  }),
  U({
    name: 'University of Oulu', slug: 'university-of-oulu',
    countrySlug: 'finland', city: 'Oulu', institutionType: 'Public', founded: 1958,
    character: 'The University of Oulu is known for research in wireless communication and technology.',
    strengths: ['wireless communication', 'electrical engineering', 'computer science', 'biology', 'geosciences'],
    teaching: 'Engineering and science programmes with English-taught master’s degrees.',
    campus: 'A main campus at Linnanmaa, north of the city centre.',
    afterwards: 'Graduates join telecommunications and technology companies.',
  }),
  // -------------------------------------------------------------- Switzerland
  U({
    name: 'ETH Zurich', slug: 'eth-zurich',
    countrySlug: 'switzerland', city: 'Zurich', institutionType: 'Public', founded: 1855, featured: true,
    character: 'ETH Zurich is Switzerland’s federal institute of technology in the German-speaking part of the country, known for science and engineering.',
    strengths: ['engineering', 'computer science', 'physics', 'chemistry', 'architecture'],
    teaching: 'Demanding science and engineering programmes, with master’s teaching largely in English.',
    campus: 'A central campus overlooking Zurich and a science campus at Hönggerberg.',
    afterwards: 'Graduates move into research, engineering, technology and finance.',
  }),
  U({
    name: 'EPFL', slug: 'epfl',
    countrySlug: 'switzerland', city: 'Lausanne', institutionType: 'Public', founded: 1969, featured: true,
    character: 'EPFL is Switzerland’s federal institute of technology in the French-speaking part of the country.',
    strengths: ['engineering', 'computer science', 'life sciences', 'architecture', 'mathematics'],
    teaching: 'Bachelor’s teaching in French, with master’s programmes largely in English.',
    campus: 'A lakeside campus on the shore of Lake Geneva, shared with the University of Lausanne.',
    afterwards: 'Graduates join technology companies, research and start-ups.',
  }),
  U({
    name: 'University of Zurich', slug: 'university-of-zurich',
    countrySlug: 'switzerland', city: 'Zurich', institutionType: 'Public', founded: 1833,
    character: 'The University of Zurich is Switzerland’s largest university, with a broad range of faculties.',
    strengths: ['medicine', 'economics', 'law', 'the life sciences', 'the humanities'],
    teaching: 'Mostly in German, with English-taught master’s programmes in several fields.',
    campus: 'A main building in central Zurich and a science campus at Irchel.',
    afterwards: 'Graduates move into health, finance, law and research.',
  }),
  U({
    name: 'University of Geneva', slug: 'university-of-geneva',
    countrySlug: 'switzerland', city: 'Geneva', institutionType: 'Public', founded: 1559,
    character: 'The University of Geneva is known for international relations, law and the sciences.',
    strengths: ['international law', 'international relations', 'physics', 'medicine', 'translation'],
    teaching: 'Mostly in French, with English-taught master’s programmes in international fields.',
    campus: 'Buildings across Geneva, near the city’s international organisations.',
    afterwards: 'Graduates go into international organisations, law and research.',
  }),
  U({
    name: 'University of Basel', slug: 'university-of-basel',
    countrySlug: 'switzerland', city: 'Basel', institutionType: 'Public', founded: 1460,
    character: 'The University of Basel is Switzerland’s oldest university, with strengths in the life sciences.',
    strengths: ['the life sciences', 'medicine', 'pharmaceutical sciences', 'economics', 'the humanities'],
    teaching: 'Mostly in German, with English-taught master’s programmes in the sciences.',
    campus: 'Buildings in Basel’s old town, near the city’s pharmaceutical companies.',
    afterwards: 'Graduates join the pharmaceutical industry, research and healthcare.',
  }),
  // -------------------------------------------------------------------- Japan
  U({
    name: 'University of Tokyo', slug: 'university-of-tokyo',
    countrySlug: 'japan', city: 'Tokyo', institutionType: 'Public', founded: 1877, featured: true,
    character: 'The University of Tokyo is Japan’s leading national university, strong across the sciences, engineering and the humanities.',
    strengths: ['engineering', 'physics', 'medicine', 'economics', 'law'],
    teaching: 'Mostly in Japanese, with English-taught programmes at undergraduate and graduate level.',
    campus: 'A historic main campus at Hongo in central Tokyo, with further campuses in the city.',
    afterwards: 'Graduates move into research, government and Japan’s leading companies.',
  }),
  U({
    name: 'Kyoto University', slug: 'kyoto-university',
    countrySlug: 'japan', city: 'Kyoto', institutionType: 'Public', founded: 1897, featured: true,
    character: 'Kyoto University is a national research university known for a tradition of independent scientific thinking.',
    strengths: ['chemistry', 'physics', 'medicine', 'engineering', 'ecology'],
    teaching: 'Research-focused, with English-taught graduate programmes in several fields.',
    campus: 'A main campus in the north-east of Kyoto, with further campuses in the region.',
    afterwards: 'Graduates are strongly represented in research and science-based industry.',
  }),
  U({
    name: 'Osaka University', slug: 'osaka-university',
    countrySlug: 'japan', city: 'Osaka', institutionType: 'Public', founded: 1931,
    character: 'Osaka University is a national university known for engineering, medicine and the life sciences.',
    strengths: ['engineering', 'medicine', 'immunology', 'materials science', 'foreign studies'],
    teaching: 'Mostly in Japanese, with English-taught programmes in science and engineering.',
    campus: 'Campuses at Suita, Toyonaka and Minoh in the Osaka area.',
    afterwards: 'Graduates join manufacturing, pharmaceutical and technology companies.',
  }),
  U({
    name: 'Tohoku University', slug: 'tohoku-university',
    countrySlug: 'japan', city: 'Sendai', institutionType: 'Public', founded: 1907,
    character: 'Tohoku University is a national research university in Sendai, known for materials science and engineering.',
    strengths: ['materials science', 'engineering', 'physics', 'medicine', 'disaster science'],
    teaching: 'Research-led, with English-taught undergraduate and graduate programmes.',
    campus: 'Several campuses around Sendai.',
    afterwards: 'Graduates join research institutes and engineering companies.',
  }),
  U({
    name: 'Waseda University', slug: 'waseda-university',
    countrySlug: 'japan', city: 'Tokyo', institutionType: 'Private', founded: 1882,
    character: 'Waseda is one of Japan’s best-known private universities, strong in politics, economics and the humanities.',
    strengths: ['political science and economics', 'international studies', 'business', 'engineering', 'literature'],
    teaching: 'A large number of English-taught undergraduate programmes alongside Japanese-taught degrees.',
    campus: 'A main campus in Shinjuku, Tokyo, with further campuses in and around the city.',
    afterwards: 'Graduates go into business, media, politics and public service.',
  }),
  // -------------------------------------------------------------- South Korea
  U({
    name: 'Seoul National University', slug: 'seoul-national-university',
    countrySlug: 'south-korea', city: 'Seoul', institutionType: 'Public', founded: 1946, featured: true,
    character: 'Seoul National University is South Korea’s leading national university.',
    strengths: ['engineering', 'natural sciences', 'medicine', 'economics', 'law'],
    teaching: 'Mostly in Korean, with English-taught courses and graduate programmes.',
    campus: 'A large campus at Gwanak in southern Seoul.',
    afterwards: 'Graduates move into research, government and South Korea’s major companies.',
  }),
  U({
    name: 'KAIST', slug: 'kaist',
    countrySlug: 'south-korea', city: 'Daejeon', institutionType: 'Public', founded: 1971, featured: true,
    character: 'KAIST is South Korea’s leading science and technology university.',
    strengths: ['electrical engineering', 'computer science', 'mechanical engineering', 'materials science', 'biological engineering'],
    teaching: 'Most courses taught in English, with a strong emphasis on research.',
    campus: 'A main campus in Daejeon’s science district, with a campus in Seoul.',
    afterwards: 'Graduates join technology companies, research institutes and start-ups.',
  }),
  U({
    name: 'Yonsei University', slug: 'yonsei-university',
    countrySlug: 'south-korea', city: 'Seoul', institutionType: 'Private', founded: 1885,
    character: 'Yonsei is one of South Korea’s oldest private universities, known for its international college.',
    strengths: ['medicine', 'business', 'international studies', 'engineering', 'Korean studies'],
    teaching: 'An international college teaching in English alongside Korean-taught programmes.',
    campus: 'A main campus at Sinchon in western Seoul, with a residential campus at Songdo.',
    afterwards: 'Graduates go into business, medicine and international careers.',
  }),
  U({
    name: 'Korea University', slug: 'korea-university',
    countrySlug: 'south-korea', city: 'Seoul', institutionType: 'Private', founded: 1905,
    character: 'Korea University is a leading private university with strengths in business, law and engineering.',
    strengths: ['business', 'law', 'engineering', 'medicine', 'political science'],
    teaching: 'A mix of Korean- and English-taught courses, with a large international summer school.',
    campus: 'A main campus at Anam in north-east Seoul.',
    afterwards: 'Graduates move into business, law and public service.',
  }),
  U({
    name: 'POSTECH', slug: 'postech',
    countrySlug: 'south-korea', city: 'Pohang', institutionType: 'Private', founded: 1986,
    character: 'POSTECH is a small, research-intensive science and technology university founded with the support of the steel industry.',
    strengths: ['materials science', 'chemical engineering', 'physics', 'mechanical engineering', 'life sciences'],
    teaching: 'Small classes, bilingual teaching and early research involvement.',
    campus: 'A residential campus in Pohang with research institutes on site.',
    afterwards: 'Graduates join research institutes and advanced manufacturing companies.',
  }),
  // ----------------------------------------------------- United Arab Emirates
  U({
    name: 'Khalifa University', slug: 'khalifa-university',
    countrySlug: 'united-arab-emirates', city: 'Abu Dhabi', institutionType: 'Public', founded: 2007, featured: true,
    character: 'Khalifa University is a research university in Abu Dhabi focused on science, engineering and medicine.',
    strengths: ['petroleum engineering', 'aerospace engineering', 'electrical engineering', 'computer science', 'medicine'],
    teaching: 'Taught in English, with a research-focused graduate programme.',
    campus: 'A main campus in Abu Dhabi city, with further campuses in the emirate.',
    afterwards: 'Graduates join energy, aerospace and technology companies in the region.',
  }),
  U({
    name: 'United Arab Emirates University', slug: 'united-arab-emirates-university',
    countrySlug: 'united-arab-emirates', city: 'Al Ain', institutionType: 'Public', founded: 1976,
    character: 'UAE University is the country’s first national university.',
    strengths: ['engineering', 'medicine and health sciences', 'agriculture', 'business', 'education'],
    teaching: 'Largely in English, with a broad range of undergraduate and graduate programmes.',
    campus: 'A large campus in Al Ain.',
    afterwards: 'Graduates move into government, healthcare, engineering and education.',
  }),
  U({
    name: 'American University of Sharjah', slug: 'american-university-of-sharjah',
    countrySlug: 'united-arab-emirates', city: 'Sharjah', institutionType: 'Private', founded: 1997,
    character: 'The American University of Sharjah follows an American model of higher education.',
    strengths: ['engineering', 'architecture and design', 'business', 'computer science', 'international studies'],
    teaching: 'An American-style curriculum taught in English, with general education requirements.',
    campus: 'A campus in Sharjah’s university city.',
    afterwards: 'Graduates join engineering, business and design firms across the Gulf.',
  }),
  U({
    name: 'University of Wollongong in Dubai', slug: 'university-of-wollongong-in-dubai',
    countrySlug: 'united-arab-emirates', city: 'Dubai', institutionType: 'Private', founded: 1993,
    character: 'The University of Wollongong in Dubai is an Australian university’s campus in the United Arab Emirates.',
    strengths: ['business', 'finance', 'computer science', 'engineering', 'media'],
    teaching: 'An Australian-style curriculum taught in English, with several intakes a year.',
    campus: 'A campus in Dubai Knowledge Park.',
    afterwards: 'Graduates join business, finance and technology roles in Dubai.',
  }),
  U({
    name: 'Heriot-Watt University Dubai', slug: 'heriot-watt-university-dubai',
    countrySlug: 'united-arab-emirates', city: 'Dubai', institutionType: 'Private', founded: 2005,
    character: 'Heriot-Watt University Dubai is the Dubai campus of a Scottish university, awarding the same degrees as the home campus.',
    strengths: ['engineering', 'business', 'computer science', 'actuarial science', 'fashion'],
    teaching: 'A British curriculum taught in English, with transfer options to the Scottish and Malaysian campuses.',
    campus: 'A campus in Dubai Knowledge Park.',
    afterwards: 'Graduates join engineering, business and technology roles across the region.',
  }),
];
