/**
 * The countries whose flag artwork ships with the site.
 *
 * Generated beside public/flags: asking this before rendering an <img>
 * is what keeps a record with an unknown ISO code from drawing a broken
 * image instead of its colour bands.
 *
 * Generated by scripts/country-table/generate.mjs -- edit that, not this.
 * ISO codes and currencies from world-countries (ISO 3166 / 4217); flag
 * colours measured from the flag-icons SVGs (MIT) by rendering and counting
 * pixels, so a share is the share of the flag a colour covers.
 */
export const FLAG_CODES: ReadonlySet<string> = new Set(["ad","ae","af","ag","al","am","ao","ar","at","au","aw","az","ba","bb","bd","be","bf","bg","bh","bi","bj","bm","bn","bo","br","bs","bt","bw","by","bz","ca","cd","cf","cg","ch","ci","cl","cm","cn","co","cr","cu","cv","cw","cy","cz","de","dj","dk","dm","do","dz","ec","ee","eg","er","es","et","fi","fj","fm","fr","ga","gb","gd","ge","gh","gl","gm","gn","gq","gr","gt","gw","gy","hk","hn","hr","ht","hu","id","ie","il","in","iq","ir","is","it","jm","jo","jp","ke","kg","kh","ki","km","kn","kp","kr","kw","ky","kz","la","lb","lc","li","lk","lr","ls","lt","lu","lv","ly","ma","mc","md","me","mg","mh","mk","ml","mm","mn","mo","mr","mt","mu","mv","mw","mx","my","mz","na","nc","ne","ng","ni","nl","no","np","nr","nz","om","pa","pe","pg","ph","pk","pl","pr","ps","pt","pw","py","qa","ro","rs","ru","rw","sa","sb","sc","sd","se","sg","si","sk","sl","sm","sn","so","sr","ss","st","sv","sy","sz","td","tg","th","tj","tl","tm","tn","to","tr","tt","tv","tw","tz","ua","ug","us","uy","uz","va","vc","ve","vn","vu","ws","xk","ye","za","zm","zw"]);

/** Whether the site can draw this country's flag. */
export function hasFlag(iso2Code: string | null | undefined): boolean {
  const code = iso2Code?.trim().toLowerCase();
  return code ? FLAG_CODES.has(code) : false;
}
